
/*
 * Copyright (c) 2020-2021 The reone project contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/** @file
 *  TSL routines registration.
 */

#include "routines.h"

using namespace std;

using namespace reone::script;

namespace reone {

namespace game {

#define Void VariableType::Void
#define Int VariableType::Int
#define Float VariableType::Float
#define Object VariableType::Object
#define String VariableType::String
#define Effect VariableType::Effect
#define Event VariableType::Event
#define Location VariableType::Location
#define Talent VariableType::Talent
#define TVector VariableType::Vector
#define Action VariableType::Action

void Routines::addTslRoutines() {
    add("Random", Int, { Int }, &Routines::random);
    add("PrintString", Void, { String }, &Routines::printString);
    add("PrintFloat", Void, { Float, Int, Int }, &Routines::printFloat);
    add("FloatToString", String, { Float, Int, Int }, &Routines::floatToString);
    add("PrintInteger", Void, { Int }, &Routines::printInteger);
    add("PrintObject", Void, { Object }, &Routines::printObject);
    add("AssignCommand", Void, { Object, Action }, &Routines::assignCommand);
    add("DelayCommand", Void, { Float, Action }, &Routines::delayCommand);
    add("ExecuteScript", Void, { String, Object, Int }, &Routines::executeScript);
    add("ClearAllActions", Void, { }, &Routines::clearAllActions);
    add("SetFacing", Void, { Float }, &Routines::setFacing);
    add("SwitchPlayerCharacter", Int, { Int }, &Routines::switchPlayerCharacter);
    add("SetTime", Void, { Int, Int, Int, Int }, &Routines::setTime);
    add("SetPartyLeader", Int, { Int }, &Routines::setPartyLeader);
    add("SetAreaUnescapable", Void, { Int }, &Routines::setAreaUnescapable);
    add("GetAreaUnescapable", Int, { }, &Routines::getAreaUnescapable);
    add("GetTimeHour", Int, { }, &Routines::getTimeHour);
    add("GetTimeMinute", Int, { }, &Routines::getTimeMinute);
    add("GetTimeSecond", Int, { }, &Routines::getTimeSecond);
    add("GetTimeMillisecond", Int, { }, &Routines::getTimeMillisecond);
    add("ActionRandomWalk", Void, { }, &Routines::actionRandomWalk);
    add("ActionMoveToLocation", Void, { Location, Int }, &Routines::actionMoveToLocation);
    add("ActionMoveToObject", Void, { Object, Int, Float }, &Routines::actionMoveToObject);
    add("ActionMoveAwayFromObject", Void, { Object, Int, Float }, &Routines::actionMoveAwayFromObject);
    add("GetArea", Object, { Object }, &Routines::getArea);
    add("GetEnteringObject", Object, { }, &Routines::getEnteringObject);
    add("GetExitingObject", Object, { }, &Routines::getExitingObject);
    add("GetPosition", TVector, { Object }, &Routines::getPosition);
    add("GetFacing", Float, { Object }, &Routines::getFacing);
    add("GetItemPossessor", Object, { Object }, &Routines::getItemPossessor);
    add("GetItemPossessedBy", Object, { Object, String }, &Routines::getItemPossessedBy);
    add("CreateItemOnObject", Object, { String, Object, Int, Int }, &Routines::createItemOnObject);
    add("ActionEquipItem", Void, { Object, Int, Int }, &Routines::actionEquipItem);
    add("ActionUnequipItem", Void, { Object, Int }, &Routines::actionUnequipItem);
    add("ActionPickUpItem", Void, { Object }, &Routines::actionPickUpItem);
    add("ActionPutDownItem", Void, { Object }, &Routines::actionPutDownItem);
    add("GetLastAttacker", Object, { Object }, &Routines::getLastAttacker);
    add("ActionAttack", Void, { Object, Int }, &Routines::actionAttack);
    add("GetNearestCreature", Object, { Int, Int, Object, Int, Int, Int, Int, Int }, &Routines::getNearestCreature);
    add("ActionSpeakString", Void, { String, Int }, &Routines::actionSpeakString);
    add("ActionPlayAnimation", Void, { Int, Float, Float }, &Routines::actionPlayAnimation);
    add("GetDistanceToObject", Float, { Object }, &Routines::getDistanceToObject);
    add("GetIsObjectValid", Int, { Object }, &Routines::getIsObjectValid);
    add("ActionOpenDoor", Void, { Object }, &Routines::actionOpenDoor);
    add("ActionCloseDoor", Void, { Object }, &Routines::actionCloseDoor);
    add("SetCameraFacing", Void, { Float }, &Routines::setCameraFacing);
    add("PlaySound", Void, { String }, &Routines::playSound);
    add("GetSpellTargetObject", Object, { }, &Routines::getSpellTargetObject);
    add("ActionCastSpellAtObject", Void, { Int, Object, Int, Int, Int, Int, Int }, &Routines::actionCastSpellAtObject);
    add("GetCurrentHitPoints", Int, { Object }, &Routines::getCurrentHitPoints);
    add("GetMaxHitPoints", Int, { Object }, &Routines::getMaxHitPoints);
    add("EffectAssuredHit", Effect, { }, &Routines::effectAssuredHit);
    add("GetLastItemEquipped", Object, { }, &Routines::getLastItemEquipped);
    add("GetSubScreenID", Int, { }, &Routines::getSubScreenID);
    add("CancelCombat", Void, { Object }, &Routines::cancelCombat);
    add("GetCurrentForcePoints", Int, { Object }, &Routines::getCurrentForcePoints);
    add("GetMaxForcePoints", Int, { Object }, &Routines::getMaxForcePoints);
    add("PauseGame", Void, { Int }, &Routines::pauseGame);
    add("SetPlayerRestrictMode", Void, { Int }, &Routines::setPlayerRestrictMode);
    add("GetStringLength", Int, { String }, &Routines::getStringLength);
    add("GetStringUpperCase", String, { String }, &Routines::getStringUpperCase);
    add("GetStringLowerCase", String, { String }, &Routines::getStringLowerCase);
    add("GetStringRight", String, { String, Int }, &Routines::getStringRight);
    add("GetStringLeft", String, { String, Int }, &Routines::getStringLeft);
    add("InsertString", String, { String, String, Int }, &Routines::insertString);
    add("GetSubString", String, { String, Int, Int }, &Routines::getSubString);
    add("FindSubString", Int, { String, String }, &Routines::findSubString);
    add("fabs", Float, { Float }, &Routines::fabs);
    add("cos", Float, { Float }, &Routines::cos);
    add("sin", Float, { Float }, &Routines::sin);
    add("tan", Float, { Float }, &Routines::tan);
    add("acos", Float, { Float }, &Routines::acos);
    add("asin", Float, { Float }, &Routines::asin);
    add("atan", Float, { Float }, &Routines::atan);
    add("log", Float, { Float }, &Routines::log);
    add("pow", Float, { Float, Float }, &Routines::pow);
    add("sqrt", Float, { Float }, &Routines::sqrt);
    add("abs", Int, { Int }, &Routines::abs);
    add("EffectHeal", Effect, { Int }, &Routines::effectHeal);
    add("EffectDamage", Effect, { Int, Int, Int }, &Routines::effectDamage);
    add("EffectAbilityIncrease", Effect, { Int, Int }, &Routines::effectAbilityIncrease);
    add("EffectDamageResistance", Effect, { Int, Int, Int }, &Routines::effectDamageResistance);
    add("EffectResurrection", Effect, { Int }, &Routines::effectResurrection);
    add("GetPlayerRestrictMode", Int, { Object }, &Routines::getPlayerRestrictMode);
    add("GetCasterLevel", Int, { Object }, &Routines::getCasterLevel);
    add("GetFirstEffect", Effect, { Object }, &Routines::getFirstEffect);
    add("GetNextEffect", Effect, { Object }, &Routines::getNextEffect);
    add("RemoveEffect", Void, { Object, Effect }, &Routines::removeEffect);
    add("GetIsEffectValid", Int, { Effect }, &Routines::getIsEffectValid);
    add("GetEffectDurationType", Int, { Effect }, &Routines::getEffectDurationType);
    add("GetEffectSubType", Int, { Effect }, &Routines::getEffectSubType);
    add("GetEffectCreator", Object, { Effect }, &Routines::getEffectCreator);
    add("IntToString", String, { Int }, &Routines::intToString);
    add("GetFirstObjectInArea", Object, { Object, Int }, &Routines::getFirstObjectInArea);
    add("GetNextObjectInArea", Object, { Object, Int }, &Routines::getNextObjectInArea);
    add("d2", Int, { Int }, &Routines::d2);
    add("d3", Int, { Int }, &Routines::d3);
    add("d4", Int, { Int }, &Routines::d4);
    add("d6", Int, { Int }, &Routines::d6);
    add("d8", Int, { Int }, &Routines::d8);
    add("d10", Int, { Int }, &Routines::d10);
    add("d12", Int, { Int }, &Routines::d12);
    add("d20", Int, { Int }, &Routines::d20);
    add("d100", Int, { Int }, &Routines::d100);
    add("VectorMagnitude", Float, { TVector }, &Routines::vectorMagnitude);
    add("GetMetaMagicFeat", Int, { }, &Routines::getMetaMagicFeat);
    add("GetObjectType", Int, { Object }, &Routines::getObjectType);
    add("GetRacialType", Int, { Object }, &Routines::getRacialType);
    add("FortitudeSave", Int, { Object, Int, Int, Object }, &Routines::fortitudeSave);
    add("ReflexSave", Int, { Object, Int, Int, Object }, &Routines::reflexSave);
    add("WillSave", Int, { Object, Int, Int, Object }, &Routines::willSave);
    add("GetSpellSaveDC", Int, { }, &Routines::getSpellSaveDC);
    add("MagicalEffect", Effect, { Effect }, &Routines::magicalEffect);
    add("SupernaturalEffect", Effect, { Effect }, &Routines::supernaturalEffect);
    add("ExtraordinaryEffect", Effect, { Effect }, &Routines::extraordinaryEffect);
    add("EffectACIncrease", Effect, { Int, Int, Int }, &Routines::effectACIncrease);
    add("GetAC", Int, { Object, Int }, &Routines::getAC);
    add("EffectSavingThrowIncrease", Effect, { Int, Int, Int }, &Routines::effectSavingThrowIncrease);
    add("EffectAttackIncrease", Effect, { Int, Int }, &Routines::effectAttackIncrease);
    add("EffectDamageReduction", Effect, { Int, Int, Int }, &Routines::effectDamageReduction);
    add("EffectDamageIncrease", Effect, { Int, Int }, &Routines::effectDamageIncrease);
    add("RoundsToSeconds", Float, { Int }, &Routines::roundsToSeconds);
    add("HoursToSeconds", Float, { Int }, &Routines::hoursToSeconds);
    add("TurnsToSeconds", Float, { Int }, &Routines::turnsToSeconds);
    add("SoundObjectSetFixedVariance", Void, { Object, Float }, &Routines::soundObjectSetFixedVariance);
    add("GetGoodEvilValue", Int, { Object }, &Routines::getGoodEvilValue);
    add("GetPartyMemberCount", Int, { }, &Routines::getPartyMemberCount);
    add("GetAlignmentGoodEvil", Int, { Object }, &Routines::getAlignmentGoodEvil);
    add("GetFirstObjectInShape", Object, { Int, Float, Location, Int, Int, TVector }, &Routines::getFirstObjectInShape);
    add("GetNextObjectInShape", Object, { Int, Float, Location, Int, Int, TVector }, &Routines::getNextObjectInShape);
    add("EffectEntangle", Effect, { }, &Routines::effectEntangle);
    add("SignalEvent", Void, { Object, Event }, &Routines::signalEvent);
    add("EventUserDefined", Event, { Int }, &Routines::eventUserDefined);
    add("EffectDeath", Effect, { Int, Int, Int }, &Routines::effectDeath);
    add("EffectKnockdown", Effect, { }, &Routines::effectKnockdown);
    add("ActionGiveItem", Void, { Object, Object }, &Routines::actionGiveItem);
    add("ActionTakeItem", Void, { Object, Object }, &Routines::actionTakeItem);
    add("VectorNormalize", TVector, { TVector }, &Routines::vectorNormalize);
    add("GetItemStackSize", Int, { Object }, &Routines::getItemStackSize);
    add("GetAbilityScore", Int, { Object, Int }, &Routines::getAbilityScore);
    add("GetIsDead", Int, { Object }, &Routines::getIsDead);
    add("PrintVector", Void, { TVector, Int }, &Routines::printVector);
    add("Vector", TVector, { Float, Float, Float }, &Routines::vectorCreate);
    add("SetFacingPoint", Void, { TVector }, &Routines::setFacingPoint);
    add("AngleToVector", TVector, { Float }, &Routines::angleToVector);
    add("VectorToAngle", Float, { TVector }, &Routines::vectorToAngle);
    add("TouchAttackMelee", Int, { Object, Int }, &Routines::touchAttackMelee);
    add("TouchAttackRanged", Int, { Object, Int }, &Routines::touchAttackRanged);
    add("EffectParalyze", Effect, { }, &Routines::effectParalyze);
    add("EffectSpellImmunity", Effect, { Int }, &Routines::effectSpellImmunity);
    add("SetItemStackSize", Void, { Object, Int }, &Routines::setItemStackSize);
    add("GetDistanceBetween", Float, { Object, Object }, &Routines::getDistanceBetween);
    add("SetReturnStrref", Void, { Int, Int, Int }, &Routines::setReturnStrref);
    add("EffectForceJump", Effect, { Object, Int }, &Routines::effectForceJump);
    add("EffectSleep", Effect, { }, &Routines::effectSleep);
    add("GetItemInSlot", Object, { Int, Object }, &Routines::getItemInSlot);
    add("EffectTemporaryForcePoints", Effect, { Int }, &Routines::effectTemporaryForcePoints);
    add("EffectConfused", Effect, { }, &Routines::effectConfused);
    add("EffectFrightened", Effect, { }, &Routines::effectFrightened);
    add("EffectChoke", Effect, { }, &Routines::effectChoke);
    add("SetGlobalString", Void, { String, String }, &Routines::setGlobalString);
    add("EffectStunned", Effect, { }, &Routines::effectStunned);
    add("SetCommandable", Void, { Int, Object }, &Routines::setCommandable);
    add("GetCommandable", Int, { Object }, &Routines::getCommandable);
    add("EffectRegenerate", Effect, { Int, Float }, &Routines::effectRegenerate);
    add("EffectMovementSpeedIncrease", Effect, { Int }, &Routines::effectMovementSpeedIncrease);
    add("GetHitDice", Int, { Object }, &Routines::getHitDice);
    add("ActionForceFollowObject", Void, { Object, Float }, &Routines::actionForceFollowObject);
    add("GetTag", String, { Object }, &Routines::getTag);
    add("ResistForce", Int, { Object, Object }, &Routines::resistForce);
    add("GetEffectType", Int, { Effect }, &Routines::getEffectType);
    add("EffectAreaOfEffect", Effect, { Int, String, String, String }, &Routines::effectAreaOfEffect);
    add("GetFactionEqual", Int, { Object, Object }, &Routines::getFactionEqual);
    add("ChangeFaction", Void, { Object, Object }, &Routines::changeFaction);
    add("GetIsListening", Int, { Object }, &Routines::getIsListening);
    add("SetListening", Void, { Object, Int }, &Routines::setListening);
    add("SetListenPattern", Void, { Object, String, Int }, &Routines::setListenPattern);
    add("TestStringAgainstPattern", Int, { String, String }, &Routines::testStringAgainstPattern);
    add("GetMatchedSubstring", String, { Int }, &Routines::getMatchedSubstring);
    add("GetMatchedSubstringsCount", Int, { }, &Routines::getMatchedSubstringsCount);
    add("EffectVisualEffect", Effect, { Int, Int }, &Routines::effectVisualEffect);
    add("GetFactionWeakestMember", Object, { Object, Int }, &Routines::getFactionWeakestMember);
    add("GetFactionStrongestMember", Object, { Object, Int }, &Routines::getFactionStrongestMember);
    add("GetFactionMostDamagedMember", Object, { Object, Int }, &Routines::getFactionMostDamagedMember);
    add("GetFactionLeastDamagedMember", Object, { Object, Int }, &Routines::getFactionLeastDamagedMember);
    add("GetFactionGold", Int, { Object }, &Routines::getFactionGold);
    add("GetFactionAverageReputation", Int, { Object, Object }, &Routines::getFactionAverageReputation);
    add("GetFactionAverageGoodEvilAlignment", Int, { Object }, &Routines::getFactionAverageGoodEvilAlignment);
    add("SoundObjectGetFixedVariance", Float, { Object }, &Routines::soundObjectGetFixedVariance);
    add("GetFactionAverageLevel", Int, { Object }, &Routines::getFactionAverageLevel);
    add("GetFactionAverageXP", Int, { Object }, &Routines::getFactionAverageXP);
    add("GetFactionMostFrequentClass", Int, { Object }, &Routines::getFactionMostFrequentClass);
    add("GetFactionWorstAC", Object, { Object, Int }, &Routines::getFactionWorstAC);
    add("GetFactionBestAC", Object, { Object, Int }, &Routines::getFactionBestAC);
    add("GetGlobalString", String, { String }, &Routines::getGlobalString);
    add("GetListenPatternNumber", Int, { }, &Routines::getListenPatternNumber);
    add("ActionJumpToObject", Void, { Object, Int }, &Routines::actionJumpToObject);
    add("GetWaypointByTag", Object, { String }, &Routines::getWaypointByTag);
    add("GetTransitionTarget", Object, { Object }, &Routines::getTransitionTarget);
    add("EffectLinkEffects", Effect, { Effect, Effect }, &Routines::effectLinkEffects);
    add("GetObjectByTag", Object, { String, Int }, &Routines::getObjectByTag);
    add("AdjustAlignment", Void, { Object, Int, Int, Int }, &Routines::adjustAlignment);
    add("ActionWait", Void, { Float }, &Routines::actionWait);
    add("SetAreaTransitionBMP", Void, { Int, String }, &Routines::setAreaTransitionBMP);
    add("ActionStartConversation", Void, { Object, String, Int, Int, Int, String, String, String, String, String, String, Int, Int, Int, Int }, &Routines::actionStartConversation);
    add("ActionPauseConversation", Void, { }, &Routines::actionPauseConversation);
    add("ActionResumeConversation", Void, { }, &Routines::actionResumeConversation);
    add("EffectBeam", Effect, { Int, Object, Int, Int }, &Routines::effectBeam);
    add("GetReputation", Int, { Object, Object }, &Routines::getReputation);
    add("AdjustReputation", Void, { Object, Object, Int }, &Routines::adjustReputation);
    add("GetModuleFileName", String, { }, &Routines::getModuleFileName);
    add("GetGoingToBeAttackedBy", Object, { Object }, &Routines::getGoingToBeAttackedBy);
    add("EffectForceResistanceIncrease", Effect, { Int }, &Routines::effectForceResistanceIncrease);
    add("GetLocation", Location, { Object }, &Routines::getLocation);
    add("ActionJumpToLocation", Void, { Location }, &Routines::actionJumpToLocation);
    add("Location", Location, { TVector, Float }, &Routines::location);
    add("ApplyEffectAtLocation", Void, { Int, Effect, Location, Float }, &Routines::applyEffectAtLocation);
    add("GetIsPC", Int, { Object }, &Routines::getIsPC);
    add("FeetToMeters", Float, { Float }, &Routines::feetToMeters);
    add("YardsToMeters", Float, { Float }, &Routines::yardsToMeters);
    add("ApplyEffectToObject", Void, { Int, Effect, Object, Float }, &Routines::applyEffectToObject);
    add("SpeakString", Void, { String, Int }, &Routines::speakString);
    add("GetSpellTargetLocation", Location, { }, &Routines::getSpellTargetLocation);
    add("GetPositionFromLocation", TVector, { Location }, &Routines::getPositionFromLocation);
    add("EffectBodyFuel", Effect, { }, &Routines::effectBodyFuel);
    add("GetFacingFromLocation", Float, { Location }, &Routines::getFacingFromLocation);
    add("GetNearestCreatureToLocation", Object, { Int, Int, Location, Int, Int, Int, Int, Int }, &Routines::getNearestCreatureToLocation);
    add("GetNearestObject", Object, { Int, Object, Int }, &Routines::getNearestObject);
    add("GetNearestObjectToLocation", Object, { Int, Location, Int }, &Routines::getNearestObjectToLocation);
    add("GetNearestObjectByTag", Object, { String, Object, Int }, &Routines::getNearestObjectByTag);
    add("IntToFloat", Float, { Int }, &Routines::intToFloat);
    add("FloatToInt", Int, { Float }, &Routines::floatToInt);
    add("StringToInt", Int, { String }, &Routines::stringToInt);
    add("StringToFloat", Float, { String }, &Routines::stringToFloat);
    add("ActionCastSpellAtLocation", Void, { Int, Location, Int, Int, Int, Int }, &Routines::actionCastSpellAtLocation);
    add("GetIsEnemy", Int, { Object, Object }, &Routines::getIsEnemy);
    add("GetIsFriend", Int, { Object, Object }, &Routines::getIsFriend);
    add("GetIsNeutral", Int, { Object, Object }, &Routines::getIsNeutral);
    add("GetPCSpeaker", Object, { }, &Routines::getPCSpeaker);
    add("GetStringByStrRef", String, { Int }, &Routines::getStringByStrRef);
    add("ActionSpeakStringByStrRef", Void, { Int, Int }, &Routines::actionSpeakStringByStrRef);
    add("DestroyObject", Void, { Object, Float, Int, Float, Int }, &Routines::destroyObject);
    add("GetModule", Object, { }, &Routines::getModule);
    add("CreateObject", Object, { Int, String, Location, Int }, &Routines::createObject);
    add("EventSpellCastAt", Event, { Object, Int, Int }, &Routines::eventSpellCastAt);
    add("GetLastSpellCaster", Object, { }, &Routines::getLastSpellCaster);
    add("GetLastSpell", Int, { }, &Routines::getLastSpell);
    add("GetUserDefinedEventNumber", Int, { }, &Routines::getUserDefinedEventNumber);
    add("GetSpellId", Int, { }, &Routines::getSpellId);
    add("RandomName", String, { }, &Routines::randomName);
    add("EffectPoison", Effect, { Int }, &Routines::effectPoison);
    add("GetLoadFromSaveGame", Int, { }, &Routines::getLoadFromSaveGame);
    add("EffectAssuredDeflection", Effect, { Int }, &Routines::effectAssuredDeflection);
    add("GetName", String, { Object }, &Routines::getName);
    add("GetLastSpeaker", Object, { }, &Routines::getLastSpeaker);
    add("BeginConversation", Int, { String, Object }, &Routines::beginConversation);
    add("GetLastPerceived", Object, { }, &Routines::getLastPerceived);
    add("GetLastPerceptionHeard", Int, { }, &Routines::getLastPerceptionHeard);
    add("GetLastPerceptionInaudible", Int, { }, &Routines::getLastPerceptionInaudible);
    add("GetLastPerceptionSeen", Int, { }, &Routines::getLastPerceptionSeen);
    add("GetLastClosedBy", Object, { }, &Routines::getLastClosedBy);
    add("GetLastPerceptionVanished", Int, { }, &Routines::getLastPerceptionVanished);
    add("GetFirstInPersistentObject", Object, { Object, Int, Int }, &Routines::getFirstInPersistentObject);
    add("GetNextInPersistentObject", Object, { Object, Int, Int }, &Routines::getNextInPersistentObject);
    add("GetAreaOfEffectCreator", Object, { Object }, &Routines::getAreaOfEffectCreator);
    add("ShowLevelUpGUI", Int, { }, &Routines::showLevelUpGUI);
    add("SetItemNonEquippable", Void, { Object, Int }, &Routines::setItemNonEquippable);
    add("GetButtonMashCheck", Int, { }, &Routines::getButtonMashCheck);
    add("SetButtonMashCheck", Void, { Int }, &Routines::setButtonMashCheck);
    add("EffectForcePushTargeted", Effect, { Location, Int }, &Routines::effectForcePushTargeted);
    add("EffectHaste", Effect, { }, &Routines::effectHaste);
    add("GiveItem", Void, { Object, Object }, &Routines::giveItem);
    add("ObjectToString", String, { Object }, &Routines::objectToString);
    add("EffectImmunity", Effect, { Int }, &Routines::effectImmunity);
    add("GetIsImmune", Int, { Object, Int, Object }, &Routines::getIsImmune);
    add("EffectDamageImmunityIncrease", Effect, { Int, Int }, &Routines::effectDamageImmunityIncrease);
    add("GetEncounterActive", Int, { Object }, &Routines::getEncounterActive);
    add("SetEncounterActive", Void, { Int, Object }, &Routines::setEncounterActive);
    add("GetEncounterSpawnsMax", Int, { Object }, &Routines::getEncounterSpawnsMax);
    add("SetEncounterSpawnsMax", Void, { Int, Object }, &Routines::setEncounterSpawnsMax);
    add("GetEncounterSpawnsCurrent", Int, { Object }, &Routines::getEncounterSpawnsCurrent);
    add("SetEncounterSpawnsCurrent", Void, { Int, Object }, &Routines::setEncounterSpawnsCurrent);
    add("GetModuleItemAcquired", Object, { }, &Routines::getModuleItemAcquired);
    add("GetModuleItemAcquiredFrom", Object, { }, &Routines::getModuleItemAcquiredFrom);
    add("SetCustomToken", Void, { Int, String }, &Routines::setCustomToken);
    add("GetHasFeat", Int, { Int, Object }, &Routines::getHasFeat);
    add("GetHasSkill", Int, { Int, Object }, &Routines::getHasSkill);
    add("ActionUseFeat", Void, { Int, Object }, &Routines::actionUseFeat);
    add("ActionUseSkill", Void, { Int, Object, Int, Object }, &Routines::actionUseSkill);
    add("GetObjectSeen", Int, { Object, Object }, &Routines::getObjectSeen);
    add("GetObjectHeard", Int, { Object, Object }, &Routines::getObjectHeard);
    add("GetLastPlayerDied", Object, { }, &Routines::getLastPlayerDied);
    add("GetModuleItemLost", Object, { }, &Routines::getModuleItemLost);
    add("GetModuleItemLostBy", Object, { }, &Routines::getModuleItemLostBy);
    add("ActionDoCommand", Void, { Action }, &Routines::actionDoCommand);
    add("EventConversation", Event, { }, &Routines::eventConversation);
    add("SetEncounterDifficulty", Void, { Int, Object }, &Routines::setEncounterDifficulty);
    add("GetEncounterDifficulty", Int, { Object }, &Routines::getEncounterDifficulty);
    add("GetDistanceBetweenLocations", Float, { Location, Location }, &Routines::getDistanceBetweenLocations);
    add("GetReflexAdjustedDamage", Int, { Int, Object, Int, Int, Object }, &Routines::getReflexAdjustedDamage);
    add("PlayAnimation", Void, { Int, Float, Float }, &Routines::playAnimation);
    add("TalentSpell", Talent, { Int }, &Routines::talentSpell);
    add("TalentFeat", Talent, { Int }, &Routines::talentFeat);
    add("TalentSkill", Talent, { Int }, &Routines::talentSkill);
    add("GetHasSpellEffect", Int, { Int, Object }, &Routines::getHasSpellEffect);
    add("GetEffectSpellId", Int, { Effect }, &Routines::getEffectSpellId);
    add("GetCreatureHasTalent", Int, { Talent, Object }, &Routines::getCreatureHasTalent);
    add("GetCreatureTalentRandom", Talent, { Int, Object, Int }, &Routines::getCreatureTalentRandom);
    add("GetCreatureTalentBest", Talent, { Int, Int, Object, Int, Int, Int }, &Routines::getCreatureTalentBest);
    add("ActionUseTalentOnObject", Void, { Talent, Object }, &Routines::actionUseTalentOnObject);
    add("ActionUseTalentAtLocation", Void, { Talent, Location }, &Routines::actionUseTalentAtLocation);
    add("GetGoldPieceValue", Int, { Object }, &Routines::getGoldPieceValue);
    add("GetIsPlayableRacialType", Int, { Object }, &Routines::getIsPlayableRacialType);
    add("JumpToLocation", Void, { Location }, &Routines::jumpToLocation);
    add("EffectTemporaryHitpoints", Effect, { Int }, &Routines::effectTemporaryHitpoints);
    add("GetSkillRank", Int, { Int, Object }, &Routines::getSkillRank);
    add("GetAttackTarget", Object, { Object }, &Routines::getAttackTarget);
    add("GetLastAttackType", Int, { Object }, &Routines::getLastAttackType);
    add("GetLastAttackMode", Int, { Object }, &Routines::getLastAttackMode);
    add("GetDistanceBetween2D", Float, { Object, Object }, &Routines::getDistanceBetween2D);
    add("GetIsInCombat", Int, { Object, Int }, &Routines::getIsInCombat);
    add("GetLastAssociateCommand", Int, { Object }, &Routines::getLastAssociateCommand);
    add("GiveGoldToCreature", Void, { Object, Int }, &Routines::giveGoldToCreature);
    add("SetIsDestroyable", Void, { Int, Int, Int }, &Routines::setIsDestroyable);
    add("SetLocked", Void, { Object, Int }, &Routines::setLocked);
    add("GetLocked", Int, { Object }, &Routines::getLocked);
    add("GetClickingObject", Object, { }, &Routines::getClickingObject);
    add("SetAssociateListenPatterns", Void, { Object }, &Routines::setAssociateListenPatterns);
    add("GetLastWeaponUsed", Object, { Object }, &Routines::getLastWeaponUsed);
    add("ActionInteractObject", Void, { Object }, &Routines::actionInteractObject);
    add("GetLastUsedBy", Object, { }, &Routines::getLastUsedBy);
    add("GetAbilityModifier", Int, { Int, Object }, &Routines::getAbilityModifier);
    add("GetIdentified", Int, { Object }, &Routines::getIdentified);
    add("SetIdentified", Void, { Object, Int }, &Routines::setIdentified);
    add("GetDistanceBetweenLocations2D", Float, { Location, Location }, &Routines::getDistanceBetweenLocations2D);
    add("GetDistanceToObject2D", Float, { Object }, &Routines::getDistanceToObject2D);
    add("GetBlockingDoor", Object, { }, &Routines::getBlockingDoor);
    add("GetIsDoorActionPossible", Int, { Object, Int }, &Routines::getIsDoorActionPossible);
    add("DoDoorAction", Void, { Object, Int }, &Routines::doDoorAction);
    add("GetFirstItemInInventory", Object, { Object }, &Routines::getFirstItemInInventory);
    add("GetNextItemInInventory", Object, { Object }, &Routines::getNextItemInInventory);
    add("GetClassByPosition", Int, { Int, Object }, &Routines::getClassByPosition);
    add("GetLevelByPosition", Int, { Int, Object }, &Routines::getLevelByPosition);
    add("GetLevelByClass", Int, { Int, Object }, &Routines::getLevelByClass);
    add("GetDamageDealtByType", Int, { Int }, &Routines::getDamageDealtByType);
    add("GetTotalDamageDealt", Int, { }, &Routines::getTotalDamageDealt);
    add("GetLastDamager", Object, { }, &Routines::getLastDamager);
    add("GetLastDisarmed", Object, { }, &Routines::getLastDisarmed);
    add("GetLastDisturbed", Object, { }, &Routines::getLastDisturbed);
    add("GetLastLocked", Object, { }, &Routines::getLastLocked);
    add("GetLastUnlocked", Object, { }, &Routines::getLastUnlocked);
    add("EffectSkillIncrease", Effect, { Int, Int }, &Routines::effectSkillIncrease);
    add("GetInventoryDisturbType", Int, { }, &Routines::getInventoryDisturbType);
    add("GetInventoryDisturbItem", Object, { }, &Routines::getInventoryDisturbItem);
    add("ShowUpgradeScreen", Void, { Object, Object, Int, Int, String }, &Routines::showUpgradeScreen);
    add("VersusAlignmentEffect", Effect, { Effect, Int, Int }, &Routines::versusAlignmentEffect);
    add("VersusRacialTypeEffect", Effect, { Effect, Int }, &Routines::versusRacialTypeEffect);
    add("VersusTrapEffect", Effect, { Effect }, &Routines::versusTrapEffect);
    add("GetGender", Int, { Object }, &Routines::getGender);
    add("GetIsTalentValid", Int, { Talent }, &Routines::getIsTalentValid);
    add("ActionMoveAwayFromLocation", Void, { Location, Int, Float }, &Routines::actionMoveAwayFromLocation);
    add("GetAttemptedAttackTarget", Object, { }, &Routines::getAttemptedAttackTarget);
    add("GetTypeFromTalent", Int, { Talent }, &Routines::getTypeFromTalent);
    add("GetIdFromTalent", Int, { Talent }, &Routines::getIdFromTalent);
    add("PlayPazaak", Void, { Int, String, Int, Int, Object }, &Routines::playPazaak);
    add("GetLastPazaakResult", Int, { }, &Routines::getLastPazaakResult);
    add("DisplayFeedBackText", Void, { Object, Int }, &Routines::displayFeedBackText);
    add("AddJournalQuestEntry", Void, { String, Int, Int }, &Routines::addJournalQuestEntry);
    add("RemoveJournalQuestEntry", Void, { String }, &Routines::removeJournalQuestEntry);
    add("GetJournalEntry", Int, { String }, &Routines::getJournalEntry);
    add("PlayRumblePattern", Int, { Int }, &Routines::playRumblePattern);
    add("StopRumblePattern", Int, { Int }, &Routines::stopRumblePattern);
    add("EffectDamageForcePoints", Effect, { Int }, &Routines::effectDamageForcePoints);
    add("EffectHealForcePoints", Effect, { Int }, &Routines::effectHealForcePoints);
    add("SendMessageToPC", Void, { Object, String }, &Routines::sendMessageToPC);
    add("GetAttemptedSpellTarget", Object, { }, &Routines::getAttemptedSpellTarget);
    add("GetLastOpenedBy", Object, { }, &Routines::getLastOpenedBy);
    add("GetHasSpell", Int, { Int, Object }, &Routines::getHasSpell);
    add("OpenStore", Void, { Object, Object, Int, Int }, &Routines::openStore);
    add("ActionSurrenderToEnemies", Void, { }, &Routines::actionSurrenderToEnemies);
    add("GetFirstFactionMember", Object, { Object, Int }, &Routines::getFirstFactionMember);
    add("GetNextFactionMember", Object, { Object, Int }, &Routines::getNextFactionMember);
    add("ActionForceMoveToLocation", Void, { Location, Int, Float }, &Routines::actionForceMoveToLocation);
    add("ActionForceMoveToObject", Void, { Object, Int, Float, Float }, &Routines::actionForceMoveToObject);
    add("GetJournalQuestExperience", Int, { String }, &Routines::getJournalQuestExperience);
    add("JumpToObject", Void, { Object, Int }, &Routines::jumpToObject);
    add("SetMapPinEnabled", Void, { Object, Int }, &Routines::setMapPinEnabled);
    add("EffectHitPointChangeWhenDying", Effect, { Float }, &Routines::effectHitPointChangeWhenDying);
    add("PopUpGUIPanel", Void, { Object, Int }, &Routines::popUpGUIPanel);
    add("AddMultiClass", Void, { Int, Object }, &Routines::addMultiClass);
    add("GetIsLinkImmune", Int, { Object, Effect }, &Routines::getIsLinkImmune);
    add("EffectDroidStun", Effect, { }, &Routines::effectDroidStun);
    add("EffectForcePushed", Effect, { }, &Routines::effectForcePushed);
    add("GiveXPToCreature", Void, { Object, Int }, &Routines::giveXPToCreature);
    add("SetXP", Void, { Object, Int }, &Routines::setXP);
    add("GetXP", Int, { Object }, &Routines::getXP);
    add("IntToHexString", String, { Int }, &Routines::intToHexString);
    add("GetBaseItemType", Int, { Object }, &Routines::getBaseItemType);
    add("GetItemHasItemProperty", Int, { Object, Int }, &Routines::getItemHasItemProperty);
    add("ActionEquipMostDamagingMelee", Void, { Object, Int }, &Routines::actionEquipMostDamagingMelee);
    add("ActionEquipMostDamagingRanged", Void, { Object }, &Routines::actionEquipMostDamagingRanged);
    add("GetItemACValue", Int, { Object }, &Routines::getItemACValue);
    add("EffectForceResisted", Effect, { Object }, &Routines::effectForceResisted);
    add("ExploreAreaForPlayer", Void, { Object, Object }, &Routines::exploreAreaForPlayer);
    add("ActionEquipMostEffectiveArmor", Void, { }, &Routines::actionEquipMostEffectiveArmor);
    add("GetIsDay", Int, { }, &Routines::getIsDay);
    add("GetIsNight", Int, { }, &Routines::getIsNight);
    add("GetIsDawn", Int, { }, &Routines::getIsDawn);
    add("GetIsDusk", Int, { }, &Routines::getIsDusk);
    add("GetIsEncounterCreature", Int, { Object }, &Routines::getIsEncounterCreature);
    add("GetLastPlayerDying", Object, { }, &Routines::getLastPlayerDying);
    add("GetStartingLocation", Location, { }, &Routines::getStartingLocation);
    add("ChangeToStandardFaction", Void, { Object, Int }, &Routines::changeToStandardFaction);
    add("SoundObjectPlay", Void, { Object }, &Routines::soundObjectPlay);
    add("SoundObjectStop", Void, { Object }, &Routines::soundObjectStop);
    add("SoundObjectSetVolume", Void, { Object, Int }, &Routines::soundObjectSetVolume);
    add("SoundObjectSetPosition", Void, { Object, TVector }, &Routines::soundObjectSetPosition);
    add("SpeakOneLinerConversation", Void, { String, Object }, &Routines::speakOneLinerConversation);
    add("GetGold", Int, { Object }, &Routines::getGold);
    add("GetLastRespawnButtonPresser", Object, { }, &Routines::getLastRespawnButtonPresser);
    add("EffectForceFizzle", Effect, { }, &Routines::effectForceFizzle);
    add("SetLightsaberPowered", Void, { Object, Int, Int, Int }, &Routines::setLightsaberPowered);
    add("GetIsWeaponEffective", Int, { Object, Int }, &Routines::getIsWeaponEffective);
    add("GetLastSpellHarmful", Int, { }, &Routines::getLastSpellHarmful);
    add("EventActivateItem", Event, { Object, Location, Object }, &Routines::eventActivateItem);
    add("MusicBackgroundPlay", Void, { Object }, &Routines::musicBackgroundPlay);
    add("MusicBackgroundStop", Void, { Object }, &Routines::musicBackgroundStop);
    add("MusicBackgroundSetDelay", Void, { Object, Int }, &Routines::musicBackgroundSetDelay);
    add("MusicBackgroundChangeDay", Void, { Object, Int, Int }, &Routines::musicBackgroundChangeDay);
    add("MusicBackgroundChangeNight", Void, { Object, Int, Int }, &Routines::musicBackgroundChangeNight);
    add("MusicBattlePlay", Void, { Object }, &Routines::musicBattlePlay);
    add("MusicBattleStop", Void, { Object }, &Routines::musicBattleStop);
    add("MusicBattleChange", Void, { Object, Int }, &Routines::musicBattleChange);
    add("AmbientSoundPlay", Void, { Object }, &Routines::ambientSoundPlay);
    add("AmbientSoundStop", Void, { Object }, &Routines::ambientSoundStop);
    add("AmbientSoundChangeDay", Void, { Object, Int }, &Routines::ambientSoundChangeDay);
    add("AmbientSoundChangeNight", Void, { Object, Int }, &Routines::ambientSoundChangeNight);
    add("GetLastKiller", Object, { }, &Routines::getLastKiller);
    add("GetSpellCastItem", Object, { }, &Routines::getSpellCastItem);
    add("GetItemActivated", Object, { }, &Routines::getItemActivated);
    add("GetItemActivator", Object, { }, &Routines::getItemActivator);
    add("GetItemActivatedTargetLocation", Location, { }, &Routines::getItemActivatedTargetLocation);
    add("GetItemActivatedTarget", Object, { }, &Routines::getItemActivatedTarget);
    add("GetIsOpen", Int, { Object }, &Routines::getIsOpen);
    add("TakeGoldFromCreature", Void, { Int, Object, Int }, &Routines::takeGoldFromCreature);
    add("GetIsInConversation", Int, { Object }, &Routines::getIsInConversation);
    add("EffectAbilityDecrease", Effect, { Int, Int }, &Routines::effectAbilityDecrease);
    add("EffectAttackDecrease", Effect, { Int, Int }, &Routines::effectAttackDecrease);
    add("EffectDamageDecrease", Effect, { Int, Int }, &Routines::effectDamageDecrease);
    add("EffectDamageImmunityDecrease", Effect, { Int, Int }, &Routines::effectDamageImmunityDecrease);
    add("EffectACDecrease", Effect, { Int, Int, Int }, &Routines::effectACDecrease);
    add("EffectMovementSpeedDecrease", Effect, { Int }, &Routines::effectMovementSpeedDecrease);
    add("EffectSavingThrowDecrease", Effect, { Int, Int, Int }, &Routines::effectSavingThrowDecrease);
    add("EffectSkillDecrease", Effect, { Int, Int }, &Routines::effectSkillDecrease);
    add("EffectForceResistanceDecrease", Effect, { Int }, &Routines::effectForceResistanceDecrease);
    add("GetPlotFlag", Int, { Object }, &Routines::getPlotFlag);
    add("SetPlotFlag", Void, { Object, Int }, &Routines::setPlotFlag);
    add("EffectInvisibility", Effect, { Int }, &Routines::effectInvisibility);
    add("EffectConcealment", Effect, { Int }, &Routines::effectConcealment);
    add("EffectForceShield", Effect, { Int }, &Routines::effectForceShield);
    add("EffectDispelMagicAll", Effect, { Int }, &Routines::effectDispelMagicAll);
    add("SetDialogPlaceableCamera", Void, { Int }, &Routines::setDialogPlaceableCamera);
    add("GetSoloMode", Int, { }, &Routines::getSoloMode);
    add("EffectDisguise", Effect, { Int }, &Routines::effectDisguise);
    add("GetMaxStealthXP", Int, { }, &Routines::getMaxStealthXP);
    add("EffectTrueSeeing", Effect, { }, &Routines::effectTrueSeeing);
    add("EffectSeeInvisible", Effect, { }, &Routines::effectSeeInvisible);
    add("EffectTimeStop", Effect, { }, &Routines::effectTimeStop);
    add("SetMaxStealthXP", Void, { Int }, &Routines::setMaxStealthXP);
    add("EffectBlasterDeflectionIncrease", Effect, { Int }, &Routines::effectBlasterDeflectionIncrease);
    add("EffectBlasterDeflectionDecrease", Effect, { Int }, &Routines::effectBlasterDeflectionDecrease);
    add("EffectHorrified", Effect, { }, &Routines::effectHorrified);
    add("EffectSpellLevelAbsorption", Effect, { Int, Int, Int }, &Routines::effectSpellLevelAbsorption);
    add("EffectDispelMagicBest", Effect, { Int }, &Routines::effectDispelMagicBest);
    add("GetCurrentStealthXP", Int, { }, &Routines::getCurrentStealthXP);
    add("GetNumStackedItems", Int, { Object }, &Routines::getNumStackedItems);
    add("SurrenderToEnemies", Void, { }, &Routines::surrenderToEnemies);
    add("EffectMissChance", Effect, { Int }, &Routines::effectMissChance);
    add("SetCurrentStealthXP", Void, { Int }, &Routines::setCurrentStealthXP);
    add("GetCreatureSize", Int, { Object }, &Routines::getCreatureSize);
    add("AwardStealthXP", Void, { Object }, &Routines::awardStealthXP);
    add("GetStealthXPEnabled", Int, { }, &Routines::getStealthXPEnabled);
    add("SetStealthXPEnabled", Void, { Int }, &Routines::setStealthXPEnabled);
    add("ActionUnlockObject", Void, { Object }, &Routines::actionUnlockObject);
    add("ActionLockObject", Void, { Object }, &Routines::actionLockObject);
    add("EffectModifyAttacks", Effect, { Int }, &Routines::effectModifyAttacks);
    add("GetLastTrapDetected", Object, { Object }, &Routines::getLastTrapDetected);
    add("EffectDamageShield", Effect, { Int, Int, Int }, &Routines::effectDamageShield);
    add("GetNearestTrapToObject", Object, { Object, Int }, &Routines::getNearestTrapToObject);
    add("GetAttemptedMovementTarget", Object, { }, &Routines::getAttemptedMovementTarget);
    add("GetBlockingCreature", Object, { Object }, &Routines::getBlockingCreature);
    add("GetFortitudeSavingThrow", Int, { Object }, &Routines::getFortitudeSavingThrow);
    add("GetWillSavingThrow", Int, { Object }, &Routines::getWillSavingThrow);
    add("GetReflexSavingThrow", Int, { Object }, &Routines::getReflexSavingThrow);
    add("GetChallengeRating", Float, { Object }, &Routines::getChallengeRating);
    add("GetFoundEnemyCreature", Object, { Object }, &Routines::getFoundEnemyCreature);
    add("GetMovementRate", Int, { Object }, &Routines::getMovementRate);
    add("GetSubRace", Int, { Object }, &Routines::getSubRace);
    add("GetStealthXPDecrement", Int, { }, &Routines::getStealthXPDecrement);
    add("SetStealthXPDecrement", Void, { Int }, &Routines::setStealthXPDecrement);
    add("DuplicateHeadAppearance", Void, { Object, Object }, &Routines::duplicateHeadAppearance);
    add("ActionCastFakeSpellAtObject", Void, { Int, Object, Int }, &Routines::actionCastFakeSpellAtObject);
    add("ActionCastFakeSpellAtLocation", Void, { Int, Location, Int }, &Routines::actionCastFakeSpellAtLocation);
    add("CutsceneAttack", Void, { Object, Int, Int, Int }, &Routines::cutsceneAttack);
    add("SetCameraMode", Void, { Object, Int }, &Routines::setCameraMode);
    add("SetLockOrientationInDialog", Void, { Object, Int }, &Routines::setLockOrientationInDialog);
    add("SetLockHeadFollowInDialog", Void, { Object, Int }, &Routines::setLockHeadFollowInDialog);
    add("CutsceneMove", Void, { Object, TVector, Int }, &Routines::cutsceneMove);
    add("EnableVideoEffect", Void, { Int }, &Routines::enableVideoEffect);
    add("StartNewModule", Void, { String, String, String, String, String, String, String, String }, &Routines::startNewModule);
    add("DisableVideoEffect", Void, { }, &Routines::disableVideoEffect);
    add("GetWeaponRanged", Int, { Object }, &Routines::getWeaponRanged);
    add("DoSinglePlayerAutoSave", Void, { }, &Routines::doSinglePlayerAutoSave);
    add("GetGameDifficulty", Int, { }, &Routines::getGameDifficulty);
    add("GetUserActionsPending", Int, { }, &Routines::getUserActionsPending);
    add("RevealMap", Void, { TVector, Int }, &Routines::revealMap);
    add("SetTutorialWindowsEnabled", Void, { Int }, &Routines::setTutorialWindowsEnabled);
    add("ShowTutorialWindow", Void, { Int }, &Routines::showTutorialWindow);
    add("StartCreditSequence", Void, { Int }, &Routines::startCreditSequence);
    add("IsCreditSequenceInProgress", Int, { }, &Routines::isCreditSequenceInProgress);

    add("SWMG_SetLateralAccelerationPerSecond", Void, { Float });
    add("SWMG_GetLateralAccelerationPerSecond", Float, { });

    add("GetCurrentAction", Int, { Object }, &Routines::getCurrentAction);
    add("GetDifficultyModifier", Float, { }, &Routines::getDifficultyModifier);
    add("GetAppearanceType", Int, { Object }, &Routines::getAppearanceType);
    add("FloatingTextStrRefOnCreature", Void, { Int, Object, Int }, &Routines::floatingTextStrRefOnCreature);
    add("FloatingTextStringOnCreature", Void, { String, Object, Int }, &Routines::floatingTextStringOnCreature);
    add("GetTrapDisarmable", Int, { Object }, &Routines::getTrapDisarmable);
    add("GetTrapDetectable", Int, { Object }, &Routines::getTrapDetectable);
    add("GetTrapDetectedBy", Int, { Object, Object }, &Routines::getTrapDetectedBy);
    add("GetTrapFlagged", Int, { Object }, &Routines::getTrapFlagged);
    add("GetTrapBaseType", Int, { Object }, &Routines::getTrapBaseType);
    add("GetTrapOneShot", Int, { Object }, &Routines::getTrapOneShot);
    add("GetTrapCreator", Object, { Object }, &Routines::getTrapCreator);
    add("GetTrapKeyTag", String, { Object }, &Routines::getTrapKeyTag);
    add("GetTrapDisarmDC", Int, { Object }, &Routines::getTrapDisarmDC);
    add("GetTrapDetectDC", Int, { Object }, &Routines::getTrapDetectDC);
    add("GetLockKeyRequired", Int, { Object }, &Routines::getLockKeyRequired);
    add("GetLockKeyTag", Int, { Object }, &Routines::getLockKeyTag);
    add("GetLockLockable", Int, { Object }, &Routines::getLockLockable);
    add("GetLockUnlockDC", Int, { Object }, &Routines::getLockUnlockDC);
    add("GetLockLockDC", Int, { Object }, &Routines::getLockLockDC);
    add("GetPCLevellingUp", Object, { }, &Routines::getPCLevellingUp);
    add("GetHasFeatEffect", Int, { Int, Object }, &Routines::getHasFeatEffect);
    add("SetPlaceableIllumination", Void, { Object, Int }, &Routines::setPlaceableIllumination);
    add("GetPlaceableIllumination", Int, { Object }, &Routines::getPlaceableIllumination);
    add("GetIsPlaceableObjectActionPossible", Int, { Object, Int }, &Routines::getIsPlaceableObjectActionPossible);
    add("DoPlaceableObjectAction", Void, { Object, Int }, &Routines::doPlaceableObjectAction);
    add("GetFirstPC", Object, { }, &Routines::getFirstPC);
    add("GetNextPC", Object, { }, &Routines::getNextPC);
    add("SetTrapDetectedBy", Int, { Object, Object }, &Routines::setTrapDetectedBy);
    add("GetIsTrapped", Int, { Object }, &Routines::getIsTrapped);
    add("SetEffectIcon", Effect, { Effect, Int }, &Routines::setEffectIcon);
    add("FaceObjectAwayFromObject", Void, { Object, Object }, &Routines::faceObjectAwayFromObject);
    add("PopUpDeathGUIPanel", Void, { Object, Int, Int, Int, String }, &Routines::popUpDeathGUIPanel);
    add("SetTrapDisabled", Void, { Object }, &Routines::setTrapDisabled);
    add("GetLastHostileActor", Object, { Object }, &Routines::getLastHostileActor);
    add("ExportAllCharacters", Void, { }, &Routines::exportAllCharacters);
    add("MusicBackgroundGetDayTrack", Int, { Object }, &Routines::musicBackgroundGetDayTrack);
    add("MusicBackgroundGetNightTrack", Int, { Object }, &Routines::musicBackgroundGetNightTrack);
    add("WriteTimestampedLogEntry", Void, { String }, &Routines::writeTimestampedLogEntry);
    add("GetModuleName", String, { }, &Routines::getModuleName);
    add("GetFactionLeader", Object, { Object }, &Routines::getFactionLeader);

    add("SWMG_SetSpeedBlurEffect", Void, { Int, Float });

    add("EndGame", Void, { Int }, &Routines::endGame);
    add("GetRunScriptVar", Int, { }, &Routines::getRunScriptVar);
    add("GetCreatureMovmentType", Int, { Object }, &Routines::getCreatureMovmentType);
    add("AmbientSoundSetDayVolume", Void, { Object, Int }, &Routines::ambientSoundSetDayVolume);
    add("AmbientSoundSetNightVolume", Void, { Object, Int }, &Routines::ambientSoundSetNightVolume);
    add("MusicBackgroundGetBattleTrack", Int, { Object }, &Routines::musicBackgroundGetBattleTrack);
    add("GetHasInventory", Int, { Object }, &Routines::getHasInventory);
    add("GetStrRefSoundDuration", Float, { Int }, &Routines::getStrRefSoundDuration);
    add("AddToParty", Void, { Object, Object }, &Routines::addToParty);
    add("RemoveFromParty", Void, { Object }, &Routines::removeFromParty);
    add("AddPartyMember", Int, { Int, Object }, &Routines::addPartyMember);
    add("RemovePartyMember", Int, { Int }, &Routines::removePartyMember);
    add("IsObjectPartyMember", Int, { Object }, &Routines::isObjectPartyMember);
    add("GetPartyMemberByIndex", Object, { Int }, &Routines::getPartyMemberByIndex);
    add("GetGlobalBoolean", Int, { String }, &Routines::getGlobalBoolean);
    add("SetGlobalBoolean", Void, { String, Int }, &Routines::setGlobalBoolean);
    add("GetGlobalNumber", Int, { String }, &Routines::getGlobalNumber);
    add("SetGlobalNumber", Void, { String, Int }, &Routines::setGlobalNumber);
    add("AurPostString", Void, { String, Int, Int, Float }, &Routines::aurPostString);

    add("SWMG_GetLastEvent", String, { });
    add("SWMG_GetLastEventModelName", String, { });
    add("SWMG_GetObjectByName", Object, { String });
    add("SWMG_PlayAnimation", Void, { Object, String, Int, Int, Int });
    add("SWMG_GetLastBulletHitDamage", Int, { });
    add("SWMG_GetLastBulletHitTarget", Int, { });
    add("SWMG_GetLastBulletHitShooter", Object, { });
    add("SWMG_AdjustFollowerHitPoints", Int, { Object, Int, Int });
    add("SWMG_OnBulletHit", Void, { });
    add("SWMG_OnObstacleHit", Void, { });
    add("SWMG_GetLastFollowerHit", Object, { });
    add("SWMG_GetLastObstacleHit", Object, { });
    add("SWMG_GetLastBulletFiredDamage", Int, { });
    add("SWMG_GetLastBulletFiredTarget", Int, { });
    add("SWMG_GetObjectName", String, { Object });
    add("SWMG_OnDeath", Void, { });
    add("SWMG_IsFollower", Int, { Object });
    add("SWMG_IsPlayer", Int, { Object });
    add("SWMG_IsEnemy", Int, { Object });
    add("SWMG_IsTrigger", Int, { Object });
    add("SWMG_IsObstacle", Int, { Object });
    add("SWMG_SetFollowerHitPoints", Void, { Object, Int });
    add("SWMG_OnDamage", Void, { });
    add("SWMG_GetLastHPChange", Int, { });
    add("SWMG_RemoveAnimation", Void, { Object, String });
    add("SWMG_GetCameraNearClip", Float, { });
    add("SWMG_GetCameraFarClip", Float, { });
    add("SWMG_SetCameraClip", Void, { Float, Float });
    add("SWMG_GetPlayer", Object, { });
    add("SWMG_GetEnemyCount", Int, { });
    add("SWMG_GetEnemy", Object, { Int });
    add("SWMG_GetObstacleCount", Int, { });
    add("SWMG_GetObstacle", Object, { Int });
    add("SWMG_GetHitPoints", Int, { Object });
    add("SWMG_GetMaxHitPoints", Int, { Object });
    add("SWMG_SetMaxHitPoints", Void, { Object, Int });
    add("SWMG_GetSphereRadius", Float, { Object });
    add("SWMG_SetSphereRadius", Void, { Object, Float });
    add("SWMG_GetNumLoops", Int, { Object });
    add("SWMG_SetNumLoops", Void, { Object, Int });
    add("SWMG_GetPosition", TVector, { Object });
    add("SWMG_GetGunBankCount", Int, { Object });
    add("SWMG_GetGunBankBulletModel", String, { Object, Int });
    add("SWMG_GetGunBankGunModel", String, { Object, Int });
    add("SWMG_GetGunBankDamage", Int, { Object, Int });
    add("SWMG_GetGunBankTimeBetweenShots", Float, { Object, Int });
    add("SWMG_GetGunBankLifespan", Float, { Object, Int });
    add("SWMG_GetGunBankSpeed", Float, { Object, Int });
    add("SWMG_GetGunBankTarget", Int, { Object, Int });
    add("SWMG_SetGunBankBulletModel", Void, { Object, Int, String });
    add("SWMG_SetGunBankGunModel", Void, { Object, Int, String });
    add("SWMG_SetGunBankDamage", Void, { Object, Int, Int });
    add("SWMG_SetGunBankTimeBetweenShots", Void, { Object, Int, Float });
    add("SWMG_SetGunBankLifespan", Void, { Object, Int, Float });
    add("SWMG_SetGunBankSpeed", Void, { Object, Int, Float });
    add("SWMG_SetGunBankTarget", Void, { Object, Int, Int });
    add("SWMG_GetLastBulletHitPart", String, { });
    add("SWMG_IsGunBankTargetting", Int, { Object, Int });
    add("SWMG_GetPlayerOffset", TVector, { });
    add("SWMG_GetPlayerInvincibility", Float, { });
    add("SWMG_GetPlayerSpeed", Float, { });
    add("SWMG_GetPlayerMinSpeed", Float, { });
    add("SWMG_GetPlayerAccelerationPerSecond", Float, { });
    add("SWMG_GetPlayerTunnelPos", TVector, { });
    add("SWMG_SetPlayerOffset", Void, { TVector });
    add("SWMG_SetPlayerInvincibility", Void, { Float });
    add("SWMG_SetPlayerSpeed", Void, { Float });
    add("SWMG_SetPlayerMinSpeed", Void, { Float });
    add("SWMG_SetPlayerAccelerationPerSecond", Void, { Float });
    add("SWMG_SetPlayerTunnelPos", Void, { TVector });
    add("SWMG_GetPlayerTunnelNeg", TVector, { });
    add("SWMG_SetPlayerTunnelNeg", Void, { TVector });
    add("SWMG_GetPlayerOrigin", TVector, { });
    add("SWMG_SetPlayerOrigin", Void, { TVector });
    add("SWMG_GetGunBankHorizontalSpread", Float, { Object, Int });
    add("SWMG_GetGunBankVerticalSpread", Float, { Object, Int });
    add("SWMG_GetGunBankSensingRadius", Float, { Object, Int });
    add("SWMG_GetGunBankInaccuracy", Float, { Object, Int });
    add("SWMG_SetGunBankHorizontalSpread", Void, { Object, Int, Float });
    add("SWMG_SetGunBankVerticalSpread", Void, { Object, Int, Float });
    add("SWMG_SetGunBankSensingRadius", Void, { Object, Int, Float });
    add("SWMG_SetGunBankInaccuracy", Void, { Object, Int, Float });
    add("SWMG_GetIsInvulnerable", Int, { Object });
    add("SWMG_StartInvulnerability", Void, { Object });
    add("SWMG_GetPlayerMaxSpeed", Float, { });
    add("SWMG_SetPlayerMaxSpeed", Void, { Float });

    add("AddJournalWorldEntry", Void, { Int, String, String }, &Routines::addJournalWorldEntry);
    add("AddJournalWorldEntryStrref", Void, { Int, Int }, &Routines::addJournalWorldEntryStrref);
    add("BarkString", Void, { Object, Int, Int, Int }, &Routines::barkString);
    add("DeleteJournalWorldAllEntries", Void, { }, &Routines::deleteJournalWorldAllEntries);
    add("DeleteJournalWorldEntry", Void, { Int }, &Routines::deleteJournalWorldEntry);
    add("DeleteJournalWorldEntryStrref", Void, { Int }, &Routines::deleteJournalWorldEntryStrref);
    add("EffectForceDrain", Effect, { Int }, &Routines::effectForceDrain);
    add("EffectPsychicStatic", Effect, { }, &Routines::effectPsychicStatic);
    add("PlayVisualAreaEffect", Void, { Int, Location }, &Routines::playVisualAreaEffect);
    add("SetJournalQuestEntryPicture", Void, { String, Object, Int, Int, Int }, &Routines::setJournalQuestEntryPicture);
    add("GetLocalBoolean", Int, { Object, Int }, &Routines::getLocalBoolean);
    add("SetLocalBoolean", Void, { Object, Int, Int }, &Routines::setLocalBoolean);
    add("GetLocalNumber", Int, { Object, Int }, &Routines::getLocalNumber);
    add("SetLocalNumber", Void, { Object, Int, Int }, &Routines::setLocalNumber);

    add("SWMG_GetSoundFrequency", Int, { Object, Int });
    add("SWMG_SetSoundFrequency", Void, { Object, Int, Int });
    add("SWMG_GetSoundFrequencyIsRandom", Int, { Object, Int });
    add("SWMG_SetSoundFrequencyIsRandom", Void, { Object, Int, Int });
    add("SWMG_GetSoundVolume", Int, { Object, Int });
    add("SWMG_SetSoundVolume", Void, { Object, Int, Int });

    add("SoundObjectGetPitchVariance", Float, { Object }, &Routines::soundObjectGetPitchVariance);
    add("SoundObjectSetPitchVariance", Void, { Object, Float }, &Routines::soundObjectSetPitchVariance);
    add("SoundObjectGetVolume", Int, { Object }, &Routines::soundObjectGetVolume);
    add("GetGlobalLocation", Location, { String }, &Routines::getGlobalLocation);
    add("SetGlobalLocation", Void, { String, Location }, &Routines::setGlobalLocation);
    add("AddAvailableNPCByObject", Int, { Int, Object }, &Routines::addAvailableNPCByObject);
    add("RemoveAvailableNPC", Int, { Int }, &Routines::removeAvailableNPC);
    add("IsAvailableCreature", Int, { Int }, &Routines::isAvailableCreature);
    add("AddAvailableNPCByTemplate", Int, { Int, String }, &Routines::addAvailableNPCByTemplate);
    add("SpawnAvailableNPC", Object, { Int, Location }, &Routines::spawnAvailableNPC);
    add("IsNPCPartyMember", Int, { Int }, &Routines::isNPCPartyMember);
    add("ActionBarkString", Void, { Int }, &Routines::actionBarkString);
    add("GetIsConversationActive", Int, { }, &Routines::getIsConversationActive);
    add("EffectLightsaberThrow", Effect, { Object, Object, Object, Int }, &Routines::effectLightsaberThrow);
    add("EffectWhirlWind", Effect, { }, &Routines::effectWhirlWind);
    add("GetPartyAIStyle", Int, { }, &Routines::getPartyAIStyle);
    add("GetNPCAIStyle", Int, { Object }, &Routines::getNPCAIStyle);
    add("SetPartyAIStyle", Void, { Int }, &Routines::setPartyAIStyle);
    add("SetNPCAIStyle", Void, { Object, Int }, &Routines::setNPCAIStyle);
    add("SetNPCSelectability", Void, { Int, Int }, &Routines::setNPCSelectability);
    add("GetNPCSelectability", Int, { Int }, &Routines::getNPCSelectability);
    add("ClearAllEffects", Void, { }, &Routines::clearAllEffects);
    add("GetLastConversation", String, { }, &Routines::getLastConversation);
    add("ShowPartySelectionGUI", Void, { String, Int, Int, Int }, &Routines::showPartySelectionGUI);
    add("GetStandardFaction", Int, { Object }, &Routines::getStandardFaction);
    add("GivePlotXP", Void, { String, Int }, &Routines::givePlotXP);
    add("GetMinOneHP", Int, { Object }, &Routines::getMinOneHP);
    add("SetMinOneHP", Void, { Object, Int }, &Routines::setMinOneHP);

    add("SWMG_GetPlayerTunnelInfinite", TVector, { });
    add("SWMG_SetPlayerTunnelInfinite", Void, { TVector });

    add("SetGlobalFadeIn", Void, { Float, Float, Float, Float, Float }, &Routines::setGlobalFadeIn);
    add("SetGlobalFadeOut", Void, { Float, Float, Float, Float, Float }, &Routines::setGlobalFadeOut);
    add("GetLastHostileTarget", Object, { Object }, &Routines::getLastHostileTarget);
    add("GetLastAttackAction", Int, { Object }, &Routines::getLastAttackAction);
    add("GetLastForcePowerUsed", Int, { Object }, &Routines::getLastForcePowerUsed);
    add("GetLastCombatFeatUsed", Int, { Object }, &Routines::getLastCombatFeatUsed);
    add("GetLastAttackResult", Int, { Object }, &Routines::getLastAttackResult);
    add("GetWasForcePowerSuccessful", Int, { Object }, &Routines::getWasForcePowerSuccessful);
    add("GetFirstAttacker", Object, { Object }, &Routines::getFirstAttacker);
    add("GetNextAttacker", Object, { Object }, &Routines::getNextAttacker);
    add("SetFormation", Void, { Object, Object, Int, Int }, &Routines::setFormation);
    add("ActionFollowLeader", Void, { }, &Routines::actionFollowLeader);
    add("SetForcePowerUnsuccessful", Void, { Int, Object }, &Routines::setForcePowerUnsuccessful);
    add("GetIsDebilitated", Int, { Object }, &Routines::getIsDebilitated);
    add("PlayMovie", Void, { String, Int }, &Routines::playMovie);
    add("SaveNPCState", Void, { Int }, &Routines::saveNPCState);
    add("GetCategoryFromTalent", Int, { Talent }, &Routines::getCategoryFromTalent);
    add("SurrenderByFaction", Void, { Int, Int }, &Routines::surrenderByFaction);
    add("ChangeFactionByFaction", Void, { Int, Int }, &Routines::changeFactionByFaction);
    add("PlayRoomAnimation", Void, { String, Int }, &Routines::playRoomAnimation);
    add("ShowGalaxyMap", Void, { Int }, &Routines::showGalaxyMap);
    add("SetPlanetSelectable", Void, { Int, Int }, &Routines::setPlanetSelectable);
    add("GetPlanetSelectable", Int, { Int }, &Routines::getPlanetSelectable);
    add("SetPlanetAvailable", Void, { Int, Int }, &Routines::setPlanetAvailable);
    add("GetPlanetAvailable", Int, { Int }, &Routines::getPlanetAvailable);
    add("GetSelectedPlanet", Int, { }, &Routines::getSelectedPlanet);
    add("SoundObjectFadeAndStop", Void, { Object, Float }, &Routines::soundObjectFadeAndStop);
    add("SetAreaFogColor", Void, { Object, Float, Float, Float }, &Routines::setAreaFogColor);
    add("ChangeItemCost", Void, { String, Float }, &Routines::changeItemCost);
    add("GetIsLiveContentAvailable", Int, { Int }, &Routines::getIsLiveContentAvailable);
    add("ResetDialogState", Void, { }, &Routines::resetDialogState);
    add("SetGoodEvilValue", Void, { Object, Int }, &Routines::setGoodEvilValue);
    add("GetIsPoisoned", Int, { Object }, &Routines::getIsPoisoned);
    add("GetSpellTarget", Object, { Object }, &Routines::getSpellTarget);
    add("SetSoloMode", Void, { Int }, &Routines::setSoloMode);
    add("EffectCutSceneHorrified", Effect, { }, &Routines::effectCutSceneHorrified);
    add("EffectCutSceneParalyze", Effect, { }, &Routines::effectCutSceneParalyze);
    add("EffectCutSceneStunned", Effect, { }, &Routines::effectCutSceneStunned);
    add("CancelPostDialogCharacterSwitch", Void, { }, &Routines::cancelPostDialogCharacterSwitch);
    add("SetMaxHitPoints", Void, { Object, Int }, &Routines::setMaxHitPoints);
    add("NoClicksFor", Void, { Float }, &Routines::noClicksFor);
    add("HoldWorldFadeInForDialog", Void, { }, &Routines::holdWorldFadeInForDialog);
    add("ShipBuild", Int, { }, &Routines::shipBuild);
    add("SurrenderRetainBuffs", Void, { }, &Routines::surrenderRetainBuffs);
    add("SuppressStatusSummaryEntry", Void, { Int }, &Routines::suppressStatusSummaryEntry);
    add("GetCheatCode", Int, { Int }, &Routines::getCheatCode);
    add("SetMusicVolume", Void, { Float }, &Routines::setMusicVolume);
    add("CreateItemOnFloor", Object, { String, Location, Int }, &Routines::createItemOnFloor);
    add("SetAvailableNPCId", Void, { Int, Object }, &Routines::setAvailableNPCId);
    add("GetScriptParameter", Int, { Int }, &Routines::getScriptParameter);
    add("SetFadeUntilScript", Void, { }, &Routines::setFadeUntilScript);
    add("EffectForceBody", Effect, { Int }, &Routines::effectForceBody);
    add("GetItemComponent", Int, { }, &Routines::getItemComponent);
    add("GetItemComponentPieceValue", Int, { }, &Routines::getItemComponentPieceValue);
    add("ShowChemicalUpgradeScreen", Void, { Object }, &Routines::showChemicalUpgradeScreen);
    add("GetChemicals", Int, { }, &Routines::getChemicals);
    add("GetChemicalPieceValue", Int, { }, &Routines::getChemicalPieceValue);
    add("GetSpellForcePointCost", Int, { }, &Routines::getSpellForcePointCost);
    add("EffectFury", Effect, { }, &Routines::effectFury);
    add("EffectBlind", Effect, { }, &Routines::effectBlind);
    add("EffectFPRegenModifier", Effect, { Int }, &Routines::effectFPRegenModifier);
    add("EffectVPRegenModifier", Effect, { Int }, &Routines::effectVPRegenModifier);
    add("EffectCrush", Effect, { }, &Routines::effectCrush);

    add("SWMG_GetSwoopUpgrade", Int, { Int });

    add("GetFeatAcquired", Int, { Int, Object }, &Routines::getFeatAcquired);
    add("GetSpellAcquired", Int, { Int, Object }, &Routines::getSpellAcquired);
    add("ShowSwoopUpgradeScreen", Void, { }, &Routines::showSwoopUpgradeScreen);
    add("GrantFeat", Void, { Int, Object }, &Routines::grantFeat);
    add("GrantSpell", Void, { Int, Object }, &Routines::grantSpell);
    add("SpawnMine", Void, { Int, Location, Int, Int, Object }, &Routines::spawnMine);

    add("SWMG_GetTrackPosition", TVector, { Object });
    add("SWMG_SetFollowerPosition", TVector, { TVector });

    add("SetFakeCombatState", Void, { Object, Int }, &Routines::setFakeCombatState);

    add("SWMG_DestroyMiniGameObject", Void, { Object });

    add("GetOwnerDemolitionsSkill", Int, { Object }, &Routines::getOwnerDemolitionsSkill);
    add("SetOrientOnClick", Void, { Object, Int }, &Routines::setOrientOnClick);
    add("GetInfluence", Int, { Int }, &Routines::getInfluence);
    add("SetInfluence", Void, { Int, Int }, &Routines::setInfluence);
    add("ModifyInfluence", Void, { Int, Int }, &Routines::modifyInfluence);
    add("GetRacialSubType", Int, { Object }, &Routines::getRacialSubType);
    add("IncrementGlobalNumber", Void, { String, Int }, &Routines::incrementGlobalNumber);
    add("DecrementGlobalNumber", Void, { String, Int }, &Routines::decrementGlobalNumber);
    add("SetBonusForcePoints", Void, { Object, Int }, &Routines::setBonusForcePoints);
    add("AddBonusForcePoints", Void, { Object, Int }, &Routines::addBonusForcePoints);
    add("GetBonusForcePoints", Void, { Object }, &Routines::getBonusForcePoints);

    add("SWMG_SetJumpSpeed", Void, { Float });

    add("IsMoviePlaying", Int, { }, &Routines::isMoviePlaying);
    add("QueueMovie", Void, { String, Int }, &Routines::queueMovie);
    add("PlayMovieQueue", Void, { Int }, &Routines::playMovieQueue);
    add("YavinHackDoorClose", Void, { Object }, &Routines::yavinHackCloseDoor);
    add("EffectDroidConfused", Effect, { }, &Routines::effectDroidConfused);
    add("IsStealthed", Int, { Object }, &Routines::isStealthed);
    add("IsMeditating", Int, { Object }, &Routines::isMeditating);
    add("IsInTotalDefense", Int, { Object }, &Routines::isInTotalDefense);
    add("SetHealTarget", Void, { Object, Object }, &Routines::setHealTarget);
    add("GetHealTarget", Object, { Object }, &Routines::getHealTarget);
    add("GetRandomDestination", TVector, { Object, Int }, &Routines::getRandomDestination);
    add("IsFormActive", Int, { Object, Int }, &Routines::isFormActive);
    add("GetSpellFormMask", Int, { Int }, &Routines::getSpellFromMask);
    add("GetSpellBaseForcePointCost", Int, { Int }, &Routines::getSpellBaseForcePointCost);
    add("SetKeepStealthInDialog", Void, { Int }, &Routines::setKeepStealthInDialog);
    add("HasLineOfSight", Int, { TVector, TVector, Object, Object }, &Routines::hasLineOfSight);
    add("ShowDemoScreen", Int, { String, Int, Int, Int, Int }, &Routines::showDemoScreen);
    add("ForceHeartbeat", Void, { Object }, &Routines::forceHeartbeat);
    add("EffectForceSight", Effect, { }, &Routines::effectForceSight);
    add("IsRunning", Int, { Object }, &Routines::isRunning);

    add("SWMG_PlayerApplyForce", Void, { TVector });

    add("SetForfeitConditions", Void, { Int }, &Routines::setForfeitConditions);
    add("GetLastForfeitViolation", Int, { }, &Routines::getLastForfeitViolation);
    add("ModifyReflexSavingThrowBase", Void, { Object, Int }, &Routines::modifyReflexSavingThrowBase);
    add("ModifyFortitudeSavingThrowBase", Void, { Object, Int }, &Routines::modifyFortitudeSavingThrowBase);
    add("ModifyWillSavingThrowBase", Void, { Object, Int }, &Routines::modifyWillSavingThrowBase);
    add("GetScriptStringParameter", String, { }, &Routines::getScriptStringParameter);
    add("GetObjectPersonalSpace", Float, { Object }, &Routines::getObjectPersonalSpace);
    add("AdjustCreatureAttributes", Void, { Object, Int, Int }, &Routines::adjustCreatureAttributes);
    add("SetCreatureAILevel", Void, { Object, Int }, &Routines::setCreatureAILevel);
    add("ResetCreatureAILevel", Void, { Object }, &Routines::resetCreatureAILevel);
    add("AddAvailablePUPByTemplate", Int, { Int, String }, &Routines::addAvailablePUPByTemplate);
    add("AddAvailablePUPByObject", Int, { Int, Object }, &Routines::addAvailablePUPByObject);
    add("AssignPUP", Int, { Int, Int }, &Routines::assignPUP);
    add("SpawnAvailablePUP", Object, { Int, Location }, &Routines::spawnAvailablePUP);
    add("AddPartyPuppet", Int, { Int, Object }, &Routines::addPartyPuppet);
    add("GetPUPOwner", Object, { Object }, &Routines::getPUPOwner);
    add("GetIsPuppet", Int, { Object }, &Routines::getIsPuppet);
    add("ActionFollowOwner", Void, { Float }, &Routines::actionFollowOwner);
    add("GetIsPartyLeader", Int, { Object }, &Routines::getIsPartyLeader);
    add("GetPartyLeader", Object, { }, &Routines::getPartyLeader);
    add("RemoveNPCFromPartyToBase", Int, { Int }, &Routines::removeNPCFromPartyToBase);
    add("CreatureFlourishWeapon", Void, { Object }, &Routines::creatureFlourishWeapon);
    add("EffectMindTrick", Effect, { }, &Routines::effectMindTrick);
    add("EffectFactionModifier", Effect, { Int }, &Routines::effectFactionModifier);
    add("ChangeObjectAppearance", Void, { Object, Int }, &Routines::changeObjectAppearance);
    add("GetIsXBox", Int, { }, &Routines::getIsXBox);
    add("EffectDroidScramble", Effect, { }, &Routines::effectDroidScramble);
    add("ActionSwitchWeapons", Void, { }, &Routines::actionSwitchWeapons);
    add("PlayOverlayAnimation", Void, { Object, Int }, &Routines::playOverlayAnimation);
    add("UnlockAllSongs", Void, { }, &Routines::unlockAllSongs);
    add("DisableMap", Void, { Int }, &Routines::disableMap);
    add("DetonateMine", Void, { Object }, &Routines::detonateMine);
    add("DisableHealthRegen", Void, { Int }, &Routines::disableHealthRegen);
    add("SetCurrentForm", Void, { Object, Int }, &Routines::setCurrentForm);
    add("SetDisableTransit", Void, { Int }, &Routines::setDisableTransit);
    add("SetInputClass", Void, { Int }, &Routines::setInputClass);
    add("SetForceAlwaysUpdate", Void, { Object, Int }, &Routines::setForceAlwaysUpdate);
    add("EnableRain", Void, { Int }, &Routines::enableRain);
    add("DisplayMessageBox", Void, { Int, String }, &Routines::displayMessageBox);
    add("DisplayDatapad", Void, { Object }, &Routines::displayDatapad);
    add("RemoveHeartbeat", Void, { Object }, &Routines::removeHeartbeat);
    add("RemoveEffectByID", Void, { Object, Int }, &Routines::removeEffectByID);
    add("RemoveEffectByExactMatch", Void, { Object, Effect }, &Routines::removeEffectByExactMatch);
    add("AdjustCreatureSkills", Void, { Object, Int, Int }, &Routines::adjustCreatureSkills);
    add("GetSkillRankBase", Int, { Int, Object }, &Routines::getSkillRankBase);
    add("EnableRendering", Void, { Object, Int }, &Routines::enableRendering);
    add("GetCombatActionsPending", Int, { Object }, &Routines::getCombatActionsPending);
    add("SaveNPCByObject", Void, { Int, Object }, &Routines::saveNPCByObject);
    add("SavePUPByObject", Void, { Int, Object }, &Routines::savePUPByObject);
    add("GetIsPlayerMadeCharacter", Int, { Object }, &Routines::getIsPlayerMadeCharacter);
    add("RebuildPartyTable", Void, { }, &Routines::rebuildPartyTable);
}

} // namespace game

} // namespace reone
