/*
 * Copyright ©  Vsevolod Kremianskii
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "routines.h"

using namespace std;
using namespace std::placeholders;

namespace reone {

namespace script {

#define Void VariableType::Void
#define Int VariableType::Int
#define Float VariableType::Float
#define Object VariableType::Object
#define String VariableType::String
#define Effect VariableType::Effect
#define Event VariableType::Event
#define Location VariableType::Location
#define Talent VariableType::Talent
#define Vector VariableType::Vector
#define Action VariableType::Action

void RoutineManager::addKotorRoutines() {
    _routines.emplace_back("Random", Int, vector<VariableType> { Int });
    _routines.emplace_back("PrintString", Void, vector<VariableType> { String });
    _routines.emplace_back("PrintFloat", Void, vector<VariableType> { Float, Int, Int });
    _routines.emplace_back("FloatToString", String, vector<VariableType> { Float, Int, Int });
    _routines.emplace_back("PrintInteger", Void, vector<VariableType> { Int });
    _routines.emplace_back("PrintObject", Void, vector<VariableType> { Object });
    _routines.emplace_back("AssignCommand", Void, vector<VariableType> { Object, Action }, bind(&RoutineManager::assignCommand, this, _1, _2));
    _routines.emplace_back("DelayCommand", Void, vector<VariableType> { Float, Action }, bind(&RoutineManager::delayCommand, this, _1, _2));
    _routines.emplace_back("ExecuteScript", Void, vector<VariableType> { String, Object, Int });
    _routines.emplace_back("ClearAllActions", Void, vector<VariableType>());
    _routines.emplace_back("SetFacing", Void, vector<VariableType> { Float });
    _routines.emplace_back("SwitchPlayerCharacter", Int, vector<VariableType> { Int });
    _routines.emplace_back("SetTime", Void, vector<VariableType> { Int, Int, Int, Int });
    _routines.emplace_back("SetPartyLeader", Int, vector<VariableType> { Int });
    _routines.emplace_back("SetAreaUnescapable", Void, vector<VariableType> { Int });
    _routines.emplace_back("GetAreaUnescapable", Int, vector<VariableType>());
    _routines.emplace_back("GetTimeHour", Int, vector<VariableType>());
    _routines.emplace_back("GetTimeMinute", Int, vector<VariableType>());
    _routines.emplace_back("GetTimeSecond", Int, vector<VariableType>());
    _routines.emplace_back("GetTimeMillisecond", Int, vector<VariableType>());
    _routines.emplace_back("ActionRandomWalk", Void, vector<VariableType>());
    _routines.emplace_back("ActionMoveToLocation", Void, vector<VariableType> { Location, Int });
    _routines.emplace_back("ActionMoveToObject", Void, vector<VariableType> { Object, Int, Float });
    _routines.emplace_back("ActionMoveAwayFromObject", Void, vector<VariableType> { Object, Int, Float });
    _routines.emplace_back("GetArea", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetEnteringObject", Object, vector<VariableType>(), bind(&RoutineManager::getEnteringObject, this, _1, _2));
    _routines.emplace_back("GetExitingObject", Object, vector<VariableType>());
    _routines.emplace_back("GetPosition", Vector, vector<VariableType> { Object });
    _routines.emplace_back("GetFacing", Float, vector<VariableType> { Object });
    _routines.emplace_back("GetItemPossessor", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetItemPossessedBy", Object, vector<VariableType> { Object, String });
    _routines.emplace_back("CreateItemOnObject", Object, vector<VariableType> { String, Object, Int });
    _routines.emplace_back("ActionEquipItem", Void, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("ActionUnequipItem", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("ActionPickUpItem", Void, vector<VariableType> { Object });
    _routines.emplace_back("ActionPutDownItem", Void, vector<VariableType> { Object });
    _routines.emplace_back("GetLastAttacker", Object, vector<VariableType> { Object });
    _routines.emplace_back("ActionAttack", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetNearestCreature", Object, vector<VariableType> { Int, Int, Object, Int, Int, Int, Int, Int  });
    _routines.emplace_back("ActionSpeakString", Void, vector<VariableType> { String, Int });
    _routines.emplace_back("ActionPlayAnimation", Void, vector<VariableType> { Int, Float, Float });
    _routines.emplace_back("GetDistanceToObject", Float, vector<VariableType> { Object });
    _routines.emplace_back("GetIsObjectValid", Int, vector<VariableType> { Object }, bind(&RoutineManager::getIsObjectValid, this, _1, _2));
    _routines.emplace_back("ActionOpenDoor", Void, vector<VariableType> { Object });
    _routines.emplace_back("ActionCloseDoor", Void, vector<VariableType> { Object });
    _routines.emplace_back("SetCameraFacing", Void, vector<VariableType> { Float });
    _routines.emplace_back("PlaySound", Void, vector<VariableType> { String });
    _routines.emplace_back("GetSpellTargetObject", Object, vector<VariableType>());
    _routines.emplace_back("ActionCastSpellAtObject", Void, vector<VariableType> { Int, Object, Int, Int, Int, Int, Int });
    _routines.emplace_back("GetCurrentHitPoints", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetMaxHitPoints", Int, vector<VariableType> { Object });
    _routines.emplace_back("EffectAssuredHit", Effect, vector<VariableType>());
    _routines.emplace_back("GetLastItemEquipped", Object, vector<VariableType>());
    _routines.emplace_back("GetSubScreenID", Int, vector<VariableType>());
    _routines.emplace_back("CancelCombat", Void, vector<VariableType> { Object });
    _routines.emplace_back("GetCurrentForcePoints", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetMaxForcePoints", Int, vector<VariableType> { Object });
    _routines.emplace_back("PauseGame", Void, vector<VariableType> { Int });
    _routines.emplace_back("SetPlayerRestrictMode", Void, vector<VariableType> { Int });
    _routines.emplace_back("GetStringLength", Int, vector<VariableType> { String });
    _routines.emplace_back("GetStringUpperCase", String, vector<VariableType> { String });
    _routines.emplace_back("GetStringLowerCase", String, vector<VariableType> { String });
    _routines.emplace_back("GetStringRight", String, vector<VariableType> { String, Int });
    _routines.emplace_back("GetStringLeft", String, vector<VariableType> { String, Int });
    _routines.emplace_back("InsertString", String, vector<VariableType> { String, String, Int });
    _routines.emplace_back("GetSubString", String, vector<VariableType> { String, Int, Int });
    _routines.emplace_back("FindSubString", Int, vector<VariableType> { String, String });
    _routines.emplace_back("fabs", Float, vector<VariableType> { Float });
    _routines.emplace_back("cos", Float, vector<VariableType> { Float });
    _routines.emplace_back("sin", Float, vector<VariableType> { Float });
    _routines.emplace_back("tan", Float, vector<VariableType> { Float });
    _routines.emplace_back("acos", Float, vector<VariableType> { Float });
    _routines.emplace_back("asin", Float, vector<VariableType> { Float });
    _routines.emplace_back("atan", Float, vector<VariableType> { Float });
    _routines.emplace_back("log", Float, vector<VariableType> { Float });
    _routines.emplace_back("pow", Float, vector<VariableType> { Float, Float });
    _routines.emplace_back("sqrt", Float, vector<VariableType> { Float });
    _routines.emplace_back("abs", Int, vector<VariableType> { Int });
    _routines.emplace_back("EffectHeal", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectDamage", Effect, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("EffectAbilityIncrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("EffectDamageResistance", Effect, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("EffectResurrection", Effect, vector<VariableType>());
    _routines.emplace_back("GetPlayerRestrictMode", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetCasterLevel", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetFirstEffect", Effect, vector<VariableType> { Object });
    _routines.emplace_back("GetNextEffect", Effect, vector<VariableType> { Object });
    _routines.emplace_back("RemoveEffect", Void, vector<VariableType> { Object, Effect });
    _routines.emplace_back("GetIsEffectValid", Int, vector<VariableType> { Effect });
    _routines.emplace_back("GetEffectDurationType", Int, vector<VariableType> { Effect });
    _routines.emplace_back("GetEffectSubType", Int, vector<VariableType> { Effect });
    _routines.emplace_back("GetEffectCreator", Object, vector<VariableType> { Effect });
    _routines.emplace_back("IntToString", String, vector<VariableType> { Int });
    _routines.emplace_back("GetFirstObjectInArea", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetNextObjectInArea", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("d2", Int, vector<VariableType> { Int });
    _routines.emplace_back("d3", Int, vector<VariableType> { Int });
    _routines.emplace_back("d4", Int, vector<VariableType> { Int });
    _routines.emplace_back("d6", Int, vector<VariableType> { Int });
    _routines.emplace_back("d8", Int, vector<VariableType> { Int });
    _routines.emplace_back("d", Int, vector<VariableType> { Int });
    _routines.emplace_back("d12", Int, vector<VariableType> { Int });
    _routines.emplace_back("d", Int, vector<VariableType> { Int });
    _routines.emplace_back("d0", Int, vector<VariableType> { Int });
    _routines.emplace_back("VectorMagnitude", Float, vector<VariableType> { Vector });
    _routines.emplace_back("GetMetaMagicFeat", Int, vector<VariableType>());
    _routines.emplace_back("GetObjectType", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetRacialType", Int, vector<VariableType> { Object });
    _routines.emplace_back("FortitudeSave", Int, vector<VariableType> { Object, Int, Int, Object });
    _routines.emplace_back("ReflexSave", Int, vector<VariableType> { Object, Int, Int, Object });
    _routines.emplace_back("WillSave", Int, vector<VariableType> { Object, Int, Int, Object });
    _routines.emplace_back("GetSpellSaveDC", Int, vector<VariableType>());
    _routines.emplace_back("MagicalEffect", Effect, vector<VariableType> { Effect });
    _routines.emplace_back("SupernaturalEffect", Effect, vector<VariableType> { Effect });
    _routines.emplace_back("ExtraordinaryEffect", Effect, vector<VariableType> { Effect });
    _routines.emplace_back("EffectACIncrease", Effect, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("GetAC", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("EffectSavingThrowIncrease", Effect, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("EffectAttackIncrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("EffectDamageReduction", Effect, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("EffectDamageIncrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("RoundsToSeconds", Float, vector<VariableType> { Int });
    _routines.emplace_back("HoursToSeconds", Float, vector<VariableType> { Int });
    _routines.emplace_back("TurnsToSeconds", Float, vector<VariableType> { Int });
    _routines.emplace_back("SoundObjectSetFixedVariance", Void, vector<VariableType> { Object, Float });
    _routines.emplace_back("GetGoodEvilValue", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetPartyMemberCount", Int, vector<VariableType>());
    _routines.emplace_back("GetAlignmentGoodEvil", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetFirstObjectInShape", Object, vector<VariableType> { Int, Float, Location, Int, Int, Vector });
    _routines.emplace_back("GetNextObjectInShape", Object, vector<VariableType> { Int, Float, Location, Int, Int, Vector });
    _routines.emplace_back("EffectEntangle", Effect, vector<VariableType>());
    _routines.emplace_back("SignalEvent", Void, vector<VariableType> { Object, Event });
    _routines.emplace_back("EventUserDefined", Event, vector<VariableType> { Int });
    _routines.emplace_back("EffectDeath", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("EffectKnockdown", Effect, vector<VariableType>());
    _routines.emplace_back("ActionGiveItem", Void, vector<VariableType> { Object, Object });
    _routines.emplace_back("ActionTakeItem", Void, vector<VariableType> { Object, Object });
    _routines.emplace_back("VectorNormalize", Vector, vector<VariableType> { Vector });
    _routines.emplace_back("GetItemStackSize", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetAbilityScore", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetIsDead", Int, vector<VariableType> { Object });
    _routines.emplace_back("PrintVector", Void, vector<VariableType> { Vector, Int });
    _routines.emplace_back("Vector", Vector, vector<VariableType> { Float, Float, Float });
    _routines.emplace_back("SetFacingPoint", Void, vector<VariableType> { Vector });
    _routines.emplace_back("AngleToVector", Vector, vector<VariableType> { Float });
    _routines.emplace_back("VectorToAngle", Float, vector<VariableType> { Vector });
    _routines.emplace_back("TouchAttackMelee", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("TouchAttackRanged", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("EffectParalyze", Effect, vector<VariableType>());
    _routines.emplace_back("EffectSpellImmunity", Effect, vector<VariableType> { Int });
    _routines.emplace_back("SetItemStackSize", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetDistanceBetween", Float, vector<VariableType> { Object, Object });
    _routines.emplace_back("SetReturnStrref", Void, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("EffectForceJump", Effect, vector<VariableType> { Object, Int });
    _routines.emplace_back("EffectSleep", Effect, vector<VariableType>());
    _routines.emplace_back("GetItemInSlot", Object, vector<VariableType> { Int, Object });
    _routines.emplace_back("EffectTemporaryForcePoints", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectConfused", Effect, vector<VariableType>());
    _routines.emplace_back("EffectFrightened", Effect, vector<VariableType>());
    _routines.emplace_back("EffectChoke", Effect, vector<VariableType> { });
    _routines.emplace_back("SetGlobalString", Void, vector<VariableType> { String, String });
    _routines.emplace_back("EffectStunned", Effect, vector<VariableType>());
    _routines.emplace_back("SetCommandable", Void, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetCommandable", Int, vector<VariableType> { Object });
    _routines.emplace_back("EffectRegenerate", Effect, vector<VariableType> { Int, Float });
    _routines.emplace_back("EffectMovementSpeedIncrease", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetHitDice", Int, vector<VariableType> { Object });
    _routines.emplace_back("ActionForceFollowObject", Void, vector<VariableType> { Object, Float });
    _routines.emplace_back("GetTag", String, vector<VariableType> { Object });
    _routines.emplace_back("ResistForce", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetEffectType", Int, vector<VariableType> { Effect });
    _routines.emplace_back("EffectAreaOfEffect", Effect, vector<VariableType> { Int, String, String, String });
    _routines.emplace_back("GetFactionEqual", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("ChangeFaction", Void, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetIsListening", Int, vector<VariableType> { Object });
    _routines.emplace_back("SetListening", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SetListenPattern", Void, vector<VariableType> { Object, String, Int });
    _routines.emplace_back("TestStringAgainstPattern", Int, vector<VariableType> { String, String });
    _routines.emplace_back("GetMatchedSubstring", String, vector<VariableType> { Int });
    _routines.emplace_back("GetMatchedSubstringsCount", Int, vector<VariableType>());
    _routines.emplace_back("EffectVisualEffect", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("GetFactionWeakestMember", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetFactionStrongestMember", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetFactionMostDamagedMember", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetFactionLeastDamagedMember", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetFactionGold", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetFactionAverageReputation", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetFactionAverageGoodEvilAlignment", Int, vector<VariableType> { Object });
    _routines.emplace_back("SoundObjectGetFixedVariance", Float, vector<VariableType> { Object });
    _routines.emplace_back("GetFactionAverageLevel", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetFactionAverageXP", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetFactionMostFrequentClass", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetFactionWorstAC", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetFactionBestAC", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetGlobalString", String, vector<VariableType> { String });
    _routines.emplace_back("GetListenPatternNumber", Int, vector<VariableType>());
    _routines.emplace_back("ActionJumpToObject", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetWaypointByTag", Object, vector<VariableType> { String });
    _routines.emplace_back("GetTransitionTarget", Object, vector<VariableType> { Object });
    _routines.emplace_back("EffectLinkEffects", Effect, vector<VariableType> { Effect, Effect });
    _routines.emplace_back("GetObjectByTag", Object, vector<VariableType> { String, Int }, bind(&RoutineManager::getObjectByTag, this, _1, _2));
    _routines.emplace_back("AdjustAlignment", Void, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("ActionWait", Void, vector<VariableType> { Float });
    _routines.emplace_back("SetAreaTransitionBMP", Void, vector<VariableType> { Int, String });
    _routines.emplace_back("ActionStartConversation", Void, vector<VariableType> { Object, String, Int, Int, Int, String, String, String, String, String, String, Int }, bind(&RoutineManager::actionStartConversation, this, _1, _2));
    _routines.emplace_back("ActionPauseConversation", Void, vector<VariableType>());
    _routines.emplace_back("ActionResumeConversation", Void, vector<VariableType>());
    _routines.emplace_back("EffectBeam", Effect, vector<VariableType> { Int, Object, Int, Int });
    _routines.emplace_back("GetReputation", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("AdjustReputation", Void, vector<VariableType> { Object, Object, Int });
    _routines.emplace_back("GetModuleFileName", String, vector<VariableType>());
    _routines.emplace_back("GetGoingToBeAttackedBy", Object, vector<VariableType> { Object });
    _routines.emplace_back("EffectForceResistanceIncrease", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetLocation", Location, vector<VariableType> { Object });
    _routines.emplace_back("ActionJumpToLocation", Void, vector<VariableType> { Location });
    _routines.emplace_back("Location", Location, vector<VariableType> { Vector, Float });
    _routines.emplace_back("ApplyEffectAtLocation", Void, vector<VariableType> { Int, Effect, Location, Float });
    _routines.emplace_back("GetIsPC", Int, vector<VariableType> { Object }, bind(&RoutineManager::getIsPC, this, _1, _2));
    _routines.emplace_back("FeetToMeters", Float, vector<VariableType> { Float });
    _routines.emplace_back("YardsToMeters", Float, vector<VariableType> { Float });
    _routines.emplace_back("ApplyEffectToObject", Void, vector<VariableType> { Int, Effect, Object, Float });
    _routines.emplace_back("SpeakString", Void, vector<VariableType> { String, Int });
    _routines.emplace_back("GetSpellTargetLocation", Location, vector<VariableType>());
    _routines.emplace_back("GetPositionFromLocation", Vector, vector<VariableType> { Location });
    _routines.emplace_back("EffectBodyFuel", Effect, vector<VariableType> { });
    _routines.emplace_back("GetFacingFromLocation", Float, vector<VariableType> { Location });
    _routines.emplace_back("GetNearestCreatureToLocation", Object, vector<VariableType> { Int, Int, Location, Int, Int, Int, Int, Int });
    _routines.emplace_back("GetNearestObject", Object, vector<VariableType> { Int, Object, Int });
    _routines.emplace_back("GetNearestObjectToLocation", Object, vector<VariableType> { Int, Location, Int });
    _routines.emplace_back("GetNearestObjectByTag", Object, vector<VariableType> { String, Object, Int });
    _routines.emplace_back("IntToFloat", Float, vector<VariableType> { Int });
    _routines.emplace_back("FloatToInt", Int, vector<VariableType> { Float });
    _routines.emplace_back("StringToInt", Int, vector<VariableType> { String });
    _routines.emplace_back("StringToFloat", Float, vector<VariableType> { String });
    _routines.emplace_back("ActionCastSpellAtLocation", Void, vector<VariableType> { Int, Location, Int, Int, Int, Int });
    _routines.emplace_back("GetIsEnemy", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetIsFriend", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetIsNeutral", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetPCSpeaker", Object, vector<VariableType>());
    _routines.emplace_back("GetStringByStrRef", String, vector<VariableType> { Int });
    _routines.emplace_back("ActionSpeakStringByStrRef", Void, vector<VariableType> { Int, Int });
    _routines.emplace_back("DestroyObject", Void, vector<VariableType> { Object, Float, Int, Float });
    _routines.emplace_back("GetModule", Object, vector<VariableType>());
    _routines.emplace_back("CreateObject", Object, vector<VariableType> { Int, String, Location, Int });
    _routines.emplace_back("EventSpellCastAt", Event, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("GetLastSpellCaster", Object, vector<VariableType>());
    _routines.emplace_back("GetLastSpell", Int, vector<VariableType>());
    _routines.emplace_back("GetUserDefinedEventNumber", Int, vector<VariableType>());
    _routines.emplace_back("GetSpellId", Int, vector<VariableType>());
    _routines.emplace_back("RandomName", String, vector<VariableType>());
    _routines.emplace_back("EffectPoison", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetLoadFromSaveGame", Int, vector<VariableType>());
    _routines.emplace_back("EffectAssuredDeflection", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetName", String, vector<VariableType> { Object });
    _routines.emplace_back("GetLastSpeaker", Object, vector<VariableType>());
    _routines.emplace_back("BeginConversation", Int, vector<VariableType> { String, Object });
    _routines.emplace_back("GetLastPerceived", Object, vector<VariableType>());
    _routines.emplace_back("GetLastPerceptionHeard", Int, vector<VariableType>());
    _routines.emplace_back("GetLastPerceptionInaudible", Int, vector<VariableType>());
    _routines.emplace_back("GetLastPerceptionSeen", Int, vector<VariableType>());
    _routines.emplace_back("GetLastClosedBy", Object, vector<VariableType>());
    _routines.emplace_back("GetLastPerceptionVanished", Int, vector<VariableType>());
    _routines.emplace_back("GetFirstInPersistentObject", Object, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("GetNextInPersistentObject", Object, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("GetAreaOfEffectCreator", Object, vector<VariableType> { Object });
    _routines.emplace_back("ShowLevelUpGUI", Int, vector<VariableType>());
    _routines.emplace_back("SetItemNonEquippable", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetButtonMashCheck", Int, vector<VariableType>());
    _routines.emplace_back("SetButtonMashCheck", Void, vector<VariableType> { Int });
    _routines.emplace_back("EffectForcePushTargeted", Effect, vector<VariableType> { Location, Int });
    _routines.emplace_back("EffectHaste", Effect, vector<VariableType>());
    _routines.emplace_back("GiveItem", Void, vector<VariableType> { Object, Object });
    _routines.emplace_back("ObjectToString", String, vector<VariableType> { Object });
    _routines.emplace_back("EffectImmunity", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetIsImmune", Int, vector<VariableType> { Object, Int, Object });
    _routines.emplace_back("EffectDamageImmunityIncrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("GetEncounterActive", Int, vector<VariableType> { Object });
    _routines.emplace_back("SetEncounterActive", Void, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetEncounterSpawnsMax", Int, vector<VariableType> { Object });
    _routines.emplace_back("SetEncounterSpawnsMax", Void, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetEncounterSpawnsCurrent", Int, vector<VariableType> { Object });
    _routines.emplace_back("SetEncounterSpawnsCurrent", Void, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetModuleItemAcquired", Object, vector<VariableType>());
    _routines.emplace_back("GetModuleItemAcquiredFrom", Object, vector<VariableType>());
    _routines.emplace_back("SetCustomToken", Void, vector<VariableType> { Int, String });
    _routines.emplace_back("GetHasFeat", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetHasSkill", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("ActionUseFeat", Void, vector<VariableType> { Int, Object });
    _routines.emplace_back("ActionUseSkill", Void, vector<VariableType> { Int, Object, Int, Object });
    _routines.emplace_back("GetObjectSeen", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetObjectHeard", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetLastPlayerDied", Object, vector<VariableType>());
    _routines.emplace_back("GetModuleItemLost", Object, vector<VariableType>());
    _routines.emplace_back("GetModuleItemLostBy", Object, vector<VariableType>());
    _routines.emplace_back("ActionDoCommand", Void, vector<VariableType> { Action });
    _routines.emplace_back("EventConversation", Event, vector<VariableType>());
    _routines.emplace_back("SetEncounterDifficulty", Void, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetEncounterDifficulty", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetDistanceBetweenLocations", Float, vector<VariableType> { Location, Location });
    _routines.emplace_back("GetReflexAdjustedDamage", Int, vector<VariableType> { Int, Object, Int, Int, Object });
    _routines.emplace_back("PlayAnimation", Void, vector<VariableType> { Int, Float, Float });
    _routines.emplace_back("TalentSpell", Talent, vector<VariableType> { Int });
    _routines.emplace_back("TalentFeat", Talent, vector<VariableType> { Int });
    _routines.emplace_back("TalentSkill", Talent, vector<VariableType> { Int });
    _routines.emplace_back("GetHasSpellEffect", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetEffectSpellId", Int, vector<VariableType> { Effect });
    _routines.emplace_back("GetCreatureHasTalent", Int, vector<VariableType> { Talent, Object });
    _routines.emplace_back("GetCreatureTalentRandom", Talent, vector<VariableType> { Int, Object, Int });
    _routines.emplace_back("GetCreatureTalentBest", Talent, vector<VariableType> { Int, Int, Object, Int, Int, Int });
    _routines.emplace_back("ActionUseTalentOnObject", Void, vector<VariableType> { Talent, Object });
    _routines.emplace_back("ActionUseTalentAtLocation", Void, vector<VariableType> { Talent, Location });
    _routines.emplace_back("GetGoldPieceValue", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetIsPlayableRacialType", Int, vector<VariableType> { Object });
    _routines.emplace_back("JumpToLocation", Void, vector<VariableType> { Location });
    _routines.emplace_back("EffectTemporaryHitpoints", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetSkillRank", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetAttackTarget", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetLastAttackType", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLastAttackMode", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetDistanceBetween2D", Float, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetIsInCombat", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLastAssociateCommand", Int, vector<VariableType> { Object });
    _routines.emplace_back("GiveGoldToCreature", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SetIsDestroyable", Void, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("SetLocked", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetLocked", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetClickingObject", Object, vector<VariableType>());
    _routines.emplace_back("SetAssociateListenPatterns", Void, vector<VariableType> { Object });
    _routines.emplace_back("GetLastWeaponUsed", Object, vector<VariableType> { Object });
    _routines.emplace_back("ActionInteractObject", Void, vector<VariableType> { Object });
    _routines.emplace_back("GetLastUsedBy", Object, vector<VariableType>());
    _routines.emplace_back("GetAbilityModifier", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetIdentified", Int, vector<VariableType> { Object });
    _routines.emplace_back("SetIdentified", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetDistanceBetweenLocations2D", Float, vector<VariableType> { Location, Location });
    _routines.emplace_back("GetDistanceToObject2D", Float, vector<VariableType> { Object });
    _routines.emplace_back("GetBlockingDoor", Object, vector<VariableType>());
    _routines.emplace_back("GetIsDoorActionPossible", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("DoDoorAction", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetFirstItemInInventory", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetNextItemInInventory", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetClassByPosition", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetLevelByPosition", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetLevelByClass", Int, vector<VariableType> { Int, Object }, bind(&RoutineManager::getLevelByClass, this, _1, _2));
    _routines.emplace_back("GetDamageDealtByType", Int, vector<VariableType> { Int });
    _routines.emplace_back("GetTotalDamageDealt", Int, vector<VariableType>());
    _routines.emplace_back("GetLastDamager", Object, vector<VariableType>());
    _routines.emplace_back("GetLastDisarmed", Object, vector<VariableType>());
    _routines.emplace_back("GetLastDisturbed", Object, vector<VariableType>());
    _routines.emplace_back("GetLastLocked", Object, vector<VariableType>());
    _routines.emplace_back("GetLastUnlocked", Object, vector<VariableType>());
    _routines.emplace_back("EffectSkillIncrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("GetInventoryDisturbType", Int, vector<VariableType>());
    _routines.emplace_back("GetInventoryDisturbItem", Object, vector<VariableType>());
    _routines.emplace_back("ShowUpgradeScreen", Void, vector<VariableType> { Object });
    _routines.emplace_back("VersusAlignmentEffect", Effect, vector<VariableType> { Effect, Int, Int });
    _routines.emplace_back("VersusRacialTypeEffect", Effect, vector<VariableType> { Effect, Int });
    _routines.emplace_back("VersusTrapEffect", Effect, vector<VariableType> { Effect });
    _routines.emplace_back("GetGender", Int, vector<VariableType> { Object }, bind(&RoutineManager::getGender, this, _1, _2));
    _routines.emplace_back("GetIsTalentValid", Int, vector<VariableType> { Talent });
    _routines.emplace_back("ActionMoveAwayFromLocation", Void, vector<VariableType> { Location, Int, Float });
    _routines.emplace_back("GetAttemptedAttackTarget", Object, vector<VariableType>());
    _routines.emplace_back("GetTypeFromTalent", Int, vector<VariableType> { Talent });
    _routines.emplace_back("GetIdFromTalent", Int, vector<VariableType> { Talent });
    _routines.emplace_back("PlayPazaak", Void, vector<VariableType> { Int, String, Int, Int, Object });
    _routines.emplace_back("GetLastPazaakResult", Int, vector<VariableType>());
    _routines.emplace_back("DisplayFeedBackText", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("AddJournalQuestEntry", Void, vector<VariableType> { String, Int, Int });
    _routines.emplace_back("RemoveJournalQuestEntry", Void, vector<VariableType> { String });
    _routines.emplace_back("GetJournalEntry", Int, vector<VariableType> { String });
    _routines.emplace_back("PlayRumblePattern", Int, vector<VariableType> { Int });
    _routines.emplace_back("StopRumblePattern", Int, vector<VariableType> { Int });
    _routines.emplace_back("EffectDamageForcePoints", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectHealForcePoints", Effect, vector<VariableType> { Int });
    _routines.emplace_back("SendMessageToPC", Void, vector<VariableType> { Object, String });
    _routines.emplace_back("GetAttemptedSpellTarget", Object, vector<VariableType>());
    _routines.emplace_back("GetLastOpenedBy", Object, vector<VariableType>());
    _routines.emplace_back("GetHasSpell", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("OpenStore", Void, vector<VariableType> { Object, Object, Int, Int });
    _routines.emplace_back("ActionSurrenderToEnemies", Void, vector<VariableType>());
    _routines.emplace_back("GetFirstFactionMember", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetNextFactionMember", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("ActionForceMoveToLocation", Void, vector<VariableType> { Location, Int, Float });
    _routines.emplace_back("ActionForceMoveToObject", Void, vector<VariableType> { Object, Int, Float, Float });
    _routines.emplace_back("GetJournalQuestExperience", Int, vector<VariableType> { String });
    _routines.emplace_back("JumpToObject", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SetMapPinEnabled", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("EffectHitPointChangeWhenDying", Effect, vector<VariableType> { Float });
    _routines.emplace_back("PopUpGUIPanel", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("AddMultiClass", Void, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetIsLinkImmune", Int, vector<VariableType> { Object, Effect });
    _routines.emplace_back("EffectDroidStun", Effect, vector<VariableType> { });
    _routines.emplace_back("EffectForcePushed", Effect, vector<VariableType>());
    _routines.emplace_back("GiveXPToCreature", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SetXP", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetXP", Int, vector<VariableType> { Object });
    _routines.emplace_back("IntToHexString", String, vector<VariableType> { Int });
    _routines.emplace_back("GetBaseItemType", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetItemHasItemProperty", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("ActionEquipMostDamagingMelee", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("ActionEquipMostDamagingRanged", Void, vector<VariableType> { Object });
    _routines.emplace_back("GetItemACValue", Int, vector<VariableType> { Object });
    _routines.emplace_back("EffectForceResisted", Effect, vector<VariableType> { Object });
    _routines.emplace_back("ExploreAreaForPlayer", Void, vector<VariableType> { Object, Object });
    _routines.emplace_back("ActionEquipMostEffectiveArmor", Void, vector<VariableType>());
    _routines.emplace_back("GetIsDay", Int, vector<VariableType>());
    _routines.emplace_back("GetIsNight", Int, vector<VariableType>());
    _routines.emplace_back("GetIsDawn", Int, vector<VariableType>());
    _routines.emplace_back("GetIsDusk", Int, vector<VariableType>());
    _routines.emplace_back("GetIsEncounterCreature", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLastPlayerDying", Object, vector<VariableType>());
    _routines.emplace_back("GetStartingLocation", Location, vector<VariableType>());
    _routines.emplace_back("ChangeToStandardFaction", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SoundObjectPlay", Void, vector<VariableType> { Object });
    _routines.emplace_back("SoundObjectStop", Void, vector<VariableType> { Object });
    _routines.emplace_back("SoundObjectSetVolume", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SoundObjectSetPosition", Void, vector<VariableType> { Object, Vector });
    _routines.emplace_back("SpeakOneLinerConversation", Void, vector<VariableType> { String, Object });
    _routines.emplace_back("GetGold", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLastRespawnButtonPresser", Object, vector<VariableType>());
    _routines.emplace_back("EffectForceFizzle", Effect, vector<VariableType>());
    _routines.emplace_back("SetLightsaberPowered", Void, vector<VariableType> { Object, Int, Int, Int });
    _routines.emplace_back("GetIsWeaponEffective", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetLastSpellHarmful", Int, vector<VariableType>());
    _routines.emplace_back("EventActivateItem", Event, vector<VariableType> { Object, Location, Object });
    _routines.emplace_back("MusicBackgroundPlay", Void, vector<VariableType> { Object });
    _routines.emplace_back("MusicBackgroundStop", Void, vector<VariableType> { Object });
    _routines.emplace_back("MusicBackgroundSetDelay", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("MusicBackgroundChangeDay", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("MusicBackgroundChangeNight", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("MusicBattlePlay", Void, vector<VariableType> { Object });
    _routines.emplace_back("MusicBattleStop", Void, vector<VariableType> { Object });
    _routines.emplace_back("MusicBattleChange", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("AmbientSoundPlay", Void, vector<VariableType> { Object });
    _routines.emplace_back("AmbientSoundStop", Void, vector<VariableType> { Object });
    _routines.emplace_back("AmbientSoundChangeDay", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("AmbientSoundChangeNight", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetLastKiller", Object, vector<VariableType>());
    _routines.emplace_back("GetSpellCastItem", Object, vector<VariableType>());
    _routines.emplace_back("GetItemActivated", Object, vector<VariableType>());
    _routines.emplace_back("GetItemActivator", Object, vector<VariableType>());
    _routines.emplace_back("GetItemActivatedTargetLocation", Location, vector<VariableType>());
    _routines.emplace_back("GetItemActivatedTarget", Object, vector<VariableType>());
    _routines.emplace_back("GetIsOpen", Int, vector<VariableType> { Object });
    _routines.emplace_back("TakeGoldFromCreature", Void, vector<VariableType> { Int, Object, Int });
    _routines.emplace_back("GetIsInConversation", Int, vector<VariableType> { Object });
    _routines.emplace_back("EffectAbilityDecrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("EffectAttackDecrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("EffectDamageDecrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("EffectDamageImmunityDecrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("EffectACDecrease", Effect, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("EffectMovementSpeedDecrease", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectSavingThrowDecrease", Effect, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("EffectSkillDecrease", Effect, vector<VariableType> { Int, Int });
    _routines.emplace_back("EffectForceResistanceDecrease", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetPlotFlag", Int, vector<VariableType> { Object });
    _routines.emplace_back("SetPlotFlag", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("EffectInvisibility", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectConcealment", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectForceShield", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectDispelMagicAll", Effect, vector<VariableType> { Int });
    _routines.emplace_back("SetDialogPlaceableCamera", Void, vector<VariableType> { Int });
    _routines.emplace_back("GetSoloMode", Int, vector<VariableType>());
    _routines.emplace_back("EffectDisguise", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetMaxStealthXP", Int, vector<VariableType>());
    _routines.emplace_back("EffectTrueSeeing", Effect, vector<VariableType>());
    _routines.emplace_back("EffectSeeInvisible", Effect, vector<VariableType>());
    _routines.emplace_back("EffectTimeStop", Effect, vector<VariableType>());
    _routines.emplace_back("SetMaxStealthXP", Void, vector<VariableType> { Int });
    _routines.emplace_back("EffectBlasterDeflectionIncrease", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectBlasterDeflectionDecrease", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectHorrified", Effect, vector<VariableType> { });
    _routines.emplace_back("EffectSpellLevelAbsorption", Effect, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("EffectDispelMagicBest", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetCurrentStealthXP", Int, vector<VariableType>());
    _routines.emplace_back("GetNumStackedItems", Int, vector<VariableType> { Object });
    _routines.emplace_back("SurrenderToEnemies", Void, vector<VariableType>());
    _routines.emplace_back("EffectMissChance", Effect, vector<VariableType> { Int });
    _routines.emplace_back("SetCurrentStealthXP", Void, vector<VariableType> { Int });
    _routines.emplace_back("GetCreatureSize", Int, vector<VariableType> { Object });
    _routines.emplace_back("AwardStealthXP", Void, vector<VariableType> { Object });
    _routines.emplace_back("GetStealthXPEnabled", Int, vector<VariableType>());
    _routines.emplace_back("SetStealthXPEnabled", Void, vector<VariableType> { Int });
    _routines.emplace_back("ActionUnlockObject", Void, vector<VariableType> { Object });
    _routines.emplace_back("ActionLockObject", Void, vector<VariableType> { Object });
    _routines.emplace_back("EffectModifyAttacks", Effect, vector<VariableType> { Int });
    _routines.emplace_back("GetLastTrapDetected", Object, vector<VariableType> { Object });
    _routines.emplace_back("EffectDamageShield", Effect, vector<VariableType> { Int, Int, Int });
    _routines.emplace_back("GetNearestTrapToObject", Object, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetAttemptedMovementTarget", Object, vector<VariableType>());
    _routines.emplace_back("GetBlockingCreature", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetFortitudeSavingThrow", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetWillSavingThrow", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetReflexSavingThrow", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetChallengeRating", Float, vector<VariableType> { Object });
    _routines.emplace_back("GetFoundEnemyCreature", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetMovementRate", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetSubRace", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetStealthXPDecrement", Int, vector<VariableType>());
    _routines.emplace_back("SetStealthXPDecrement", Void, vector<VariableType> { Int });
    _routines.emplace_back("DuplicateHeadAppearance", Void, vector<VariableType> { Object, Object });
    _routines.emplace_back("ActionCastFakeSpellAtObject", Void, vector<VariableType> { Int, Object, Int });
    _routines.emplace_back("ActionCastFakeSpellAtLocation", Void, vector<VariableType> { Int, Location, Int });
    _routines.emplace_back("CutsceneAttack", Void, vector<VariableType> { Object, Int, Int, Int });
    _routines.emplace_back("SetCameraMode", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SetLockOrientationInDialog", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SetLockHeadFollowInDialog", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("CutsceneMove", Void, vector<VariableType> { Object, Vector, Int });
    _routines.emplace_back("EnableVideoEffect", Void, vector<VariableType> { Int });
    _routines.emplace_back("StartNewModule", Void, vector<VariableType> { String, String, String, String, String, String, String, String });
    _routines.emplace_back("DisableVideoEffect", Void, vector<VariableType>());
    _routines.emplace_back("GetWeaponRanged", Int, vector<VariableType> { Object });
    _routines.emplace_back("DoSinglePlayerAutoSave", Void, vector<VariableType>());
    _routines.emplace_back("GetGameDifficulty", Int, vector<VariableType>());
    _routines.emplace_back("GetUserActionsPending", Int, vector<VariableType>());
    _routines.emplace_back("RevealMap", Void, vector<VariableType> { Vector, Int });
    _routines.emplace_back("SetTutorialWindowsEnabled", Void, vector<VariableType> { Int });
    _routines.emplace_back("ShowTutorialWindow", Void, vector<VariableType> { Int });
    _routines.emplace_back("StartCreditSequence", Void, vector<VariableType> { Int });
    _routines.emplace_back("IsCreditSequenceInProgress", Int, vector<VariableType>());
    _routines.emplace_back("SWMG_SetLateralAccelerationPerSecond", Void, vector<VariableType> { Float });
    _routines.emplace_back("SWMG_GetLateralAccelerationPerSecond", Float, vector<VariableType>());
    _routines.emplace_back("GetCurrentAction", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetDifficultyModifier", Float, vector<VariableType>());
    _routines.emplace_back("GetAppearanceType", Int, vector<VariableType> { Object });
    _routines.emplace_back("FloatingTextStrRefOnCreature", Void, vector<VariableType> { Int, Object, Int });
    _routines.emplace_back("FloatingTextStringOnCreature", Void, vector<VariableType> { String, Object, Int });
    _routines.emplace_back("GetTrapDisarmable", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetTrapDetectable", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetTrapDetectedBy", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetTrapFlagged", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetTrapBaseType", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetTrapOneShot", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetTrapCreator", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetTrapKeyTag", String, vector<VariableType> { Object });
    _routines.emplace_back("GetTrapDisarmDC", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetTrapDetectDC", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLockKeyRequired", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLockKeyTag", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLockLockable", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLockUnlockDC", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLockLockDC", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetPCLevellingUp", Object, vector<VariableType>());
    _routines.emplace_back("GetHasFeatEffect", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("SetPlaceableIllumination", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetPlaceableIllumination", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetIsPlaceableObjectActionPossible", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("DoPlaceableObjectAction", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetFirstPC", Object, vector<VariableType>(), bind(&RoutineManager::getFirstPC, this, _1, _2));
    _routines.emplace_back("GetNextPC", Object, vector<VariableType>(), bind(&RoutineManager::getFirstPC, this, _1, _2));
    _routines.emplace_back("SetTrapDetectedBy", Int, vector<VariableType> { Object, Object });
    _routines.emplace_back("GetIsTrapped", Int, vector<VariableType> { Object });
    _routines.emplace_back("SetEffectIcon", Effect, vector<VariableType> { Effect, Int });
    _routines.emplace_back("FaceObjectAwayFromObject", Void, vector<VariableType> { Object, Object });
    _routines.emplace_back("PopUpDeathGUIPanel", Void, vector<VariableType> { Object, Int, Int, Int, String });
    _routines.emplace_back("SetTrapDisabled", Void, vector<VariableType> { Object });
    _routines.emplace_back("GetLastHostileActor", Object, vector<VariableType> { Object });
    _routines.emplace_back("ExportAllCharacters", Void, vector<VariableType>());
    _routines.emplace_back("MusicBackgroundGetDayTrack", Int, vector<VariableType> { Object });
    _routines.emplace_back("MusicBackgroundGetNightTrack", Int, vector<VariableType> { Object });
    _routines.emplace_back("WriteTimestampedLogEntry", Void, vector<VariableType> { String });
    _routines.emplace_back("GetModuleName", String, vector<VariableType>());
    _routines.emplace_back("GetFactionLeader", Object, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_SetSpeedBlurEffect", Void, vector<VariableType> { Int, Float });
    _routines.emplace_back("EndGame", Void, vector<VariableType> { Int });
    _routines.emplace_back("GetRunScriptVar", Int, vector<VariableType>());
    _routines.emplace_back("GetCreatureMovmentType", Int, vector<VariableType> { Object });
    _routines.emplace_back("AmbientSoundSetDayVolume", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("AmbientSoundSetNightVolume", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("MusicBackgroundGetBattleTrack", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetHasInventory", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetStrRefSoundDuration", Float, vector<VariableType> { Int });
    _routines.emplace_back("AddToParty", Void, vector<VariableType> { Object, Object });
    _routines.emplace_back("RemoveFromParty", Void, vector<VariableType> { Object });
    _routines.emplace_back("AddPartyMember", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("RemovePartyMember", Int, vector<VariableType> { Int });
    _routines.emplace_back("IsObjectPartyMember", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetPartyMemberByIndex", Object, vector<VariableType> { Int });
    _routines.emplace_back("GetGlobalBoolean", Int, vector<VariableType> { String });
    _routines.emplace_back("SetGlobalBoolean", Void, vector<VariableType> { String, Int });
    _routines.emplace_back("GetGlobalNumber", Int, vector<VariableType> { String });
    _routines.emplace_back("SetGlobalNumber", Void, vector<VariableType> { String, Int });
    _routines.emplace_back("AurPostString", Void, vector<VariableType> { String, Int, Int, Float });
    _routines.emplace_back("SWMG_GetLastEvent", String, vector<VariableType>());
    _routines.emplace_back("SWMG_GetLastEventModelName", String, vector<VariableType>());
    _routines.emplace_back("SWMG_GetObjectByName", Object, vector<VariableType> { String });
    _routines.emplace_back("SWMG_PlayAnimation", Void, vector<VariableType> { Object, String, Int, Int, Int });
    _routines.emplace_back("SWMG_GetLastBulletHitDamage", Int, vector<VariableType>());
    _routines.emplace_back("SWMG_GetLastBulletHitTarget", Int, vector<VariableType>());
    _routines.emplace_back("SWMG_GetLastBulletHitShooter", Object, vector<VariableType>());
    _routines.emplace_back("SWMG_AdjustFollowerHitPoints", Int, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("SWMG_OnBulletHit", Void, vector<VariableType>());
    _routines.emplace_back("SWMG_OnObstacleHit", Void, vector<VariableType>());
    _routines.emplace_back("SWMG_GetLastFollowerHit", Object, vector<VariableType>());
    _routines.emplace_back("SWMG_GetLastObstacleHit", Object, vector<VariableType>());
    _routines.emplace_back("SWMG_GetLastBulletFiredDamage", Int, vector<VariableType>());
    _routines.emplace_back("SWMG_GetLastBulletFiredTarget", Int, vector<VariableType>());
    _routines.emplace_back("SWMG_GetObjectName", String, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_OnDeath", Void, vector<VariableType>());
    _routines.emplace_back("SWMG_IsFollower", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_IsPlayer", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_IsEnemy", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_IsTrigger", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_IsObstacle", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_SetFollowerHitPoints", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_OnDamage", Void, vector<VariableType>());
    _routines.emplace_back("SWMG_GetLastHPChange", Int, vector<VariableType>());
    _routines.emplace_back("SWMG_RemoveAnimation", Void, vector<VariableType> { Object, String });
    _routines.emplace_back("SWMG_GetCameraNearClip", Float, vector<VariableType>());
    _routines.emplace_back("SWMG_GetCameraFarClip", Float, vector<VariableType>());
    _routines.emplace_back("SWMG_SetCameraClip", Void, vector<VariableType> { Float, Float });
    _routines.emplace_back("SWMG_GetPlayer", Object, vector<VariableType>());
    _routines.emplace_back("SWMG_GetEnemyCount", Int, vector<VariableType>());
    _routines.emplace_back("SWMG_GetEnemy", Object, vector<VariableType> { Int });
    _routines.emplace_back("SWMG_GetObstacleCount", Int, vector<VariableType>());
    _routines.emplace_back("SWMG_GetObstacle", Object, vector<VariableType> { Int });
    _routines.emplace_back("SWMG_GetHitPoints", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_GetMaxHitPoints", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_SetMaxHitPoints", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetSphereRadius", Float, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_SetSphereRadius", Void, vector<VariableType> { Object, Float });
    _routines.emplace_back("SWMG_GetNumLoops", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_SetNumLoops", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetPosition", Vector, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_GetGunBankCount", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_GetGunBankBulletModel", String, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetGunBankGunModel", String, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetGunBankDamage", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetGunBankTimeBetweenShots", Float, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetGunBankLifespan", Float, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetGunBankSpeed", Float, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetGunBankTarget", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_SetGunBankBulletModel", Void, vector<VariableType> { Object, Int, String });
    _routines.emplace_back("SWMG_SetGunBankGunModel", Void, vector<VariableType> { Object, Int, String });
    _routines.emplace_back("SWMG_SetGunBankDamage", Void, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("SWMG_SetGunBankTimeBetweenShots", Void, vector<VariableType> { Object, Int, Float });
    _routines.emplace_back("SWMG_SetGunBankLifespan", Void, vector<VariableType> { Object, Int, Float });
    _routines.emplace_back("SWMG_SetGunBankSpeed", Void, vector<VariableType> { Object, Int, Float });
    _routines.emplace_back("SWMG_SetGunBankTarget", Void, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("SWMG_GetLastBulletHitPart", String, vector<VariableType>());
    _routines.emplace_back("SWMG_IsGunBankTargetting", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetPlayerOffset", Vector, vector<VariableType>());
    _routines.emplace_back("SWMG_GetPlayerInvincibility", Float, vector<VariableType>());
    _routines.emplace_back("SWMG_GetPlayerSpeed", Float, vector<VariableType>());
    _routines.emplace_back("SWMG_GetPlayerMinSpeed", Float, vector<VariableType>());
    _routines.emplace_back("SWMG_GetPlayerAccelerationPerSecond", Float, vector<VariableType>());
    _routines.emplace_back("SWMG_GetPlayerTunnelPos", Vector, vector<VariableType>());
    _routines.emplace_back("SWMG_SetPlayerOffset", Void, vector<VariableType> { Vector });
    _routines.emplace_back("SWMG_SetPlayerInvincibility", Void, vector<VariableType> { Float });
    _routines.emplace_back("SWMG_SetPlayerSpeed", Void, vector<VariableType> { Float });
    _routines.emplace_back("SWMG_SetPlayerMinSpeed", Void, vector<VariableType> { Float });
    _routines.emplace_back("SWMG_SetPlayerAccelerationPerSecond", Void, vector<VariableType> { Float });
    _routines.emplace_back("SWMG_SetPlayerTunnelPos", Void, vector<VariableType> { Vector });
    _routines.emplace_back("SWMG_GetPlayerTunnelNeg", Vector, vector<VariableType>());
    _routines.emplace_back("SWMG_SetPlayerTunnelNeg", Void, vector<VariableType> { Vector });
    _routines.emplace_back("SWMG_GetPlayerOrigin", Vector, vector<VariableType>());
    _routines.emplace_back("SWMG_SetPlayerOrigin", Void, vector<VariableType> { Vector });
    _routines.emplace_back("SWMG_GetGunBankHorizontalSpread", Float, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetGunBankVerticalSpread", Float, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetGunBankSensingRadius", Float, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetGunBankInaccuracy", Float, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_SetGunBankHorizontalSpread", Void, vector<VariableType> { Object, Int, Float });
    _routines.emplace_back("SWMG_SetGunBankVerticalSpread", Void, vector<VariableType> { Object, Int, Float });
    _routines.emplace_back("SWMG_SetGunBankSensingRadius", Void, vector<VariableType> { Object, Int, Float });
    _routines.emplace_back("SWMG_SetGunBankInaccuracy", Void, vector<VariableType> { Object, Int, Float });
    _routines.emplace_back("SWMG_GetIsInvulnerable", Int, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_StartInvulnerability", Void, vector<VariableType> { Object });
    _routines.emplace_back("SWMG_GetPlayerMaxSpeed", Float, vector<VariableType>());
    _routines.emplace_back("SWMG_SetPlayerMaxSpeed", Void, vector<VariableType> { Float });
    _routines.emplace_back("AddJournalWorldEntry", Void, vector<VariableType> { Int, String, String });
    _routines.emplace_back("AddJournalWorldEntryStrref", Void, vector<VariableType> { Int, Int });
    _routines.emplace_back("BarkString", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("DeleteJournalWorldAllEntries", Void, vector<VariableType>());
    _routines.emplace_back("DeleteJournalWorldEntry", Void, vector<VariableType> { Int });
    _routines.emplace_back("DeleteJournalWorldEntryStrref", Void, vector<VariableType> { Int });
    _routines.emplace_back("EffectForceDrain", Effect, vector<VariableType> { Int });
    _routines.emplace_back("EffectPsychicStatic", Effect, vector<VariableType>());
    _routines.emplace_back("PlayVisualAreaEffect", Void, vector<VariableType> { Int, Location });
    _routines.emplace_back("SetJournalQuestEntryPicture", Void, vector<VariableType> { String, Object, Int, Int, Int });
    _routines.emplace_back("GetLocalBoolean", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("SetLocalBoolean", Void, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("GetLocalNumber", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("SetLocalNumber", Void, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("SWMG_GetSoundFrequency", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_SetSoundFrequency", Void, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("SWMG_GetSoundFrequencyIsRandom", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_SetSoundFrequencyIsRandom", Void, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("SWMG_GetSoundVolume", Int, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_SetSoundVolume", Void, vector<VariableType> { Object, Int, Int });
    _routines.emplace_back("SoundObjectGetPitchVariance", Float, vector<VariableType> { Object });
    _routines.emplace_back("SoundObjectSetPitchVariance", Void, vector<VariableType> { Object, Float });
    _routines.emplace_back("SoundObjectGetVolume", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetGlobalLocation", Location, vector<VariableType> { String });
    _routines.emplace_back("SetGlobalLocation", Void, vector<VariableType> { String, Location });
    _routines.emplace_back("AddAvailableNPCByObject", Int, vector<VariableType> { Int, Object });
    _routines.emplace_back("RemoveAvailableNPC", Int, vector<VariableType> { Int });
    _routines.emplace_back("IsAvailableCreature", Int, vector<VariableType> { Int });
    _routines.emplace_back("AddAvailableNPCByTemplate", Int, vector<VariableType> { Int, String });
    _routines.emplace_back("SpawnAvailableNPC", Object, vector<VariableType> { Int, Location });
    _routines.emplace_back("IsNPCPartyMember", Int, vector<VariableType> { Int });
    _routines.emplace_back("ActionBarkString", Void, vector<VariableType> { Int });
    _routines.emplace_back("GetIsConversationActive", Int, vector<VariableType>());
    _routines.emplace_back("EffectLightsaberThrow", Effect, vector<VariableType> { Object, Object, Object, Int });
    _routines.emplace_back("EffectWhirlWind", Effect, vector<VariableType>());
    _routines.emplace_back("GetPartyAIStyle", Int, vector<VariableType>());
    _routines.emplace_back("GetNPCAIStyle", Int, vector<VariableType> { Object });
    _routines.emplace_back("SetPartyAIStyle", Void, vector<VariableType> { Int });
    _routines.emplace_back("SetNPCAIStyle", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SetNPCSelectability", Void, vector<VariableType> { Int, Int });
    _routines.emplace_back("GetNPCSelectability", Int, vector<VariableType> { Int });
    _routines.emplace_back("ClearAllEffects", Void, vector<VariableType>());
    _routines.emplace_back("GetLastConversation", String, vector<VariableType>());
    _routines.emplace_back("ShowPartySelectionGUI", Void, vector<VariableType> { String, Int, Int });
    _routines.emplace_back("GetStandardFaction", Int, vector<VariableType> { Object });
    _routines.emplace_back("GivePlotXP", Void, vector<VariableType> { String, Int });
    _routines.emplace_back("GetMinOneHP", Int, vector<VariableType> { Object });
    _routines.emplace_back("SetMinOneHP", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("SWMG_GetPlayerTunnelInfinite", Vector, vector<VariableType>());
    _routines.emplace_back("SWMG_SetPlayerTunnelInfinite", Void, vector<VariableType> { Vector });
    _routines.emplace_back("SetGlobalFadeIn", Void, vector<VariableType> { Float, Float, Float, Float, Float });
    _routines.emplace_back("SetGlobalFadeOut", Void, vector<VariableType> { Float, Float, Float, Float, Float });
    _routines.emplace_back("GetLastHostileTarget", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetLastAttackAction", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLastForcePowerUsed", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLastCombatFeatUsed", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetLastAttackResult", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetWasForcePowerSuccessful", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetFirstAttacker", Object, vector<VariableType> { Object });
    _routines.emplace_back("GetNextAttacker", Object, vector<VariableType> { Object });
    _routines.emplace_back("SetFormation", Void, vector<VariableType> { Object, Object, Int, Int });
    _routines.emplace_back("ActionFollowLeader", Void, vector<VariableType>());
    _routines.emplace_back("SetForcePowerUnsuccessful", Void, vector<VariableType> { Int, Object });
    _routines.emplace_back("GetIsDebilitated", Int, vector<VariableType> { Object });
    _routines.emplace_back("PlayMovie", Void, vector<VariableType> { String });
    _routines.emplace_back("SaveNPCState", Void, vector<VariableType> { Int });
    _routines.emplace_back("GetCategoryFromTalent", Int, vector<VariableType> { Talent });
    _routines.emplace_back("SurrenderByFaction", Void, vector<VariableType> { Int, Int });
    _routines.emplace_back("ChangeFactionByFaction", Void, vector<VariableType> { Int, Int });
    _routines.emplace_back("PlayRoomAnimation", Void, vector<VariableType> { String, Int });
    _routines.emplace_back("ShowGalaxyMap", Void, vector<VariableType> { Int });
    _routines.emplace_back("SetPlanetSelectable", Void, vector<VariableType> { Int, Int });
    _routines.emplace_back("GetPlanetSelectable", Int, vector<VariableType> { Int });
    _routines.emplace_back("SetPlanetAvailable", Void, vector<VariableType> { Int, Int });
    _routines.emplace_back("GetPlanetAvailable", Int, vector<VariableType> { Int });
    _routines.emplace_back("GetSelectedPlanet", Int, vector<VariableType>());
    _routines.emplace_back("SoundObjectFadeAndStop", Void, vector<VariableType> { Object, Float });
    _routines.emplace_back("SetAreaFogColor", Void, vector<VariableType> { Object, Float, Float, Float });
    _routines.emplace_back("ChangeItemCost", Void, vector<VariableType> { String, Float });
    _routines.emplace_back("GetIsLiveContentAvailable", Int, vector<VariableType> { Int });
    _routines.emplace_back("ResetDialogState", Void, vector<VariableType>());
    _routines.emplace_back("SetGoodEvilValue", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("GetIsPoisoned", Int, vector<VariableType> { Object });
    _routines.emplace_back("GetSpellTarget", Object, vector<VariableType> { Object });
    _routines.emplace_back("SetSoloMode", Void, vector<VariableType> { Int });
    _routines.emplace_back("EffectCutSceneHorrified", Effect, vector<VariableType>());
    _routines.emplace_back("EffectCutSceneParalyze", Effect, vector<VariableType>());
    _routines.emplace_back("EffectCutSceneStunned", Effect, vector<VariableType>());
    _routines.emplace_back("CancelPostDialogCharacterSwitch", Void, vector<VariableType>());
    _routines.emplace_back("SetMaxHitPoints", Void, vector<VariableType> { Object, Int });
    _routines.emplace_back("NoClicksFor", Void, vector<VariableType> { Float });
    _routines.emplace_back("HoldWorldFadeInForDialog", Void, vector<VariableType>());
    _routines.emplace_back("ShipBuild", Int, vector<VariableType>());
    _routines.emplace_back("SurrenderRetainBuffs", Void, vector<VariableType>());
    _routines.emplace_back("SuppressStatusSummaryEntry", Void, vector<VariableType> { Int });
    _routines.emplace_back("GetCheatCode", Int, vector<VariableType> { Int });
    _routines.emplace_back("SetMusicVolume", Void, vector<VariableType> { Float });
    _routines.emplace_back("CreateItemOnFloor", Object, vector<VariableType> { String, Location, Int });
    _routines.emplace_back("SetAvailableNPCId", Void, vector<VariableType> { Int, Object });
    _routines.emplace_back("IsMoviePlaying", Int, vector<VariableType>());
    _routines.emplace_back("QueueMovie", Void, vector<VariableType> { String, Int });
    _routines.emplace_back("PlayMovieQueue", Void, vector<VariableType> { Int });
    _routines.emplace_back("YavinHackCloseDoor", Void, vector<VariableType> { Object });
}

} // namespace script

} // namespace reone
