/*
 * Copyright (c) 2020-2021 The reone project contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "tsl.h"

#include "../../../../script/types.h"

#include "../../../core/script/routine/impl/declarations.h"
#include "../../../core/script/routine/iroutines.h"

namespace reone {

namespace game {

#define VT_V script::VariableType::Void
#define VT_I script::VariableType::Int
#define VT_F script::VariableType::Float
#define VT_O script::VariableType::Object
#define VT_S script::VariableType::String
#define VT_EFFECT script::VariableType::Effect
#define VT_EVENT script::VariableType::Event
#define VT_LOCATION script::VariableType::Location
#define VT_TALENT script::VariableType::Talent
#define VT_VECTOR script::VariableType::Vector
#define VT_ACTION script::VariableType::Action

void TSLRoutineRegistrar::invoke() {
    _routines.add("Random", VT_I, {VT_I}, &routine::random);
    _routines.add("PrintString", VT_V, {VT_S}, &routine::printString);
    _routines.add("PrintFloat", VT_V, {VT_F, VT_I, VT_I}, &routine::printFloat);
    _routines.add("FloatToString", VT_S, {VT_F, VT_I, VT_I}, &routine::floatToString);
    _routines.add("PrintInteger", VT_V, {VT_I}, &routine::printInteger);
    _routines.add("PrintObject", VT_V, {VT_O}, &routine::printObject);
    _routines.add("AssignCommand", VT_V, {VT_O, VT_ACTION}, &routine::assignCommand);
    _routines.add("DelayCommand", VT_V, {VT_F, VT_ACTION}, &routine::delayCommand);
    _routines.add("ExecuteScript", VT_V, {VT_S, VT_O, VT_I}, &routine::executeScript);
    _routines.add("ClearAllActions", VT_V, {}, &routine::clearAllActions);
    _routines.add("SetFacing", VT_V, {VT_F}, &routine::setFacing);
    _routines.add("SwitchPlayerCharacter", VT_I, {VT_I}, &routine::switchPlayerCharacter);
    _routines.add("SetTime", VT_V, {VT_I, VT_I, VT_I, VT_I}, &routine::setTime);
    _routines.add("SetPartyLeader", VT_I, {VT_I}, &routine::setPartyLeader);
    _routines.add("SetAreaUnescapable", VT_V, {VT_I}, &routine::setAreaUnescapable);
    _routines.add("GetAreaUnescapable", VT_I, {}, &routine::getAreaUnescapable);
    _routines.add("GetTimeHour", VT_I, {}, &routine::getTimeHour);
    _routines.add("GetTimeMinute", VT_I, {}, &routine::getTimeMinute);
    _routines.add("GetTimeSecond", VT_I, {}, &routine::getTimeSecond);
    _routines.add("GetTimeMillisecond", VT_I, {}, &routine::getTimeMillisecond);
    _routines.add("ActionRandomWalk", VT_V, {}, &routine::actionRandomWalk);
    _routines.add("ActionMoveToLocation", VT_V, {VT_LOCATION, VT_I}, &routine::actionMoveToLocation);
    _routines.add("ActionMoveToObject", VT_V, {VT_O, VT_I, VT_F}, &routine::actionMoveToObject);
    _routines.add("ActionMoveAwayFromObject", VT_V, {VT_O, VT_I, VT_F}, &routine::actionMoveAwayFromObject);
    _routines.add("GetArea", VT_O, {VT_O}, &routine::getArea);
    _routines.add("GetEnteringObject", VT_O, {}, &routine::getEnteringObject);
    _routines.add("GetExitingObject", VT_O, {}, &routine::getExitingObject);
    _routines.add("GetPosition", VT_VECTOR, {VT_O}, &routine::getPosition);
    _routines.add("GetFacing", VT_F, {VT_O}, &routine::getFacing);
    _routines.add("GetItemPossessor", VT_O, {VT_O}, &routine::getItemPossessor);
    _routines.add("GetItemPossessedBy", VT_O, {VT_O, VT_S}, &routine::getItemPossessedBy);
    _routines.add("CreateItemOnObject", VT_O, {VT_S, VT_O, VT_I, VT_I}, &routine::createItemOnObject);
    _routines.add("ActionEquipItem", VT_V, {VT_O, VT_I, VT_I}, &routine::actionEquipItem);
    _routines.add("ActionUnequipItem", VT_V, {VT_O, VT_I}, &routine::actionUnequipItem);
    _routines.add("ActionPickUpItem", VT_V, {VT_O}, &routine::actionPickUpItem);
    _routines.add("ActionPutDownItem", VT_V, {VT_O}, &routine::actionPutDownItem);
    _routines.add("GetLastAttacker", VT_O, {VT_O}, &routine::getLastAttacker);
    _routines.add("ActionAttack", VT_V, {VT_O, VT_I}, &routine::actionAttack);
    _routines.add("GetNearestCreature", VT_O, {VT_I, VT_I, VT_O, VT_I, VT_I, VT_I, VT_I, VT_I}, &routine::getNearestCreature);
    _routines.add("ActionSpeakString", VT_V, {VT_S, VT_I}, &routine::actionSpeakString);
    _routines.add("ActionPlayAnimation", VT_V, {VT_I, VT_F, VT_F}, &routine::actionPlayAnimation);
    _routines.add("GetDistanceToObject", VT_F, {VT_O}, &routine::getDistanceToObject);
    _routines.add("GetIsObjectValid", VT_I, {VT_O}, &routine::getIsObjectValid);
    _routines.add("ActionOpenDoor", VT_V, {VT_O}, &routine::actionOpenDoor);
    _routines.add("ActionCloseDoor", VT_V, {VT_O}, &routine::actionCloseDoor);
    _routines.add("SetCameraFacing", VT_V, {VT_F}, &routine::setCameraFacing);
    _routines.add("PlaySound", VT_V, {VT_S}, &routine::playSound);
    _routines.add("GetSpellTargetObject", VT_O, {}, &routine::getSpellTargetObject);
    _routines.add("ActionCastSpellAtObject", VT_V, {VT_I, VT_O, VT_I, VT_I, VT_I, VT_I, VT_I}, &routine::actionCastSpellAtObject);
    _routines.add("GetCurrentHitPoints", VT_I, {VT_O}, &routine::getCurrentHitPoints);
    _routines.add("GetMaxHitPoints", VT_I, {VT_O}, &routine::getMaxHitPoints);
    _routines.add("EffectAssuredHit", VT_EFFECT, {}, &routine::effectAssuredHit);
    _routines.add("GetLastItemEquipped", VT_O, {}, &routine::getLastItemEquipped);
    _routines.add("GetSubScreenID", VT_I, {}, &routine::getSubScreenID);
    _routines.add("CancelCombat", VT_V, {VT_O}, &routine::cancelCombat);
    _routines.add("GetCurrentForcePoints", VT_I, {VT_O}, &routine::getCurrentForcePoints);
    _routines.add("GetMaxForcePoints", VT_I, {VT_O}, &routine::getMaxForcePoints);
    _routines.add("PauseGame", VT_V, {VT_I}, &routine::pauseGame);
    _routines.add("SetPlayerRestrictMode", VT_V, {VT_I}, &routine::setPlayerRestrictMode);
    _routines.add("GetStringLength", VT_I, {VT_S}, &routine::getStringLength);
    _routines.add("GetStringUpperCase", VT_S, {VT_S}, &routine::getStringUpperCase);
    _routines.add("GetStringLowerCase", VT_S, {VT_S}, &routine::getStringLowerCase);
    _routines.add("GetStringRight", VT_S, {VT_S, VT_I}, &routine::getStringRight);
    _routines.add("GetStringLeft", VT_S, {VT_S, VT_I}, &routine::getStringLeft);
    _routines.add("InsertString", VT_S, {VT_S, VT_S, VT_I}, &routine::insertString);
    _routines.add("GetSubString", VT_S, {VT_S, VT_I, VT_I}, &routine::getSubString);
    _routines.add("FindSubString", VT_I, {VT_S, VT_S}, &routine::findSubString);
    _routines.add("fabs", VT_F, {VT_F}, &routine::fabs);
    _routines.add("cos", VT_F, {VT_F}, &routine::cos);
    _routines.add("sin", VT_F, {VT_F}, &routine::sin);
    _routines.add("tan", VT_F, {VT_F}, &routine::tan);
    _routines.add("acos", VT_F, {VT_F}, &routine::acos);
    _routines.add("asin", VT_F, {VT_F}, &routine::asin);
    _routines.add("atan", VT_F, {VT_F}, &routine::atan);
    _routines.add("log", VT_F, {VT_F}, &routine::log);
    _routines.add("pow", VT_F, {VT_F, VT_F}, &routine::pow);
    _routines.add("sqrt", VT_F, {VT_F}, &routine::sqrt);
    _routines.add("abs", VT_I, {VT_I}, &routine::abs);
    _routines.add("EffectHeal", VT_EFFECT, {VT_I}, &routine::effectHeal);
    _routines.add("EffectDamage", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectDamage);
    _routines.add("EffectAbilityIncrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectAbilityIncrease);
    _routines.add("EffectDamageResistance", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectDamageResistance);
    _routines.add("EffectResurrection", VT_EFFECT, {VT_I}, &routine::effectResurrection);
    _routines.add("GetPlayerRestrictMode", VT_I, {VT_O}, &routine::getPlayerRestrictMode);
    _routines.add("GetCasterLevel", VT_I, {VT_O}, &routine::getCasterLevel);
    _routines.add("GetFirstEffect", VT_EFFECT, {VT_O}, &routine::getFirstEffect);
    _routines.add("GetNextEffect", VT_EFFECT, {VT_O}, &routine::getNextEffect);
    _routines.add("RemoveEffect", VT_V, {VT_O, VT_EFFECT}, &routine::removeEffect);
    _routines.add("GetIsEffectValid", VT_I, {VT_EFFECT}, &routine::getIsEffectValid);
    _routines.add("GetEffectDurationType", VT_I, {VT_EFFECT}, &routine::getEffectDurationType);
    _routines.add("GetEffectSubType", VT_I, {VT_EFFECT}, &routine::getEffectSubType);
    _routines.add("GetEffectCreator", VT_O, {VT_EFFECT}, &routine::getEffectCreator);
    _routines.add("IntToString", VT_S, {VT_I}, &routine::intToString);
    _routines.add("GetFirstObjectInArea", VT_O, {VT_O, VT_I}, &routine::getFirstObjectInArea);
    _routines.add("GetNextObjectInArea", VT_O, {VT_O, VT_I}, &routine::getNextObjectInArea);
    _routines.add("d2", VT_I, {VT_I}, &routine::d2);
    _routines.add("d3", VT_I, {VT_I}, &routine::d3);
    _routines.add("d4", VT_I, {VT_I}, &routine::d4);
    _routines.add("d6", VT_I, {VT_I}, &routine::d6);
    _routines.add("d8", VT_I, {VT_I}, &routine::d8);
    _routines.add("d10", VT_I, {VT_I}, &routine::d10);
    _routines.add("d12", VT_I, {VT_I}, &routine::d12);
    _routines.add("d20", VT_I, {VT_I}, &routine::d20);
    _routines.add("d100", VT_I, {VT_I}, &routine::d100);
    _routines.add("VectorMagnitude", VT_F, {VT_VECTOR}, &routine::vectorMagnitude);
    _routines.add("GetMetaMagicFeat", VT_I, {}, &routine::getMetaMagicFeat);
    _routines.add("GetObjectType", VT_I, {VT_O}, &routine::getObjectType);
    _routines.add("GetRacialType", VT_I, {VT_O}, &routine::getRacialType);
    _routines.add("FortitudeSave", VT_I, {VT_O, VT_I, VT_I, VT_O}, &routine::fortitudeSave);
    _routines.add("ReflexSave", VT_I, {VT_O, VT_I, VT_I, VT_O}, &routine::reflexSave);
    _routines.add("WillSave", VT_I, {VT_O, VT_I, VT_I, VT_O}, &routine::willSave);
    _routines.add("GetSpellSaveDC", VT_I, {}, &routine::getSpellSaveDC);
    _routines.add("MagicalEffect", VT_EFFECT, {VT_EFFECT}, &routine::magicalEffect);
    _routines.add("SupernaturalEffect", VT_EFFECT, {VT_EFFECT}, &routine::supernaturalEffect);
    _routines.add("ExtraordinaryEffect", VT_EFFECT, {VT_EFFECT}, &routine::extraordinaryEffect);
    _routines.add("EffectACIncrease", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectACIncrease);
    _routines.add("GetAC", VT_I, {VT_O, VT_I}, &routine::getAC);
    _routines.add("EffectSavingThrowIncrease", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectSavingThrowIncrease);
    _routines.add("EffectAttackIncrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectAttackIncrease);
    _routines.add("EffectDamageReduction", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectDamageReduction);
    _routines.add("EffectDamageIncrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectDamageIncrease);
    _routines.add("RoundsToSeconds", VT_F, {VT_I}, &routine::roundsToSeconds);
    _routines.add("HoursToSeconds", VT_F, {VT_I}, &routine::hoursToSeconds);
    _routines.add("TurnsToSeconds", VT_F, {VT_I}, &routine::turnsToSeconds);
    _routines.add("SoundObjectSetFixedVariance", VT_V, {VT_O, VT_F}, &routine::soundObjectSetFixedVariance);
    _routines.add("GetGoodEvilValue", VT_I, {VT_O}, &routine::getGoodEvilValue);
    _routines.add("GetPartyMemberCount", VT_I, {}, &routine::getPartyMemberCount);
    _routines.add("GetAlignmentGoodEvil", VT_I, {VT_O}, &routine::getAlignmentGoodEvil);
    _routines.add("GetFirstObjectInShape", VT_O, {VT_I, VT_F, VT_LOCATION, VT_I, VT_I, VT_VECTOR}, &routine::getFirstObjectInShape);
    _routines.add("GetNextObjectInShape", VT_O, {VT_I, VT_F, VT_LOCATION, VT_I, VT_I, VT_VECTOR}, &routine::getNextObjectInShape);
    _routines.add("EffectEntangle", VT_EFFECT, {}, &routine::effectEntangle);
    _routines.add("SignalEvent", VT_V, {VT_O, VT_EVENT}, &routine::signalEvent);
    _routines.add("EventUserDefined", VT_EVENT, {VT_I}, &routine::eventUserDefined);
    _routines.add("EffectDeath", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectDeath);
    _routines.add("EffectKnockdown", VT_EFFECT, {}, &routine::effectKnockdown);
    _routines.add("ActionGiveItem", VT_V, {VT_O, VT_O}, &routine::actionGiveItem);
    _routines.add("ActionTakeItem", VT_V, {VT_O, VT_O}, &routine::actionTakeItem);
    _routines.add("VectorNormalize", VT_VECTOR, {VT_VECTOR}, &routine::vectorNormalize);
    _routines.add("GetItemStackSize", VT_I, {VT_O}, &routine::getItemStackSize);
    _routines.add("GetAbilityScore", VT_I, {VT_O, VT_I}, &routine::getAbilityScore);
    _routines.add("GetIsDead", VT_I, {VT_O}, &routine::getIsDead);
    _routines.add("PrintVector", VT_V, {VT_VECTOR, VT_I}, &routine::printVector);
    _routines.add("Vector", VT_VECTOR, {VT_F, VT_F, VT_F}, &routine::vectorCreate);
    _routines.add("SetFacingPoint", VT_V, {VT_VECTOR}, &routine::setFacingPoint);
    _routines.add("AngleToVector", VT_VECTOR, {VT_F}, &routine::angleToVector);
    _routines.add("VectorToAngle", VT_F, {VT_VECTOR}, &routine::vectorToAngle);
    _routines.add("TouchAttackMelee", VT_I, {VT_O, VT_I}, &routine::touchAttackMelee);
    _routines.add("TouchAttackRanged", VT_I, {VT_O, VT_I}, &routine::touchAttackRanged);
    _routines.add("EffectParalyze", VT_EFFECT, {}, &routine::effectParalyze);
    _routines.add("EffectSpellImmunity", VT_EFFECT, {VT_I}, &routine::effectSpellImmunity);
    _routines.add("SetItemStackSize", VT_V, {VT_O, VT_I}, &routine::setItemStackSize);
    _routines.add("GetDistanceBetween", VT_F, {VT_O, VT_O}, &routine::getDistanceBetween);
    _routines.add("SetReturnStrref", VT_V, {VT_I, VT_I, VT_I}, &routine::setReturnStrref);
    _routines.add("EffectForceJump", VT_EFFECT, {VT_O, VT_I}, &routine::effectForceJump);
    _routines.add("EffectSleep", VT_EFFECT, {}, &routine::effectSleep);
    _routines.add("GetItemInSlot", VT_O, {VT_I, VT_O}, &routine::getItemInSlot);
    _routines.add("EffectTemporaryForcePoints", VT_EFFECT, {VT_I}, &routine::effectTemporaryForcePoints);
    _routines.add("EffectConfused", VT_EFFECT, {}, &routine::effectConfused);
    _routines.add("EffectFrightened", VT_EFFECT, {}, &routine::effectFrightened);
    _routines.add("EffectChoke", VT_EFFECT, {}, &routine::effectChoke);
    _routines.add("SetGlobalString", VT_V, {VT_S, VT_S}, &routine::setGlobalString);
    _routines.add("EffectStunned", VT_EFFECT, {}, &routine::effectStunned);
    _routines.add("SetCommandable", VT_V, {VT_I, VT_O}, &routine::setCommandable);
    _routines.add("GetCommandable", VT_I, {VT_O}, &routine::getCommandable);
    _routines.add("EffectRegenerate", VT_EFFECT, {VT_I, VT_F}, &routine::effectRegenerate);
    _routines.add("EffectMovementSpeedIncrease", VT_EFFECT, {VT_I}, &routine::effectMovementSpeedIncrease);
    _routines.add("GetHitDice", VT_I, {VT_O}, &routine::getHitDice);
    _routines.add("ActionForceFollowObject", VT_V, {VT_O, VT_F}, &routine::actionForceFollowObject);
    _routines.add("GetTag", VT_S, {VT_O}, &routine::getTag);
    _routines.add("ResistForce", VT_I, {VT_O, VT_O}, &routine::resistForce);
    _routines.add("GetEffectType", VT_I, {VT_EFFECT}, &routine::getEffectType);
    _routines.add("EffectAreaOfEffect", VT_EFFECT, {VT_I, VT_S, VT_S, VT_S}, &routine::effectAreaOfEffect);
    _routines.add("GetFactionEqual", VT_I, {VT_O, VT_O}, &routine::getFactionEqual);
    _routines.add("ChangeFaction", VT_V, {VT_O, VT_O}, &routine::changeFaction);
    _routines.add("GetIsListening", VT_I, {VT_O}, &routine::getIsListening);
    _routines.add("SetListening", VT_V, {VT_O, VT_I}, &routine::setListening);
    _routines.add("SetListenPattern", VT_V, {VT_O, VT_S, VT_I}, &routine::setListenPattern);
    _routines.add("TestStringAgainstPattern", VT_I, {VT_S, VT_S}, &routine::testStringAgainstPattern);
    _routines.add("GetMatchedSubstring", VT_S, {VT_I}, &routine::getMatchedSubstring);
    _routines.add("GetMatchedSubstringsCount", VT_I, {}, &routine::getMatchedSubstringsCount);
    _routines.add("EffectVisualEffect", VT_EFFECT, {VT_I, VT_I}, &routine::effectVisualEffect);
    _routines.add("GetFactionWeakestMember", VT_O, {VT_O, VT_I}, &routine::getFactionWeakestMember);
    _routines.add("GetFactionStrongestMember", VT_O, {VT_O, VT_I}, &routine::getFactionStrongestMember);
    _routines.add("GetFactionMostDamagedMember", VT_O, {VT_O, VT_I}, &routine::getFactionMostDamagedMember);
    _routines.add("GetFactionLeastDamagedMember", VT_O, {VT_O, VT_I}, &routine::getFactionLeastDamagedMember);
    _routines.add("GetFactionGold", VT_I, {VT_O}, &routine::getFactionGold);
    _routines.add("GetFactionAverageReputation", VT_I, {VT_O, VT_O}, &routine::getFactionAverageReputation);
    _routines.add("GetFactionAverageGoodEvilAlignment", VT_I, {VT_O}, &routine::getFactionAverageGoodEvilAlignment);
    _routines.add("SoundObjectGetFixedVariance", VT_F, {VT_O}, &routine::soundObjectGetFixedVariance);
    _routines.add("GetFactionAverageLevel", VT_I, {VT_O}, &routine::getFactionAverageLevel);
    _routines.add("GetFactionAverageXP", VT_I, {VT_O}, &routine::getFactionAverageXP);
    _routines.add("GetFactionMostFrequentClass", VT_I, {VT_O}, &routine::getFactionMostFrequentClass);
    _routines.add("GetFactionWorstAC", VT_O, {VT_O, VT_I}, &routine::getFactionWorstAC);
    _routines.add("GetFactionBestAC", VT_O, {VT_O, VT_I}, &routine::getFactionBestAC);
    _routines.add("GetGlobalString", VT_S, {VT_S}, &routine::getGlobalString);
    _routines.add("GetListenPatternNumber", VT_I, {}, &routine::getListenPatternNumber);
    _routines.add("ActionJumpToObject", VT_V, {VT_O, VT_I}, &routine::actionJumpToObject);
    _routines.add("GetWaypointByTag", VT_O, {VT_S}, &routine::getWaypointByTag);
    _routines.add("GetTransitionTarget", VT_O, {VT_O}, &routine::getTransitionTarget);
    _routines.add("EffectLinkEffects", VT_EFFECT, {VT_EFFECT, VT_EFFECT}, &routine::effectLinkEffects);
    _routines.add("GetObjectByTag", VT_O, {VT_S, VT_I}, &routine::getObjectByTag);
    _routines.add("AdjustAlignment", VT_V, {VT_O, VT_I, VT_I, VT_I}, &routine::adjustAlignment);
    _routines.add("ActionWait", VT_V, {VT_F}, &routine::actionWait);
    _routines.add("SetAreaTransitionBMP", VT_V, {VT_I, VT_S}, &routine::setAreaTransitionBMP);
    _routines.add("ActionStartConversation", VT_V, {VT_O, VT_S, VT_I, VT_I, VT_I, VT_S, VT_S, VT_S, VT_S, VT_S, VT_S, VT_I, VT_I, VT_I, VT_I}, &routine::actionStartConversation);
    _routines.add("ActionPauseConversation", VT_V, {}, &routine::actionPauseConversation);
    _routines.add("ActionResumeConversation", VT_V, {}, &routine::actionResumeConversation);
    _routines.add("EffectBeam", VT_EFFECT, {VT_I, VT_O, VT_I, VT_I}, &routine::effectBeam);
    _routines.add("GetReputation", VT_I, {VT_O, VT_O}, &routine::getReputation);
    _routines.add("AdjustReputation", VT_V, {VT_O, VT_O, VT_I}, &routine::adjustReputation);
    _routines.add("GetModuleFileName", VT_S, {}, &routine::getModuleFileName);
    _routines.add("GetGoingToBeAttackedBy", VT_O, {VT_O}, &routine::getGoingToBeAttackedBy);
    _routines.add("EffectForceResistanceIncrease", VT_EFFECT, {VT_I}, &routine::effectForceResistanceIncrease);
    _routines.add("GetLocation", VT_LOCATION, {VT_O}, &routine::getLocation);
    _routines.add("ActionJumpToLocation", VT_V, {VT_LOCATION}, &routine::actionJumpToLocation);
    _routines.add("Location", VT_LOCATION, {VT_VECTOR, VT_F}, &routine::location);
    _routines.add("ApplyEffectAtLocation", VT_V, {VT_I, VT_EFFECT, VT_LOCATION, VT_F}, &routine::applyEffectAtLocation);
    _routines.add("GetIsPC", VT_I, {VT_O}, &routine::getIsPC);
    _routines.add("FeetToMeters", VT_F, {VT_F}, &routine::feetToMeters);
    _routines.add("YardsToMeters", VT_F, {VT_F}, &routine::yardsToMeters);
    _routines.add("ApplyEffectToObject", VT_V, {VT_I, VT_EFFECT, VT_O, VT_F}, &routine::applyEffectToObject);
    _routines.add("SpeakString", VT_V, {VT_S, VT_I}, &routine::speakString);
    _routines.add("GetSpellTargetLocation", VT_LOCATION, {}, &routine::getSpellTargetLocation);
    _routines.add("GetPositionFromLocation", VT_VECTOR, {VT_LOCATION}, &routine::getPositionFromLocation);
    _routines.add("EffectBodyFuel", VT_EFFECT, {}, &routine::effectBodyFuel);
    _routines.add("GetFacingFromLocation", VT_F, {VT_LOCATION}, &routine::getFacingFromLocation);
    _routines.add("GetNearestCreatureToLocation", VT_O, {VT_I, VT_I, VT_LOCATION, VT_I, VT_I, VT_I, VT_I, VT_I}, &routine::getNearestCreatureToLocation);
    _routines.add("GetNearestObject", VT_O, {VT_I, VT_O, VT_I}, &routine::getNearestObject);
    _routines.add("GetNearestObjectToLocation", VT_O, {VT_I, VT_LOCATION, VT_I}, &routine::getNearestObjectToLocation);
    _routines.add("GetNearestObjectByTag", VT_O, {VT_S, VT_O, VT_I}, &routine::getNearestObjectByTag);
    _routines.add("IntToFloat", VT_F, {VT_I}, &routine::intToFloat);
    _routines.add("FloatToInt", VT_I, {VT_F}, &routine::floatToInt);
    _routines.add("StringToInt", VT_I, {VT_S}, &routine::stringToInt);
    _routines.add("StringToFloat", VT_F, {VT_S}, &routine::stringToFloat);
    _routines.add("ActionCastSpellAtLocation", VT_V, {VT_I, VT_LOCATION, VT_I, VT_I, VT_I, VT_I}, &routine::actionCastSpellAtLocation);
    _routines.add("GetIsEnemy", VT_I, {VT_O, VT_O}, &routine::getIsEnemy);
    _routines.add("GetIsFriend", VT_I, {VT_O, VT_O}, &routine::getIsFriend);
    _routines.add("GetIsNeutral", VT_I, {VT_O, VT_O}, &routine::getIsNeutral);
    _routines.add("GetPCSpeaker", VT_O, {}, &routine::getPCSpeaker);
    _routines.add("GetStringByStrRef", VT_S, {VT_I}, &routine::getStringByStrRef);
    _routines.add("ActionSpeakStringByStrRef", VT_V, {VT_I, VT_I}, &routine::actionSpeakStringByStrRef);
    _routines.add("DestroyObject", VT_V, {VT_O, VT_F, VT_I, VT_F, VT_I}, &routine::destroyObject);
    _routines.add("GetModule", VT_O, {}, &routine::getModule);
    _routines.add("CreateObject", VT_O, {VT_I, VT_S, VT_LOCATION, VT_I}, &routine::createObject);
    _routines.add("EventSpellCastAt", VT_EVENT, {VT_O, VT_I, VT_I}, &routine::eventSpellCastAt);
    _routines.add("GetLastSpellCaster", VT_O, {}, &routine::getLastSpellCaster);
    _routines.add("GetLastSpell", VT_I, {}, &routine::getLastSpell);
    _routines.add("GetUserDefinedEventNumber", VT_I, {}, &routine::getUserDefinedEventNumber);
    _routines.add("GetSpellId", VT_I, {}, &routine::getSpellId);
    _routines.add("RandomName", VT_S, {}, &routine::randomName);
    _routines.add("EffectPoison", VT_EFFECT, {VT_I}, &routine::effectPoison);
    _routines.add("GetLoadFromSaveGame", VT_I, {}, &routine::getLoadFromSaveGame);
    _routines.add("EffectAssuredDeflection", VT_EFFECT, {VT_I}, &routine::effectAssuredDeflection);
    _routines.add("GetName", VT_S, {VT_O}, &routine::getName);
    _routines.add("GetLastSpeaker", VT_O, {}, &routine::getLastSpeaker);
    _routines.add("BeginConversation", VT_I, {VT_S, VT_O}, &routine::beginConversation);
    _routines.add("GetLastPerceived", VT_O, {}, &routine::getLastPerceived);
    _routines.add("GetLastPerceptionHeard", VT_I, {}, &routine::getLastPerceptionHeard);
    _routines.add("GetLastPerceptionInaudible", VT_I, {}, &routine::getLastPerceptionInaudible);
    _routines.add("GetLastPerceptionSeen", VT_I, {}, &routine::getLastPerceptionSeen);
    _routines.add("GetLastClosedBy", VT_O, {}, &routine::getLastClosedBy);
    _routines.add("GetLastPerceptionVanished", VT_I, {}, &routine::getLastPerceptionVanished);
    _routines.add("GetFirstInPersistentObject", VT_O, {VT_O, VT_I, VT_I}, &routine::getFirstInPersistentObject);
    _routines.add("GetNextInPersistentObject", VT_O, {VT_O, VT_I, VT_I}, &routine::getNextInPersistentObject);
    _routines.add("GetAreaOfEffectCreator", VT_O, {VT_O}, &routine::getAreaOfEffectCreator);
    _routines.add("ShowLevelUpGUI", VT_I, {}, &routine::showLevelUpGUI);
    _routines.add("SetItemNonEquippable", VT_V, {VT_O, VT_I}, &routine::setItemNonEquippable);
    _routines.add("GetButtonMashCheck", VT_I, {}, &routine::getButtonMashCheck);
    _routines.add("SetButtonMashCheck", VT_V, {VT_I}, &routine::setButtonMashCheck);
    _routines.add("EffectForcePushTargeted", VT_EFFECT, {VT_LOCATION, VT_I}, &routine::effectForcePushTargeted);
    _routines.add("EffectHaste", VT_EFFECT, {}, &routine::effectHaste);
    _routines.add("GiveItem", VT_V, {VT_O, VT_O}, &routine::giveItem);
    _routines.add("ObjectToString", VT_S, {VT_O}, &routine::objectToString);
    _routines.add("EffectImmunity", VT_EFFECT, {VT_I}, &routine::effectImmunity);
    _routines.add("GetIsImmune", VT_I, {VT_O, VT_I, VT_O}, &routine::getIsImmune);
    _routines.add("EffectDamageImmunityIncrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectDamageImmunityIncrease);
    _routines.add("GetEncounterActive", VT_I, {VT_O}, &routine::getEncounterActive);
    _routines.add("SetEncounterActive", VT_V, {VT_I, VT_O}, &routine::setEncounterActive);
    _routines.add("GetEncounterSpawnsMax", VT_I, {VT_O}, &routine::getEncounterSpawnsMax);
    _routines.add("SetEncounterSpawnsMax", VT_V, {VT_I, VT_O}, &routine::setEncounterSpawnsMax);
    _routines.add("GetEncounterSpawnsCurrent", VT_I, {VT_O}, &routine::getEncounterSpawnsCurrent);
    _routines.add("SetEncounterSpawnsCurrent", VT_V, {VT_I, VT_O}, &routine::setEncounterSpawnsCurrent);
    _routines.add("GetModuleItemAcquired", VT_O, {}, &routine::getModuleItemAcquired);
    _routines.add("GetModuleItemAcquiredFrom", VT_O, {}, &routine::getModuleItemAcquiredFrom);
    _routines.add("SetCustomToken", VT_V, {VT_I, VT_S}, &routine::setCustomToken);
    _routines.add("GetHasFeat", VT_I, {VT_I, VT_O}, &routine::getHasFeat);
    _routines.add("GetHasSkill", VT_I, {VT_I, VT_O}, &routine::getHasSkill);
    _routines.add("ActionUseFeat", VT_V, {VT_I, VT_O}, &routine::actionUseFeat);
    _routines.add("ActionUseSkill", VT_V, {VT_I, VT_O, VT_I, VT_O}, &routine::actionUseSkill);
    _routines.add("GetObjectSeen", VT_I, {VT_O, VT_O}, &routine::getObjectSeen);
    _routines.add("GetObjectHeard", VT_I, {VT_O, VT_O}, &routine::getObjectHeard);
    _routines.add("GetLastPlayerDied", VT_O, {}, &routine::getLastPlayerDied);
    _routines.add("GetModuleItemLost", VT_O, {}, &routine::getModuleItemLost);
    _routines.add("GetModuleItemLostBy", VT_O, {}, &routine::getModuleItemLostBy);
    _routines.add("ActionDoCommand", VT_V, {VT_ACTION}, &routine::actionDoCommand);
    _routines.add("EventConversation", VT_EVENT, {}, &routine::eventConversation);
    _routines.add("SetEncounterDifficulty", VT_V, {VT_I, VT_O}, &routine::setEncounterDifficulty);
    _routines.add("GetEncounterDifficulty", VT_I, {VT_O}, &routine::getEncounterDifficulty);
    _routines.add("GetDistanceBetweenLocations", VT_F, {VT_LOCATION, VT_LOCATION}, &routine::getDistanceBetweenLocations);
    _routines.add("GetReflexAdjustedDamage", VT_I, {VT_I, VT_O, VT_I, VT_I, VT_O}, &routine::getReflexAdjustedDamage);
    _routines.add("PlayAnimation", VT_V, {VT_I, VT_F, VT_F}, &routine::playAnimation);
    _routines.add("TalentSpell", VT_TALENT, {VT_I}, &routine::talentSpell);
    _routines.add("TalentFeat", VT_TALENT, {VT_I}, &routine::talentFeat);
    _routines.add("TalentSkill", VT_TALENT, {VT_I}, &routine::talentSkill);
    _routines.add("GetHasSpellEffect", VT_I, {VT_I, VT_O}, &routine::getHasSpellEffect);
    _routines.add("GetEffectSpellId", VT_I, {VT_EFFECT}, &routine::getEffectSpellId);
    _routines.add("GetCreatureHasTalent", VT_I, {VT_TALENT, VT_O}, &routine::getCreatureHasTalent);
    _routines.add("GetCreatureTalentRandom", VT_TALENT, {VT_I, VT_O, VT_I}, &routine::getCreatureTalentRandom);
    _routines.add("GetCreatureTalentBest", VT_TALENT, {VT_I, VT_I, VT_O, VT_I, VT_I, VT_I}, &routine::getCreatureTalentBest);
    _routines.add("ActionUseTalentOnObject", VT_V, {VT_TALENT, VT_O}, &routine::actionUseTalentOnObject);
    _routines.add("ActionUseTalentAtLocation", VT_V, {VT_TALENT, VT_LOCATION}, &routine::actionUseTalentAtLocation);
    _routines.add("GetGoldPieceValue", VT_I, {VT_O}, &routine::getGoldPieceValue);
    _routines.add("GetIsPlayableRacialType", VT_I, {VT_O}, &routine::getIsPlayableRacialType);
    _routines.add("JumpToLocation", VT_V, {VT_LOCATION}, &routine::jumpToLocation);
    _routines.add("EffectTemporaryHitpoints", VT_EFFECT, {VT_I}, &routine::effectTemporaryHitpoints);
    _routines.add("GetSkillRank", VT_I, {VT_I, VT_O}, &routine::getSkillRank);
    _routines.add("GetAttackTarget", VT_O, {VT_O}, &routine::getAttackTarget);
    _routines.add("GetLastAttackType", VT_I, {VT_O}, &routine::getLastAttackType);
    _routines.add("GetLastAttackMode", VT_I, {VT_O}, &routine::getLastAttackMode);
    _routines.add("GetDistanceBetween2D", VT_F, {VT_O, VT_O}, &routine::getDistanceBetween2D);
    _routines.add("GetIsInCombat", VT_I, {VT_O, VT_I}, &routine::getIsInCombat);
    _routines.add("GetLastAssociateCommand", VT_I, {VT_O}, &routine::getLastAssociateCommand);
    _routines.add("GiveGoldToCreature", VT_V, {VT_O, VT_I}, &routine::giveGoldToCreature);
    _routines.add("SetIsDestroyable", VT_V, {VT_I, VT_I, VT_I}, &routine::setIsDestroyable);
    _routines.add("SetLocked", VT_V, {VT_O, VT_I}, &routine::setLocked);
    _routines.add("GetLocked", VT_I, {VT_O}, &routine::getLocked);
    _routines.add("GetClickingObject", VT_O, {}, &routine::getClickingObject);
    _routines.add("SetAssociateListenPatterns", VT_V, {VT_O}, &routine::setAssociateListenPatterns);
    _routines.add("GetLastWeaponUsed", VT_O, {VT_O}, &routine::getLastWeaponUsed);
    _routines.add("ActionInteractObject", VT_V, {VT_O}, &routine::actionInteractObject);
    _routines.add("GetLastUsedBy", VT_O, {}, &routine::getLastUsedBy);
    _routines.add("GetAbilityModifier", VT_I, {VT_I, VT_O}, &routine::getAbilityModifier);
    _routines.add("GetIdentified", VT_I, {VT_O}, &routine::getIdentified);
    _routines.add("SetIdentified", VT_V, {VT_O, VT_I}, &routine::setIdentified);
    _routines.add("GetDistanceBetweenLocations2D", VT_F, {VT_LOCATION, VT_LOCATION}, &routine::getDistanceBetweenLocations2D);
    _routines.add("GetDistanceToObject2D", VT_F, {VT_O}, &routine::getDistanceToObject2D);
    _routines.add("GetBlockingDoor", VT_O, {}, &routine::getBlockingDoor);
    _routines.add("GetIsDoorActionPossible", VT_I, {VT_O, VT_I}, &routine::getIsDoorActionPossible);
    _routines.add("DoDoorAction", VT_V, {VT_O, VT_I}, &routine::doDoorAction);
    _routines.add("GetFirstItemInInventory", VT_O, {VT_O}, &routine::getFirstItemInInventory);
    _routines.add("GetNextItemInInventory", VT_O, {VT_O}, &routine::getNextItemInInventory);
    _routines.add("GetClassByPosition", VT_I, {VT_I, VT_O}, &routine::getClassByPosition);
    _routines.add("GetLevelByPosition", VT_I, {VT_I, VT_O}, &routine::getLevelByPosition);
    _routines.add("GetLevelByClass", VT_I, {VT_I, VT_O}, &routine::getLevelByClass);
    _routines.add("GetDamageDealtByType", VT_I, {VT_I}, &routine::getDamageDealtByType);
    _routines.add("GetTotalDamageDealt", VT_I, {}, &routine::getTotalDamageDealt);
    _routines.add("GetLastDamager", VT_O, {}, &routine::getLastDamager);
    _routines.add("GetLastDisarmed", VT_O, {}, &routine::getLastDisarmed);
    _routines.add("GetLastDisturbed", VT_O, {}, &routine::getLastDisturbed);
    _routines.add("GetLastLocked", VT_O, {}, &routine::getLastLocked);
    _routines.add("GetLastUnlocked", VT_O, {}, &routine::getLastUnlocked);
    _routines.add("EffectSkillIncrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectSkillIncrease);
    _routines.add("GetInventoryDisturbType", VT_I, {}, &routine::getInventoryDisturbType);
    _routines.add("GetInventoryDisturbItem", VT_O, {}, &routine::getInventoryDisturbItem);
    _routines.add("ShowUpgradeScreen", VT_V, {VT_O, VT_O, VT_I, VT_I, VT_S}, &routine::showUpgradeScreen);
    _routines.add("VersusAlignmentEffect", VT_EFFECT, {VT_EFFECT, VT_I, VT_I}, &routine::versusAlignmentEffect);
    _routines.add("VersusRacialTypeEffect", VT_EFFECT, {VT_EFFECT, VT_I}, &routine::versusRacialTypeEffect);
    _routines.add("VersusTrapEffect", VT_EFFECT, {VT_EFFECT}, &routine::versusTrapEffect);
    _routines.add("GetGender", VT_I, {VT_O}, &routine::getGender);
    _routines.add("GetIsTalentValid", VT_I, {VT_TALENT}, &routine::getIsTalentValid);
    _routines.add("ActionMoveAwayFromLocation", VT_V, {VT_LOCATION, VT_I, VT_F}, &routine::actionMoveAwayFromLocation);
    _routines.add("GetAttemptedAttackTarget", VT_O, {}, &routine::getAttemptedAttackTarget);
    _routines.add("GetTypeFromTalent", VT_I, {VT_TALENT}, &routine::getTypeFromTalent);
    _routines.add("GetIdFromTalent", VT_I, {VT_TALENT}, &routine::getIdFromTalent);
    _routines.add("PlayPazaak", VT_V, {VT_I, VT_S, VT_I, VT_I, VT_O}, &routine::playPazaak);
    _routines.add("GetLastPazaakResult", VT_I, {}, &routine::getLastPazaakResult);
    _routines.add("DisplayFeedBackText", VT_V, {VT_O, VT_I}, &routine::displayFeedBackText);
    _routines.add("AddJournalQuestEntry", VT_V, {VT_S, VT_I, VT_I}, &routine::addJournalQuestEntry);
    _routines.add("RemoveJournalQuestEntry", VT_V, {VT_S}, &routine::removeJournalQuestEntry);
    _routines.add("GetJournalEntry", VT_I, {VT_S}, &routine::getJournalEntry);
    _routines.add("PlayRumblePattern", VT_I, {VT_I}, &routine::playRumblePattern);
    _routines.add("StopRumblePattern", VT_I, {VT_I}, &routine::stopRumblePattern);
    _routines.add("EffectDamageForcePoints", VT_EFFECT, {VT_I}, &routine::effectDamageForcePoints);
    _routines.add("EffectHealForcePoints", VT_EFFECT, {VT_I}, &routine::effectHealForcePoints);
    _routines.add("SendMessageToPC", VT_V, {VT_O, VT_S}, &routine::sendMessageToPC);
    _routines.add("GetAttemptedSpellTarget", VT_O, {}, &routine::getAttemptedSpellTarget);
    _routines.add("GetLastOpenedBy", VT_O, {}, &routine::getLastOpenedBy);
    _routines.add("GetHasSpell", VT_I, {VT_I, VT_O}, &routine::getHasSpell);
    _routines.add("OpenStore", VT_V, {VT_O, VT_O, VT_I, VT_I}, &routine::openStore);
    _routines.add("ActionSurrenderToEnemies", VT_V, {}, &routine::actionSurrenderToEnemies);
    _routines.add("GetFirstFactionMember", VT_O, {VT_O, VT_I}, &routine::getFirstFactionMember);
    _routines.add("GetNextFactionMember", VT_O, {VT_O, VT_I}, &routine::getNextFactionMember);
    _routines.add("ActionForceMoveToLocation", VT_V, {VT_LOCATION, VT_I, VT_F}, &routine::actionForceMoveToLocation);
    _routines.add("ActionForceMoveToObject", VT_V, {VT_O, VT_I, VT_F, VT_F}, &routine::actionForceMoveToObject);
    _routines.add("GetJournalQuestExperience", VT_I, {VT_S}, &routine::getJournalQuestExperience);
    _routines.add("JumpToObject", VT_V, {VT_O, VT_I}, &routine::jumpToObject);
    _routines.add("SetMapPinEnabled", VT_V, {VT_O, VT_I}, &routine::setMapPinEnabled);
    _routines.add("EffectHitPointChangeWhenDying", VT_EFFECT, {VT_F}, &routine::effectHitPointChangeWhenDying);
    _routines.add("PopUpGUIPanel", VT_V, {VT_O, VT_I}, &routine::popUpGUIPanel);
    _routines.add("AddMultiClass", VT_V, {VT_I, VT_O}, &routine::addMultiClass);
    _routines.add("GetIsLinkImmune", VT_I, {VT_O, VT_EFFECT}, &routine::getIsLinkImmune);
    _routines.add("EffectDroidStun", VT_EFFECT, {}, &routine::effectDroidStun);
    _routines.add("EffectForcePushed", VT_EFFECT, {}, &routine::effectForcePushed);
    _routines.add("GiveXPToCreature", VT_V, {VT_O, VT_I}, &routine::giveXPToCreature);
    _routines.add("SetXP", VT_V, {VT_O, VT_I}, &routine::setXP);
    _routines.add("GetXP", VT_I, {VT_O}, &routine::getXP);
    _routines.add("IntToHexString", VT_S, {VT_I}, &routine::intToHexString);
    _routines.add("GetBaseItemType", VT_I, {VT_O}, &routine::getBaseItemType);
    _routines.add("GetItemHasItemProperty", VT_I, {VT_O, VT_I}, &routine::getItemHasItemProperty);
    _routines.add("ActionEquipMostDamagingMelee", VT_V, {VT_O, VT_I}, &routine::actionEquipMostDamagingMelee);
    _routines.add("ActionEquipMostDamagingRanged", VT_V, {VT_O}, &routine::actionEquipMostDamagingRanged);
    _routines.add("GetItemACValue", VT_I, {VT_O}, &routine::getItemACValue);
    _routines.add("EffectForceResisted", VT_EFFECT, {VT_O}, &routine::effectForceResisted);
    _routines.add("ExploreAreaForPlayer", VT_V, {VT_O, VT_O}, &routine::exploreAreaForPlayer);
    _routines.add("ActionEquipMostEffectiveArmor", VT_V, {}, &routine::actionEquipMostEffectiveArmor);
    _routines.add("GetIsDay", VT_I, {}, &routine::getIsDay);
    _routines.add("GetIsNight", VT_I, {}, &routine::getIsNight);
    _routines.add("GetIsDawn", VT_I, {}, &routine::getIsDawn);
    _routines.add("GetIsDusk", VT_I, {}, &routine::getIsDusk);
    _routines.add("GetIsEncounterCreature", VT_I, {VT_O}, &routine::getIsEncounterCreature);
    _routines.add("GetLastPlayerDying", VT_O, {}, &routine::getLastPlayerDying);
    _routines.add("GetStartingLocation", VT_LOCATION, {}, &routine::getStartingLocation);
    _routines.add("ChangeToStandardFaction", VT_V, {VT_O, VT_I}, &routine::changeToStandardFaction);
    _routines.add("SoundObjectPlay", VT_V, {VT_O}, &routine::soundObjectPlay);
    _routines.add("SoundObjectStop", VT_V, {VT_O}, &routine::soundObjectStop);
    _routines.add("SoundObjectSetVolume", VT_V, {VT_O, VT_I}, &routine::soundObjectSetVolume);
    _routines.add("SoundObjectSetPosition", VT_V, {VT_O, VT_VECTOR}, &routine::soundObjectSetPosition);
    _routines.add("SpeakOneLinerConversation", VT_V, {VT_S, VT_O}, &routine::speakOneLinerConversation);
    _routines.add("GetGold", VT_I, {VT_O}, &routine::getGold);
    _routines.add("GetLastRespawnButtonPresser", VT_O, {}, &routine::getLastRespawnButtonPresser);
    _routines.add("EffectForceFizzle", VT_EFFECT, {}, &routine::effectForceFizzle);
    _routines.add("SetLightsaberPowered", VT_V, {VT_O, VT_I, VT_I, VT_I}, &routine::setLightsaberPowered);
    _routines.add("GetIsWeaponEffective", VT_I, {VT_O, VT_I}, &routine::getIsWeaponEffective);
    _routines.add("GetLastSpellHarmful", VT_I, {}, &routine::getLastSpellHarmful);
    _routines.add("EventActivateItem", VT_EVENT, {VT_O, VT_LOCATION, VT_O}, &routine::eventActivateItem);
    _routines.add("MusicBackgroundPlay", VT_V, {VT_O}, &routine::musicBackgroundPlay);
    _routines.add("MusicBackgroundStop", VT_V, {VT_O}, &routine::musicBackgroundStop);
    _routines.add("MusicBackgroundSetDelay", VT_V, {VT_O, VT_I}, &routine::musicBackgroundSetDelay);
    _routines.add("MusicBackgroundChangeDay", VT_V, {VT_O, VT_I, VT_I}, &routine::musicBackgroundChangeDay);
    _routines.add("MusicBackgroundChangeNight", VT_V, {VT_O, VT_I, VT_I}, &routine::musicBackgroundChangeNight);
    _routines.add("MusicBattlePlay", VT_V, {VT_O}, &routine::musicBattlePlay);
    _routines.add("MusicBattleStop", VT_V, {VT_O}, &routine::musicBattleStop);
    _routines.add("MusicBattleChange", VT_V, {VT_O, VT_I}, &routine::musicBattleChange);
    _routines.add("AmbientSoundPlay", VT_V, {VT_O}, &routine::ambientSoundPlay);
    _routines.add("AmbientSoundStop", VT_V, {VT_O}, &routine::ambientSoundStop);
    _routines.add("AmbientSoundChangeDay", VT_V, {VT_O, VT_I}, &routine::ambientSoundChangeDay);
    _routines.add("AmbientSoundChangeNight", VT_V, {VT_O, VT_I}, &routine::ambientSoundChangeNight);
    _routines.add("GetLastKiller", VT_O, {}, &routine::getLastKiller);
    _routines.add("GetSpellCastItem", VT_O, {}, &routine::getSpellCastItem);
    _routines.add("GetItemActivated", VT_O, {}, &routine::getItemActivated);
    _routines.add("GetItemActivator", VT_O, {}, &routine::getItemActivator);
    _routines.add("GetItemActivatedTargetLocation", VT_LOCATION, {}, &routine::getItemActivatedTargetLocation);
    _routines.add("GetItemActivatedTarget", VT_O, {}, &routine::getItemActivatedTarget);
    _routines.add("GetIsOpen", VT_I, {VT_O}, &routine::getIsOpen);
    _routines.add("TakeGoldFromCreature", VT_V, {VT_I, VT_O, VT_I}, &routine::takeGoldFromCreature);
    _routines.add("GetIsInConversation", VT_I, {VT_O}, &routine::getIsInConversation);
    _routines.add("EffectAbilityDecrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectAbilityDecrease);
    _routines.add("EffectAttackDecrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectAttackDecrease);
    _routines.add("EffectDamageDecrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectDamageDecrease);
    _routines.add("EffectDamageImmunityDecrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectDamageImmunityDecrease);
    _routines.add("EffectACDecrease", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectACDecrease);
    _routines.add("EffectMovementSpeedDecrease", VT_EFFECT, {VT_I}, &routine::effectMovementSpeedDecrease);
    _routines.add("EffectSavingThrowDecrease", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectSavingThrowDecrease);
    _routines.add("EffectSkillDecrease", VT_EFFECT, {VT_I, VT_I}, &routine::effectSkillDecrease);
    _routines.add("EffectForceResistanceDecrease", VT_EFFECT, {VT_I}, &routine::effectForceResistanceDecrease);
    _routines.add("GetPlotFlag", VT_I, {VT_O}, &routine::getPlotFlag);
    _routines.add("SetPlotFlag", VT_V, {VT_O, VT_I}, &routine::setPlotFlag);
    _routines.add("EffectInvisibility", VT_EFFECT, {VT_I}, &routine::effectInvisibility);
    _routines.add("EffectConcealment", VT_EFFECT, {VT_I}, &routine::effectConcealment);
    _routines.add("EffectForceShield", VT_EFFECT, {VT_I}, &routine::effectForceShield);
    _routines.add("EffectDispelMagicAll", VT_EFFECT, {VT_I}, &routine::effectDispelMagicAll);
    _routines.add("SetDialogPlaceableCamera", VT_V, {VT_I}, &routine::setDialogPlaceableCamera);
    _routines.add("GetSoloMode", VT_I, {}, &routine::getSoloMode);
    _routines.add("EffectDisguise", VT_EFFECT, {VT_I}, &routine::effectDisguise);
    _routines.add("GetMaxStealthXP", VT_I, {}, &routine::getMaxStealthXP);
    _routines.add("EffectTrueSeeing", VT_EFFECT, {}, &routine::effectTrueSeeing);
    _routines.add("EffectSeeInvisible", VT_EFFECT, {}, &routine::effectSeeInvisible);
    _routines.add("EffectTimeStop", VT_EFFECT, {}, &routine::effectTimeStop);
    _routines.add("SetMaxStealthXP", VT_V, {VT_I}, &routine::setMaxStealthXP);
    _routines.add("EffectBlasterDeflectionIncrease", VT_EFFECT, {VT_I}, &routine::effectBlasterDeflectionIncrease);
    _routines.add("EffectBlasterDeflectionDecrease", VT_EFFECT, {VT_I}, &routine::effectBlasterDeflectionDecrease);
    _routines.add("EffectHorrified", VT_EFFECT, {}, &routine::effectHorrified);
    _routines.add("EffectSpellLevelAbsorption", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectSpellLevelAbsorption);
    _routines.add("EffectDispelMagicBest", VT_EFFECT, {VT_I}, &routine::effectDispelMagicBest);
    _routines.add("GetCurrentStealthXP", VT_I, {}, &routine::getCurrentStealthXP);
    _routines.add("GetNumStackedItems", VT_I, {VT_O}, &routine::getNumStackedItems);
    _routines.add("SurrenderToEnemies", VT_V, {}, &routine::surrenderToEnemies);
    _routines.add("EffectMissChance", VT_EFFECT, {VT_I}, &routine::effectMissChance);
    _routines.add("SetCurrentStealthXP", VT_V, {VT_I}, &routine::setCurrentStealthXP);
    _routines.add("GetCreatureSize", VT_I, {VT_O}, &routine::getCreatureSize);
    _routines.add("AwardStealthXP", VT_V, {VT_O}, &routine::awardStealthXP);
    _routines.add("GetStealthXPEnabled", VT_I, {}, &routine::getStealthXPEnabled);
    _routines.add("SetStealthXPEnabled", VT_V, {VT_I}, &routine::setStealthXPEnabled);
    _routines.add("ActionUnlockObject", VT_V, {VT_O}, &routine::actionUnlockObject);
    _routines.add("ActionLockObject", VT_V, {VT_O}, &routine::actionLockObject);
    _routines.add("EffectModifyAttacks", VT_EFFECT, {VT_I}, &routine::effectModifyAttacks);
    _routines.add("GetLastTrapDetected", VT_O, {VT_O}, &routine::getLastTrapDetected);
    _routines.add("EffectDamageShield", VT_EFFECT, {VT_I, VT_I, VT_I}, &routine::effectDamageShield);
    _routines.add("GetNearestTrapToObject", VT_O, {VT_O, VT_I}, &routine::getNearestTrapToObject);
    _routines.add("GetAttemptedMovementTarget", VT_O, {}, &routine::getAttemptedMovementTarget);
    _routines.add("GetBlockingCreature", VT_O, {VT_O}, &routine::getBlockingCreature);
    _routines.add("GetFortitudeSavingThrow", VT_I, {VT_O}, &routine::getFortitudeSavingThrow);
    _routines.add("GetWillSavingThrow", VT_I, {VT_O}, &routine::getWillSavingThrow);
    _routines.add("GetReflexSavingThrow", VT_I, {VT_O}, &routine::getReflexSavingThrow);
    _routines.add("GetChallengeRating", VT_F, {VT_O}, &routine::getChallengeRating);
    _routines.add("GetFoundEnemyCreature", VT_O, {VT_O}, &routine::getFoundEnemyCreature);
    _routines.add("GetMovementRate", VT_I, {VT_O}, &routine::getMovementRate);
    _routines.add("GetSubRace", VT_I, {VT_O}, &routine::getSubRace);
    _routines.add("GetStealthXPDecrement", VT_I, {}, &routine::getStealthXPDecrement);
    _routines.add("SetStealthXPDecrement", VT_V, {VT_I}, &routine::setStealthXPDecrement);
    _routines.add("DuplicateHeadAppearance", VT_V, {VT_O, VT_O}, &routine::duplicateHeadAppearance);
    _routines.add("ActionCastFakeSpellAtObject", VT_V, {VT_I, VT_O, VT_I}, &routine::actionCastFakeSpellAtObject);
    _routines.add("ActionCastFakeSpellAtLocation", VT_V, {VT_I, VT_LOCATION, VT_I}, &routine::actionCastFakeSpellAtLocation);
    _routines.add("CutsceneAttack", VT_V, {VT_O, VT_I, VT_I, VT_I}, &routine::cutsceneAttack);
    _routines.add("SetCameraMode", VT_V, {VT_O, VT_I}, &routine::setCameraMode);
    _routines.add("SetLockOrientationInDialog", VT_V, {VT_O, VT_I}, &routine::setLockOrientationInDialog);
    _routines.add("SetLockHeadFollowInDialog", VT_V, {VT_O, VT_I}, &routine::setLockHeadFollowInDialog);
    _routines.add("CutsceneMove", VT_V, {VT_O, VT_VECTOR, VT_I}, &routine::cutsceneMove);
    _routines.add("EnableVideoEffect", VT_V, {VT_I}, &routine::enableVideoEffect);
    _routines.add("StartNewModule", VT_V, {VT_S, VT_S, VT_S, VT_S, VT_S, VT_S, VT_S, VT_S}, &routine::startNewModule);
    _routines.add("DisableVideoEffect", VT_V, {}, &routine::disableVideoEffect);
    _routines.add("GetWeaponRanged", VT_I, {VT_O}, &routine::getWeaponRanged);
    _routines.add("DoSinglePlayerAutoSave", VT_V, {}, &routine::doSinglePlayerAutoSave);
    _routines.add("GetGameDifficulty", VT_I, {}, &routine::getGameDifficulty);
    _routines.add("GetUserActionsPending", VT_I, {}, &routine::getUserActionsPending);
    _routines.add("RevealMap", VT_V, {VT_VECTOR, VT_I}, &routine::revealMap);
    _routines.add("SetTutorialWindowsEnabled", VT_V, {VT_I}, &routine::setTutorialWindowsEnabled);
    _routines.add("ShowTutorialWindow", VT_V, {VT_I}, &routine::showTutorialWindow);
    _routines.add("StartCreditSequence", VT_V, {VT_I}, &routine::startCreditSequence);
    _routines.add("IsCreditSequenceInProgress", VT_I, {}, &routine::isCreditSequenceInProgress);

    _routines.add("SWMG_SetLateralAccelerationPerSecond", VT_V, {VT_F}, &routine::minigame::setLateralAccelerationPerSecond);
    _routines.add("SWMG_GetLateralAccelerationPerSecond", VT_F, {}, &routine::minigame::getLateralAccelerationPerSecond);

    _routines.add("GetCurrentAction", VT_I, {VT_O}, &routine::getCurrentAction);
    _routines.add("GetDifficultyModifier", VT_F, {}, &routine::getDifficultyModifier);
    _routines.add("GetAppearanceType", VT_I, {VT_O}, &routine::getAppearanceType);
    _routines.add("FloatingTextStrRefOnCreature", VT_V, {VT_I, VT_O, VT_I}, &routine::floatingTextStrRefOnCreature);
    _routines.add("FloatingTextStringOnCreature", VT_V, {VT_S, VT_O, VT_I}, &routine::floatingTextStringOnCreature);
    _routines.add("GetTrapDisarmable", VT_I, {VT_O}, &routine::getTrapDisarmable);
    _routines.add("GetTrapDetectable", VT_I, {VT_O}, &routine::getTrapDetectable);
    _routines.add("GetTrapDetectedBy", VT_I, {VT_O, VT_O}, &routine::getTrapDetectedBy);
    _routines.add("GetTrapFlagged", VT_I, {VT_O}, &routine::getTrapFlagged);
    _routines.add("GetTrapBaseType", VT_I, {VT_O}, &routine::getTrapBaseType);
    _routines.add("GetTrapOneShot", VT_I, {VT_O}, &routine::getTrapOneShot);
    _routines.add("GetTrapCreator", VT_O, {VT_O}, &routine::getTrapCreator);
    _routines.add("GetTrapKeyTag", VT_S, {VT_O}, &routine::getTrapKeyTag);
    _routines.add("GetTrapDisarmDC", VT_I, {VT_O}, &routine::getTrapDisarmDC);
    _routines.add("GetTrapDetectDC", VT_I, {VT_O}, &routine::getTrapDetectDC);
    _routines.add("GetLockKeyRequired", VT_I, {VT_O}, &routine::getLockKeyRequired);
    _routines.add("GetLockKeyTag", VT_I, {VT_O}, &routine::getLockKeyTag);
    _routines.add("GetLockLockable", VT_I, {VT_O}, &routine::getLockLockable);
    _routines.add("GetLockUnlockDC", VT_I, {VT_O}, &routine::getLockUnlockDC);
    _routines.add("GetLockLockDC", VT_I, {VT_O}, &routine::getLockLockDC);
    _routines.add("GetPCLevellingUp", VT_O, {}, &routine::getPCLevellingUp);
    _routines.add("GetHasFeatEffect", VT_I, {VT_I, VT_O}, &routine::getHasFeatEffect);
    _routines.add("SetPlaceableIllumination", VT_V, {VT_O, VT_I}, &routine::setPlaceableIllumination);
    _routines.add("GetPlaceableIllumination", VT_I, {VT_O}, &routine::getPlaceableIllumination);
    _routines.add("GetIsPlaceableObjectActionPossible", VT_I, {VT_O, VT_I}, &routine::getIsPlaceableObjectActionPossible);
    _routines.add("DoPlaceableObjectAction", VT_V, {VT_O, VT_I}, &routine::doPlaceableObjectAction);
    _routines.add("GetFirstPC", VT_O, {}, &routine::getFirstPC);
    _routines.add("GetNextPC", VT_O, {}, &routine::getNextPC);
    _routines.add("SetTrapDetectedBy", VT_I, {VT_O, VT_O}, &routine::setTrapDetectedBy);
    _routines.add("GetIsTrapped", VT_I, {VT_O}, &routine::getIsTrapped);
    _routines.add("SetEffectIcon", VT_EFFECT, {VT_EFFECT, VT_I}, &routine::setEffectIcon);
    _routines.add("FaceObjectAwayFromObject", VT_V, {VT_O, VT_O}, &routine::faceObjectAwayFromObject);
    _routines.add("PopUpDeathGUIPanel", VT_V, {VT_O, VT_I, VT_I, VT_I, VT_S}, &routine::popUpDeathGUIPanel);
    _routines.add("SetTrapDisabled", VT_V, {VT_O}, &routine::setTrapDisabled);
    _routines.add("GetLastHostileActor", VT_O, {VT_O}, &routine::getLastHostileActor);
    _routines.add("ExportAllCharacters", VT_V, {}, &routine::exportAllCharacters);
    _routines.add("MusicBackgroundGetDayTrack", VT_I, {VT_O}, &routine::musicBackgroundGetDayTrack);
    _routines.add("MusicBackgroundGetNightTrack", VT_I, {VT_O}, &routine::musicBackgroundGetNightTrack);
    _routines.add("WriteTimestampedLogEntry", VT_V, {VT_S}, &routine::writeTimestampedLogEntry);
    _routines.add("GetModuleName", VT_S, {}, &routine::getModuleName);
    _routines.add("GetFactionLeader", VT_O, {VT_O}, &routine::getFactionLeader);

    _routines.add("SWMG_SetSpeedBlurEffect", VT_V, {VT_I, VT_F}, &routine::minigame::setSpeedBlurEffect);

    _routines.add("EndGame", VT_V, {VT_I}, &routine::endGame);
    _routines.add("GetRunScriptVar", VT_I, {}, &routine::getRunScriptVar);
    _routines.add("GetCreatureMovmentType", VT_I, {VT_O}, &routine::getCreatureMovmentType);
    _routines.add("AmbientSoundSetDayVolume", VT_V, {VT_O, VT_I}, &routine::ambientSoundSetDayVolume);
    _routines.add("AmbientSoundSetNightVolume", VT_V, {VT_O, VT_I}, &routine::ambientSoundSetNightVolume);
    _routines.add("MusicBackgroundGetBattleTrack", VT_I, {VT_O}, &routine::musicBackgroundGetBattleTrack);
    _routines.add("GetHasInventory", VT_I, {VT_O}, &routine::getHasInventory);
    _routines.add("GetStrRefSoundDuration", VT_F, {VT_I}, &routine::getStrRefSoundDuration);
    _routines.add("AddToParty", VT_V, {VT_O, VT_O}, &routine::addToParty);
    _routines.add("RemoveFromParty", VT_V, {VT_O}, &routine::removeFromParty);
    _routines.add("AddPartyMember", VT_I, {VT_I, VT_O}, &routine::addPartyMember);
    _routines.add("RemovePartyMember", VT_I, {VT_I}, &routine::removePartyMember);
    _routines.add("IsObjectPartyMember", VT_I, {VT_O}, &routine::isObjectPartyMember);
    _routines.add("GetPartyMemberByIndex", VT_O, {VT_I}, &routine::getPartyMemberByIndex);
    _routines.add("GetGlobalBoolean", VT_I, {VT_S}, &routine::getGlobalBoolean);
    _routines.add("SetGlobalBoolean", VT_V, {VT_S, VT_I}, &routine::setGlobalBoolean);
    _routines.add("GetGlobalNumber", VT_I, {VT_S}, &routine::getGlobalNumber);
    _routines.add("SetGlobalNumber", VT_V, {VT_S, VT_I}, &routine::setGlobalNumber);
    _routines.add("AurPostString", VT_V, {VT_S, VT_I, VT_I, VT_F}, &routine::aurPostString);

    _routines.add("SWMG_GetLastEvent", VT_S, {}, &routine::minigame::getLastEvent);
    _routines.add("SWMG_GetLastEventModelName", VT_S, {}, &routine::minigame::getLastEventModelName);
    _routines.add("SWMG_GetObjectByName", VT_O, {VT_S}, &routine::minigame::getObjectByName);
    _routines.add("SWMG_PlayAnimation", VT_V, {VT_O, VT_S, VT_I, VT_I, VT_I}, &routine::minigame::playAnimation);
    _routines.add("SWMG_GetLastBulletHitDamage", VT_I, {}, &routine::minigame::getLastBulletHitDamage);
    _routines.add("SWMG_GetLastBulletHitTarget", VT_I, {}, &routine::minigame::getLastBulletHitTarget);
    _routines.add("SWMG_GetLastBulletHitShooter", VT_O, {}, &routine::minigame::getLastBulletHitShooter);
    _routines.add("SWMG_AdjustFollowerHitPoints", VT_I, {VT_O, VT_I, VT_I}, &routine::minigame::adjustFollowerHitPoints);
    _routines.add("SWMG_OnBulletHit", VT_V, {}, &routine::minigame::onBulletHit);
    _routines.add("SWMG_OnObstacleHit", VT_V, {}, &routine::minigame::onObstacleHit);
    _routines.add("SWMG_GetLastFollowerHit", VT_O, {}, &routine::minigame::getLastFollowerHit);
    _routines.add("SWMG_GetLastObstacleHit", VT_O, {}, &routine::minigame::getLastObstacleHit);
    _routines.add("SWMG_GetLastBulletFiredDamage", VT_I, {}, &routine::minigame::getLastBulletFiredDamage);
    _routines.add("SWMG_GetLastBulletFiredTarget", VT_I, {}, &routine::minigame::getLastBulletFiredTarget);
    _routines.add("SWMG_GetObjectName", VT_S, {VT_O}, &routine::minigame::getObjectName);
    _routines.add("SWMG_OnDeath", VT_V, {}, &routine::minigame::onDeath);
    _routines.add("SWMG_IsFollower", VT_I, {VT_O}, &routine::minigame::isFollower);
    _routines.add("SWMG_IsPlayer", VT_I, {VT_O}, &routine::minigame::isPlayer);
    _routines.add("SWMG_IsEnemy", VT_I, {VT_O}, &routine::minigame::isEnemy);
    _routines.add("SWMG_IsTrigger", VT_I, {VT_O}, &routine::minigame::isTrigger);
    _routines.add("SWMG_IsObstacle", VT_I, {VT_O}, &routine::minigame::isObstacle);
    _routines.add("SWMG_SetFollowerHitPoints", VT_V, {VT_O, VT_I}, &routine::minigame::setFollowerHitPoints);
    _routines.add("SWMG_OnDamage", VT_V, {}, &routine::minigame::onDamage);
    _routines.add("SWMG_GetLastHPChange", VT_I, {}, &routine::minigame::getLastHPChange);
    _routines.add("SWMG_RemoveAnimation", VT_V, {VT_O, VT_S}, &routine::minigame::removeAnimation);
    _routines.add("SWMG_GetCameraNearClip", VT_F, {}, &routine::minigame::getCameraNearClip);
    _routines.add("SWMG_GetCameraFarClip", VT_F, {}, &routine::minigame::getCameraFarClip);
    _routines.add("SWMG_SetCameraClip", VT_V, {VT_F, VT_F}, &routine::minigame::setCameraClip);
    _routines.add("SWMG_GetPlayer", VT_O, {}, &routine::minigame::getPlayer);
    _routines.add("SWMG_GetEnemyCount", VT_I, {}, &routine::minigame::getEnemyCount);
    _routines.add("SWMG_GetEnemy", VT_O, {VT_I}, &routine::minigame::getEnemy);
    _routines.add("SWMG_GetObstacleCount", VT_I, {}, &routine::minigame::getObstacleCount);
    _routines.add("SWMG_GetObstacle", VT_O, {VT_I}, &routine::minigame::getObstacle);
    _routines.add("SWMG_GetHitPoints", VT_I, {VT_O}, &routine::minigame::getHitPoints);
    _routines.add("SWMG_GetMaxHitPoints", VT_I, {VT_O}, &routine::minigame::getMaxHitPoints);
    _routines.add("SWMG_SetMaxHitPoints", VT_V, {VT_O, VT_I}, &routine::minigame::setMaxHitPoints);
    _routines.add("SWMG_GetSphereRadius", VT_F, {VT_O}, &routine::minigame::getSphereRadius);
    _routines.add("SWMG_SetSphereRadius", VT_V, {VT_O, VT_F}, &routine::minigame::setSphereRadius);
    _routines.add("SWMG_GetNumLoops", VT_I, {VT_O}, &routine::minigame::getNumLoops);
    _routines.add("SWMG_SetNumLoops", VT_V, {VT_O, VT_I}, &routine::minigame::setNumLoops);
    _routines.add("SWMG_GetPosition", VT_VECTOR, {VT_O}, &routine::minigame::getPosition);
    _routines.add("SWMG_GetGunBankCount", VT_I, {VT_O}, &routine::minigame::getGunBankCount);
    _routines.add("SWMG_GetGunBankBulletModel", VT_S, {VT_O, VT_I}, &routine::minigame::getGunBankBulletModel);
    _routines.add("SWMG_GetGunBankGunModel", VT_S, {VT_O, VT_I}, &routine::minigame::getGunBankGunModel);
    _routines.add("SWMG_GetGunBankDamage", VT_I, {VT_O, VT_I}, &routine::minigame::getGunBankDamage);
    _routines.add("SWMG_GetGunBankTimeBetweenShots", VT_F, {VT_O, VT_I}, &routine::minigame::getGunBankTimeBetweenShots);
    _routines.add("SWMG_GetGunBankLifespan", VT_F, {VT_O, VT_I}, &routine::minigame::getGunBankLifespan);
    _routines.add("SWMG_GetGunBankSpeed", VT_F, {VT_O, VT_I}, &routine::minigame::getGunBankSpeed);
    _routines.add("SWMG_GetGunBankTarget", VT_I, {VT_O, VT_I}, &routine::minigame::getGunBankTarget);
    _routines.add("SWMG_SetGunBankBulletModel", VT_V, {VT_O, VT_I, VT_S}, &routine::minigame::setGunBankBulletModel);
    _routines.add("SWMG_SetGunBankGunModel", VT_V, {VT_O, VT_I, VT_S}, &routine::minigame::setGunBankGunModel);
    _routines.add("SWMG_SetGunBankDamage", VT_V, {VT_O, VT_I, VT_I}, &routine::minigame::setGunBankDamage);
    _routines.add("SWMG_SetGunBankTimeBetweenShots", VT_V, {VT_O, VT_I, VT_F}, &routine::minigame::setGunBankTimeBetweenShots);
    _routines.add("SWMG_SetGunBankLifespan", VT_V, {VT_O, VT_I, VT_F}, &routine::minigame::setGunBankLifespan);
    _routines.add("SWMG_SetGunBankSpeed", VT_V, {VT_O, VT_I, VT_F}, &routine::minigame::setGunBankSpeed);
    _routines.add("SWMG_SetGunBankTarget", VT_V, {VT_O, VT_I, VT_I}, &routine::minigame::setGunBankTarget);
    _routines.add("SWMG_GetLastBulletHitPart", VT_S, {}, &routine::minigame::getLastBulletHitPart);
    _routines.add("SWMG_IsGunBankTargetting", VT_I, {VT_O, VT_I}, &routine::minigame::isGunBankTargetting);
    _routines.add("SWMG_GetPlayerOffset", VT_VECTOR, {}, &routine::minigame::getPlayerOffset);
    _routines.add("SWMG_GetPlayerInvincibility", VT_F, {}, &routine::minigame::getPlayerInvincibility);
    _routines.add("SWMG_GetPlayerSpeed", VT_F, {}, &routine::minigame::getPlayerSpeed);
    _routines.add("SWMG_GetPlayerMinSpeed", VT_F, {}, &routine::minigame::getPlayerMinSpeed);
    _routines.add("SWMG_GetPlayerAccelerationPerSecond", VT_F, {}, &routine::minigame::getPlayerAccelerationPerSecond);
    _routines.add("SWMG_GetPlayerTunnelPos", VT_VECTOR, {}, &routine::minigame::getPlayerTunnelPos);
    _routines.add("SWMG_SetPlayerOffset", VT_V, {VT_VECTOR}, &routine::minigame::setPlayerOffset);
    _routines.add("SWMG_SetPlayerInvincibility", VT_V, {VT_F}, &routine::minigame::setPlayerInvincibility);
    _routines.add("SWMG_SetPlayerSpeed", VT_V, {VT_F}, &routine::minigame::setPlayerSpeed);
    _routines.add("SWMG_SetPlayerMinSpeed", VT_V, {VT_F}, &routine::minigame::setPlayerMinSpeed);
    _routines.add("SWMG_SetPlayerAccelerationPerSecond", VT_V, {VT_F}, &routine::minigame::setPlayerAccelerationPerSecond);
    _routines.add("SWMG_SetPlayerTunnelPos", VT_V, {VT_VECTOR}, &routine::minigame::setPlayerTunnelPos);
    _routines.add("SWMG_GetPlayerTunnelNeg", VT_VECTOR, {}, &routine::minigame::getPlayerTunnelNeg);
    _routines.add("SWMG_SetPlayerTunnelNeg", VT_V, {VT_VECTOR}, &routine::minigame::setPlayerTunnelNeg);
    _routines.add("SWMG_GetPlayerOrigin", VT_VECTOR, {}, &routine::minigame::getPlayerOrigin);
    _routines.add("SWMG_SetPlayerOrigin", VT_V, {VT_VECTOR}, &routine::minigame::setPlayerOrigin);
    _routines.add("SWMG_GetGunBankHorizontalSpread", VT_F, {VT_O, VT_I}, &routine::minigame::getGunBankHorizontalSpread);
    _routines.add("SWMG_GetGunBankVerticalSpread", VT_F, {VT_O, VT_I}, &routine::minigame::getGunBankVerticalSpread);
    _routines.add("SWMG_GetGunBankSensingRadius", VT_F, {VT_O, VT_I}, &routine::minigame::getGunBankSensingRadius);
    _routines.add("SWMG_GetGunBankInaccuracy", VT_F, {VT_O, VT_I}, &routine::minigame::getGunBankInaccuracy);
    _routines.add("SWMG_SetGunBankHorizontalSpread", VT_V, {VT_O, VT_I, VT_F}, &routine::minigame::setGunBankHorizontalSpread);
    _routines.add("SWMG_SetGunBankVerticalSpread", VT_V, {VT_O, VT_I, VT_F}, &routine::minigame::setGunBankVerticalSpread);
    _routines.add("SWMG_SetGunBankSensingRadius", VT_V, {VT_O, VT_I, VT_F}, &routine::minigame::setGunBankSensingRadius);
    _routines.add("SWMG_SetGunBankInaccuracy", VT_V, {VT_O, VT_I, VT_F}, &routine::minigame::setGunBankInaccuracy);
    _routines.add("SWMG_GetIsInvulnerable", VT_I, {VT_O}, &routine::minigame::getIsInvulnerable);
    _routines.add("SWMG_StartInvulnerability", VT_V, {VT_O}, &routine::minigame::startInvulnerability);
    _routines.add("SWMG_GetPlayerMaxSpeed", VT_F, {}, &routine::minigame::getPlayerMaxSpeed);
    _routines.add("SWMG_SetPlayerMaxSpeed", VT_V, {VT_F}, &routine::minigame::setPlayerMaxSpeed);

    _routines.add("AddJournalWorldEntry", VT_V, {VT_I, VT_S, VT_S}, &routine::addJournalWorldEntry);
    _routines.add("AddJournalWorldEntryStrref", VT_V, {VT_I, VT_I}, &routine::addJournalWorldEntryStrref);
    _routines.add("BarkString", VT_V, {VT_O, VT_I, VT_I, VT_I}, &routine::barkString);
    _routines.add("DeleteJournalWorldAllEntries", VT_V, {}, &routine::deleteJournalWorldAllEntries);
    _routines.add("DeleteJournalWorldEntry", VT_V, {VT_I}, &routine::deleteJournalWorldEntry);
    _routines.add("DeleteJournalWorldEntryStrref", VT_V, {VT_I}, &routine::deleteJournalWorldEntryStrref);
    _routines.add("EffectForceDrain", VT_EFFECT, {VT_I}, &routine::effectForceDrain);
    _routines.add("EffectPsychicStatic", VT_EFFECT, {}, &routine::effectPsychicStatic);
    _routines.add("PlayVisualAreaEffect", VT_V, {VT_I, VT_LOCATION}, &routine::playVisualAreaEffect);
    _routines.add("SetJournalQuestEntryPicture", VT_V, {VT_S, VT_O, VT_I, VT_I, VT_I}, &routine::setJournalQuestEntryPicture);
    _routines.add("GetLocalBoolean", VT_I, {VT_O, VT_I}, &routine::getLocalBoolean);
    _routines.add("SetLocalBoolean", VT_V, {VT_O, VT_I, VT_I}, &routine::setLocalBoolean);
    _routines.add("GetLocalNumber", VT_I, {VT_O, VT_I}, &routine::getLocalNumber);
    _routines.add("SetLocalNumber", VT_V, {VT_O, VT_I, VT_I}, &routine::setLocalNumber);

    _routines.add("SWMG_GetSoundFrequency", VT_I, {VT_O, VT_I}, &routine::minigame::getSoundFrequency);
    _routines.add("SWMG_SetSoundFrequency", VT_V, {VT_O, VT_I, VT_I}, &routine::minigame::setSoundFrequency);
    _routines.add("SWMG_GetSoundFrequencyIsRandom", VT_I, {VT_O, VT_I}, &routine::minigame::getSoundFrequencyIsRandom);
    _routines.add("SWMG_SetSoundFrequencyIsRandom", VT_V, {VT_O, VT_I, VT_I}, &routine::minigame::setSoundFrequencyIsRandom);
    _routines.add("SWMG_GetSoundVolume", VT_I, {VT_O, VT_I}, &routine::minigame::getSoundVolume);
    _routines.add("SWMG_SetSoundVolume", VT_V, {VT_O, VT_I, VT_I}, &routine::minigame::setSoundVolume);

    _routines.add("SoundObjectGetPitchVariance", VT_F, {VT_O}, &routine::soundObjectGetPitchVariance);
    _routines.add("SoundObjectSetPitchVariance", VT_V, {VT_O, VT_F}, &routine::soundObjectSetPitchVariance);
    _routines.add("SoundObjectGetVolume", VT_I, {VT_O}, &routine::soundObjectGetVolume);
    _routines.add("GetGlobalLocation", VT_LOCATION, {VT_S}, &routine::getGlobalLocation);
    _routines.add("SetGlobalLocation", VT_V, {VT_S, VT_LOCATION}, &routine::setGlobalLocation);
    _routines.add("AddAvailableNPCByObject", VT_I, {VT_I, VT_O}, &routine::addAvailableNPCByObject);
    _routines.add("RemoveAvailableNPC", VT_I, {VT_I}, &routine::removeAvailableNPC);
    _routines.add("IsAvailableCreature", VT_I, {VT_I}, &routine::isAvailableCreature);
    _routines.add("AddAvailableNPCByTemplate", VT_I, {VT_I, VT_S}, &routine::addAvailableNPCByTemplate);
    _routines.add("SpawnAvailableNPC", VT_O, {VT_I, VT_LOCATION}, &routine::spawnAvailableNPC);
    _routines.add("IsNPCPartyMember", VT_I, {VT_I}, &routine::isNPCPartyMember);
    _routines.add("ActionBarkString", VT_V, {VT_I}, &routine::actionBarkString);
    _routines.add("GetIsConversationActive", VT_I, {}, &routine::getIsConversationActive);
    _routines.add("EffectLightsaberThrow", VT_EFFECT, {VT_O, VT_O, VT_O, VT_I}, &routine::effectLightsaberThrow);
    _routines.add("EffectWhirlWind", VT_EFFECT, {}, &routine::effectWhirlWind);
    _routines.add("GetPartyAIStyle", VT_I, {}, &routine::getPartyAIStyle);
    _routines.add("GetNPCAIStyle", VT_I, {VT_O}, &routine::getNPCAIStyle);
    _routines.add("SetPartyAIStyle", VT_V, {VT_I}, &routine::setPartyAIStyle);
    _routines.add("SetNPCAIStyle", VT_V, {VT_O, VT_I}, &routine::setNPCAIStyle);
    _routines.add("SetNPCSelectability", VT_V, {VT_I, VT_I}, &routine::setNPCSelectability);
    _routines.add("GetNPCSelectability", VT_I, {VT_I}, &routine::getNPCSelectability);
    _routines.add("ClearAllEffects", VT_V, {}, &routine::clearAllEffects);
    _routines.add("GetLastConversation", VT_S, {}, &routine::getLastConversation);
    _routines.add("ShowPartySelectionGUI", VT_V, {VT_S, VT_I, VT_I, VT_I}, &routine::showPartySelectionGUI);
    _routines.add("GetStandardFaction", VT_I, {VT_O}, &routine::getStandardFaction);
    _routines.add("GivePlotXP", VT_V, {VT_S, VT_I}, &routine::givePlotXP);
    _routines.add("GetMinOneHP", VT_I, {VT_O}, &routine::getMinOneHP);
    _routines.add("SetMinOneHP", VT_V, {VT_O, VT_I}, &routine::setMinOneHP);

    _routines.add("SWMG_GetPlayerTunnelInfinite", VT_VECTOR, {}, &routine::minigame::getPlayerTunnelInfinite);
    _routines.add("SWMG_SetPlayerTunnelInfinite", VT_V, {VT_VECTOR}, &routine::minigame::setPlayerTunnelInfinite);

    _routines.add("SetGlobalFadeIn", VT_V, {VT_F, VT_F, VT_F, VT_F, VT_F}, &routine::setGlobalFadeIn);
    _routines.add("SetGlobalFadeOut", VT_V, {VT_F, VT_F, VT_F, VT_F, VT_F}, &routine::setGlobalFadeOut);
    _routines.add("GetLastHostileTarget", VT_O, {VT_O}, &routine::getLastHostileTarget);
    _routines.add("GetLastAttackAction", VT_I, {VT_O}, &routine::getLastAttackAction);
    _routines.add("GetLastForcePowerUsed", VT_I, {VT_O}, &routine::getLastForcePowerUsed);
    _routines.add("GetLastCombatFeatUsed", VT_I, {VT_O}, &routine::getLastCombatFeatUsed);
    _routines.add("GetLastAttackResult", VT_I, {VT_O}, &routine::getLastAttackResult);
    _routines.add("GetWasForcePowerSuccessful", VT_I, {VT_O}, &routine::getWasForcePowerSuccessful);
    _routines.add("GetFirstAttacker", VT_O, {VT_O}, &routine::getFirstAttacker);
    _routines.add("GetNextAttacker", VT_O, {VT_O}, &routine::getNextAttacker);
    _routines.add("SetFormation", VT_V, {VT_O, VT_O, VT_I, VT_I}, &routine::setFormation);
    _routines.add("ActionFollowLeader", VT_V, {}, &routine::actionFollowLeader);
    _routines.add("SetForcePowerUnsuccessful", VT_V, {VT_I, VT_O}, &routine::setForcePowerUnsuccessful);
    _routines.add("GetIsDebilitated", VT_I, {VT_O}, &routine::getIsDebilitated);
    _routines.add("PlayMovie", VT_V, {VT_S, VT_I}, &routine::playMovie);
    _routines.add("SaveNPCState", VT_V, {VT_I}, &routine::saveNPCState);
    _routines.add("GetCategoryFromTalent", VT_I, {VT_TALENT}, &routine::getCategoryFromTalent);
    _routines.add("SurrenderByFaction", VT_V, {VT_I, VT_I}, &routine::surrenderByFaction);
    _routines.add("ChangeFactionByFaction", VT_V, {VT_I, VT_I}, &routine::changeFactionByFaction);
    _routines.add("PlayRoomAnimation", VT_V, {VT_S, VT_I}, &routine::playRoomAnimation);
    _routines.add("ShowGalaxyMap", VT_V, {VT_I}, &routine::showGalaxyMap);
    _routines.add("SetPlanetSelectable", VT_V, {VT_I, VT_I}, &routine::setPlanetSelectable);
    _routines.add("GetPlanetSelectable", VT_I, {VT_I}, &routine::getPlanetSelectable);
    _routines.add("SetPlanetAvailable", VT_V, {VT_I, VT_I}, &routine::setPlanetAvailable);
    _routines.add("GetPlanetAvailable", VT_I, {VT_I}, &routine::getPlanetAvailable);
    _routines.add("GetSelectedPlanet", VT_I, {}, &routine::getSelectedPlanet);
    _routines.add("SoundObjectFadeAndStop", VT_V, {VT_O, VT_F}, &routine::soundObjectFadeAndStop);
    _routines.add("SetAreaFogColor", VT_V, {VT_O, VT_F, VT_F, VT_F}, &routine::setAreaFogColor);
    _routines.add("ChangeItemCost", VT_V, {VT_S, VT_F}, &routine::changeItemCost);
    _routines.add("GetIsLiveContentAvailable", VT_I, {VT_I}, &routine::getIsLiveContentAvailable);
    _routines.add("ResetDialogState", VT_V, {}, &routine::resetDialogState);
    _routines.add("SetGoodEvilValue", VT_V, {VT_O, VT_I}, &routine::setGoodEvilValue);
    _routines.add("GetIsPoisoned", VT_I, {VT_O}, &routine::getIsPoisoned);
    _routines.add("GetSpellTarget", VT_O, {VT_O}, &routine::getSpellTarget);
    _routines.add("SetSoloMode", VT_V, {VT_I}, &routine::setSoloMode);
    _routines.add("EffectCutSceneHorrified", VT_EFFECT, {}, &routine::effectCutSceneHorrified);
    _routines.add("EffectCutSceneParalyze", VT_EFFECT, {}, &routine::effectCutSceneParalyze);
    _routines.add("EffectCutSceneStunned", VT_EFFECT, {}, &routine::effectCutSceneStunned);
    _routines.add("CancelPostDialogCharacterSwitch", VT_V, {}, &routine::cancelPostDialogCharacterSwitch);
    _routines.add("SetMaxHitPoints", VT_V, {VT_O, VT_I}, &routine::setMaxHitPoints);
    _routines.add("NoClicksFor", VT_V, {VT_F}, &routine::noClicksFor);
    _routines.add("HoldWorldFadeInForDialog", VT_V, {}, &routine::holdWorldFadeInForDialog);
    _routines.add("ShipBuild", VT_I, {}, &routine::shipBuild);
    _routines.add("SurrenderRetainBuffs", VT_V, {}, &routine::surrenderRetainBuffs);
    _routines.add("SuppressStatusSummaryEntry", VT_V, {VT_I}, &routine::suppressStatusSummaryEntry);
    _routines.add("GetCheatCode", VT_I, {VT_I}, &routine::getCheatCode);
    _routines.add("SetMusicVolume", VT_V, {VT_F}, &routine::setMusicVolume);
    _routines.add("CreateItemOnFloor", VT_O, {VT_S, VT_LOCATION, VT_I}, &routine::createItemOnFloor);
    _routines.add("SetAvailableNPCId", VT_V, {VT_I, VT_O}, &routine::setAvailableNPCId);
    _routines.add("GetScriptParameter", VT_I, {VT_I}, &routine::getScriptParameter);
    _routines.add("SetFadeUntilScript", VT_V, {}, &routine::setFadeUntilScript);
    _routines.add("EffectForceBody", VT_EFFECT, {VT_I}, &routine::effectForceBody);
    _routines.add("GetItemComponent", VT_I, {}, &routine::getItemComponent);
    _routines.add("GetItemComponentPieceValue", VT_I, {}, &routine::getItemComponentPieceValue);
    _routines.add("ShowChemicalUpgradeScreen", VT_V, {VT_O}, &routine::showChemicalUpgradeScreen);
    _routines.add("GetChemicals", VT_I, {}, &routine::getChemicals);
    _routines.add("GetChemicalPieceValue", VT_I, {}, &routine::getChemicalPieceValue);
    _routines.add("GetSpellForcePointCost", VT_I, {}, &routine::getSpellForcePointCost);
    _routines.add("EffectFury", VT_EFFECT, {}, &routine::effectFury);
    _routines.add("EffectBlind", VT_EFFECT, {}, &routine::effectBlind);
    _routines.add("EffectFPRegenModifier", VT_EFFECT, {VT_I}, &routine::effectFPRegenModifier);
    _routines.add("EffectVPRegenModifier", VT_EFFECT, {VT_I}, &routine::effectVPRegenModifier);
    _routines.add("EffectCrush", VT_EFFECT, {}, &routine::effectCrush);

    _routines.add("SWMG_GetSwoopUpgrade", VT_I, {VT_I}, &routine::minigame::getSwoopUpgrade);

    _routines.add("GetFeatAcquired", VT_I, {VT_I, VT_O}, &routine::getFeatAcquired);
    _routines.add("GetSpellAcquired", VT_I, {VT_I, VT_O}, &routine::getSpellAcquired);
    _routines.add("ShowSwoopUpgradeScreen", VT_V, {}, &routine::showSwoopUpgradeScreen);
    _routines.add("GrantFeat", VT_V, {VT_I, VT_O}, &routine::grantFeat);
    _routines.add("GrantSpell", VT_V, {VT_I, VT_O}, &routine::grantSpell);
    _routines.add("SpawnMine", VT_V, {VT_I, VT_LOCATION, VT_I, VT_I, VT_O}, &routine::spawnMine);

    _routines.add("SWMG_GetTrackPosition", VT_VECTOR, {VT_O}, &routine::minigame::getTrackPosition);
    _routines.add("SWMG_SetFollowerPosition", VT_VECTOR, {VT_VECTOR}, &routine::minigame::setFollowerPosition);

    _routines.add("SetFakeCombatState", VT_V, {VT_O, VT_I}, &routine::setFakeCombatState);

    _routines.add("SWMG_DestroyMiniGameObject", VT_V, {VT_O}, &routine::minigame::destroyMiniGameObject);

    _routines.add("GetOwnerDemolitionsSkill", VT_I, {VT_O}, &routine::getOwnerDemolitionsSkill);
    _routines.add("SetOrientOnClick", VT_V, {VT_O, VT_I}, &routine::setOrientOnClick);
    _routines.add("GetInfluence", VT_I, {VT_I}, &routine::getInfluence);
    _routines.add("SetInfluence", VT_V, {VT_I, VT_I}, &routine::setInfluence);
    _routines.add("ModifyInfluence", VT_V, {VT_I, VT_I}, &routine::modifyInfluence);
    _routines.add("GetRacialSubType", VT_I, {VT_O}, &routine::getRacialSubType);
    _routines.add("IncrementGlobalNumber", VT_V, {VT_S, VT_I}, &routine::incrementGlobalNumber);
    _routines.add("DecrementGlobalNumber", VT_V, {VT_S, VT_I}, &routine::decrementGlobalNumber);
    _routines.add("SetBonusForcePoints", VT_V, {VT_O, VT_I}, &routine::setBonusForcePoints);
    _routines.add("AddBonusForcePoints", VT_V, {VT_O, VT_I}, &routine::addBonusForcePoints);
    _routines.add("GetBonusForcePoints", VT_V, {VT_O}, &routine::getBonusForcePoints);

    _routines.add("SWMG_SetJumpSpeed", VT_V, {VT_F}, &routine::minigame::setJumpSpeed);

    _routines.add("IsMoviePlaying", VT_I, {}, &routine::isMoviePlaying);
    _routines.add("QueueMovie", VT_V, {VT_S, VT_I}, &routine::queueMovie);
    _routines.add("PlayMovieQueue", VT_V, {VT_I}, &routine::playMovieQueue);
    _routines.add("YavinHackDoorClose", VT_V, {VT_O}, &routine::yavinHackCloseDoor);
    _routines.add("EffectDroidConfused", VT_EFFECT, {}, &routine::effectDroidConfused);
    _routines.add("IsStealthed", VT_I, {VT_O}, &routine::isStealthed);
    _routines.add("IsMeditating", VT_I, {VT_O}, &routine::isMeditating);
    _routines.add("IsInTotalDefense", VT_I, {VT_O}, &routine::isInTotalDefense);
    _routines.add("SetHealTarget", VT_V, {VT_O, VT_O}, &routine::setHealTarget);
    _routines.add("GetHealTarget", VT_O, {VT_O}, &routine::getHealTarget);
    _routines.add("GetRandomDestination", VT_VECTOR, {VT_O, VT_I}, &routine::getRandomDestination);
    _routines.add("IsFormActive", VT_I, {VT_O, VT_I}, &routine::isFormActive);
    _routines.add("GetSpellFormMask", VT_I, {VT_I}, &routine::getSpellFormMask);
    _routines.add("GetSpellBaseForcePointCost", VT_I, {VT_I}, &routine::getSpellBaseForcePointCost);
    _routines.add("SetKeepStealthInDialog", VT_V, {VT_I}, &routine::setKeepStealthInDialog);
    _routines.add("HasLineOfSight", VT_I, {VT_VECTOR, VT_VECTOR, VT_O, VT_O}, &routine::hasLineOfSight);
    _routines.add("ShowDemoScreen", VT_I, {VT_S, VT_I, VT_I, VT_I, VT_I}, &routine::showDemoScreen);
    _routines.add("ForceHeartbeat", VT_V, {VT_O}, &routine::forceHeartbeat);
    _routines.add("EffectForceSight", VT_EFFECT, {}, &routine::effectForceSight);
    _routines.add("IsRunning", VT_I, {VT_O}, &routine::isRunning);

    _routines.add("SWMG_PlayerApplyForce", VT_V, {VT_VECTOR}, &routine::minigame::playerApplyForce);

    _routines.add("SetForfeitConditions", VT_V, {VT_I}, &routine::setForfeitConditions);
    _routines.add("GetLastForfeitViolation", VT_I, {}, &routine::getLastForfeitViolation);
    _routines.add("ModifyReflexSavingThrowBase", VT_V, {VT_O, VT_I}, &routine::modifyReflexSavingThrowBase);
    _routines.add("ModifyFortitudeSavingThrowBase", VT_V, {VT_O, VT_I}, &routine::modifyFortitudeSavingThrowBase);
    _routines.add("ModifyWillSavingThrowBase", VT_V, {VT_O, VT_I}, &routine::modifyWillSavingThrowBase);
    _routines.add("GetScriptStringParameter", VT_S, {}, &routine::getScriptStringParameter);
    _routines.add("GetObjectPersonalSpace", VT_F, {VT_O}, &routine::getObjectPersonalSpace);
    _routines.add("AdjustCreatureAttributes", VT_V, {VT_O, VT_I, VT_I}, &routine::adjustCreatureAttributes);
    _routines.add("SetCreatureAILevel", VT_V, {VT_O, VT_I}, &routine::setCreatureAILevel);
    _routines.add("ResetCreatureAILevel", VT_V, {VT_O}, &routine::resetCreatureAILevel);
    _routines.add("AddAvailablePUPByTemplate", VT_I, {VT_I, VT_S}, &routine::addAvailablePUPByTemplate);
    _routines.add("AddAvailablePUPByObject", VT_I, {VT_I, VT_O}, &routine::addAvailablePUPByObject);
    _routines.add("AssignPUP", VT_I, {VT_I, VT_I}, &routine::assignPUP);
    _routines.add("SpawnAvailablePUP", VT_O, {VT_I, VT_LOCATION}, &routine::spawnAvailablePUP);
    _routines.add("AddPartyPuppet", VT_I, {VT_I, VT_O}, &routine::addPartyPuppet);
    _routines.add("GetPUPOwner", VT_O, {VT_O}, &routine::getPUPOwner);
    _routines.add("GetIsPuppet", VT_I, {VT_O}, &routine::getIsPuppet);
    _routines.add("ActionFollowOwner", VT_V, {VT_F}, &routine::actionFollowOwner);
    _routines.add("GetIsPartyLeader", VT_I, {VT_O}, &routine::getIsPartyLeader);
    _routines.add("GetPartyLeader", VT_O, {}, &routine::getPartyLeader);
    _routines.add("RemoveNPCFromPartyToBase", VT_I, {VT_I}, &routine::removeNPCFromPartyToBase);
    _routines.add("CreatureFlourishWeapon", VT_V, {VT_O}, &routine::creatureFlourishWeapon);
    _routines.add("EffectMindTrick", VT_EFFECT, {}, &routine::effectMindTrick);
    _routines.add("EffectFactionModifier", VT_EFFECT, {VT_I}, &routine::effectFactionModifier);
    _routines.add("ChangeObjectAppearance", VT_V, {VT_O, VT_I}, &routine::changeObjectAppearance);
    _routines.add("GetIsXBox", VT_I, {}, &routine::getIsXBox);
    _routines.add("EffectDroidScramble", VT_EFFECT, {}, &routine::effectDroidScramble);
    _routines.add("ActionSwitchWeapons", VT_V, {}, &routine::actionSwitchWeapons);
    _routines.add("PlayOverlayAnimation", VT_V, {VT_O, VT_I}, &routine::playOverlayAnimation);
    _routines.add("UnlockAllSongs", VT_V, {}, &routine::unlockAllSongs);
    _routines.add("DisableMap", VT_V, {VT_I}, &routine::disableMap);
    _routines.add("DetonateMine", VT_V, {VT_O}, &routine::detonateMine);
    _routines.add("DisableHealthRegen", VT_V, {VT_I}, &routine::disableHealthRegen);
    _routines.add("SetCurrentForm", VT_V, {VT_O, VT_I}, &routine::setCurrentForm);
    _routines.add("SetDisableTransit", VT_V, {VT_I}, &routine::setDisableTransit);
    _routines.add("SetInputClass", VT_V, {VT_I}, &routine::setInputClass);
    _routines.add("SetForceAlwaysUpdate", VT_V, {VT_O, VT_I}, &routine::setForceAlwaysUpdate);
    _routines.add("EnableRain", VT_V, {VT_I}, &routine::enableRain);
    _routines.add("DisplayMessageBox", VT_V, {VT_I, VT_S}, &routine::displayMessageBox);
    _routines.add("DisplayDatapad", VT_V, {VT_O}, &routine::displayDatapad);
    _routines.add("RemoveHeartbeat", VT_V, {VT_O}, &routine::removeHeartbeat);
    _routines.add("RemoveEffectByID", VT_V, {VT_O, VT_I}, &routine::removeEffectByID);
    _routines.add("RemoveEffectByExactMatch", VT_V, {VT_O, VT_EFFECT}, &routine::removeEffectByExactMatch);
    _routines.add("AdjustCreatureSkills", VT_V, {VT_O, VT_I, VT_I}, &routine::adjustCreatureSkills);
    _routines.add("GetSkillRankBase", VT_I, {VT_I, VT_O}, &routine::getSkillRankBase);
    _routines.add("EnableRendering", VT_V, {VT_O, VT_I}, &routine::enableRendering);
    _routines.add("GetCombatActionsPending", VT_I, {VT_O}, &routine::getCombatActionsPending);
    _routines.add("SaveNPCByObject", VT_V, {VT_I, VT_O}, &routine::saveNPCByObject);
    _routines.add("SavePUPByObject", VT_V, {VT_I, VT_O}, &routine::savePUPByObject);
    _routines.add("GetIsPlayerMadeCharacter", VT_I, {VT_O}, &routine::getIsPlayerMadeCharacter);
    _routines.add("RebuildPartyTable", VT_V, {}, &routine::rebuildPartyTable);
}

} // namespace game

} // namespace reone
